/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { calendarEventsCreateCalendarEvent } from "../funcs/calendar-events-create-calendar-event.js";
import { calendarEventsDeleteCalendarEvent } from "../funcs/calendar-events-delete-calendar-event.js";
import { calendarEventsGetCalendarEvent } from "../funcs/calendar-events-get-calendar-event.js";
import { calendarEventsListCalendarEvents } from "../funcs/calendar-events-list-calendar-events.js";
import { calendarEventsUpdateCalendarEvent } from "../funcs/calendar-events-update-calendar-event.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CalendarEvents extends ClientSDK {
  /**
   * List calendar events
   */
  async listCalendarEvents(
    security: operations.ListCalendarEventsSecurity,
    request?: operations.ListCalendarEventsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListCalendarEventsResponse> {
    return unwrapAsync(calendarEventsListCalendarEvents(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a calendar event
   *
   * @remarks
   * Only manually-created events accepted via API; events synced from Google/Outlook/Apple are read-only.
   */
  async createCalendarEvent(
    security: operations.CreateCalendarEventSecurity,
    request: models.CalendarEventCreate,
    options?: RequestOptions,
  ): Promise<models.CalendarEvent> {
    return unwrapAsync(calendarEventsCreateCalendarEvent(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a calendar event
   */
  async getCalendarEvent(
    security: operations.GetCalendarEventSecurity,
    request: operations.GetCalendarEventRequest,
    options?: RequestOptions,
  ): Promise<models.CalendarEvent> {
    return unwrapAsync(calendarEventsGetCalendarEvent(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a calendar event
   */
  async deleteCalendarEvent(
    security: operations.DeleteCalendarEventSecurity,
    request: operations.DeleteCalendarEventRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(calendarEventsDeleteCalendarEvent(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a calendar event
   *
   * @remarks
   * Externally-sourced events (google/microsoft/apple) are read-only.
   */
  async updateCalendarEvent(
    security: operations.UpdateCalendarEventSecurity,
    request: operations.UpdateCalendarEventRequest,
    options?: RequestOptions,
  ): Promise<models.CalendarEvent> {
    return unwrapAsync(calendarEventsUpdateCalendarEvent(
      this,
      security,
      request,
      options,
    ));
  }
}
