/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { calendarEventsCreate } from "../funcs/calendar-events-create.js";
import { calendarEventsDelete } from "../funcs/calendar-events-delete.js";
import { calendarEventsGet } from "../funcs/calendar-events-get.js";
import { calendarEventsList } from "../funcs/calendar-events-list.js";
import { calendarEventsUpdate } from "../funcs/calendar-events-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CalendarEvents extends ClientSDK {
  /**
   * List calendar events
   */
  async list(
    security: operations.ListCalendarEventsSecurity,
    request?: operations.ListCalendarEventsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListCalendarEventsResponse> {
    return unwrapAsync(calendarEventsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a calendar event
   *
   * @remarks
   * Only manually-created events accepted via API; events synced from Google/Outlook/Apple are read-only.
   */
  async create(
    security: operations.CreateCalendarEventSecurity,
    request: models.CalendarEventCreate,
    options?: RequestOptions,
  ): Promise<models.CalendarEvent> {
    return unwrapAsync(calendarEventsCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a calendar event
   */
  async get(
    security: operations.GetCalendarEventSecurity,
    request: operations.GetCalendarEventRequest,
    options?: RequestOptions,
  ): Promise<models.CalendarEvent> {
    return unwrapAsync(calendarEventsGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a calendar event
   *
   * @remarks
   * Externally-sourced events (google/microsoft/apple) are read-only.
   */
  async update(
    security: operations.UpdateCalendarEventSecurity,
    request: operations.UpdateCalendarEventRequest,
    options?: RequestOptions,
  ): Promise<models.CalendarEvent> {
    return unwrapAsync(calendarEventsUpdate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a calendar event
   */
  async delete(
    security: operations.DeleteCalendarEventSecurity,
    request: operations.DeleteCalendarEventRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(calendarEventsDelete(
      this,
      security,
      request,
      options,
    ));
  }
}
