/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { catalogItemsCreateCatalogItem } from "../funcs/catalog-items-create-catalog-item.js";
import { catalogItemsDeleteCatalogItem } from "../funcs/catalog-items-delete-catalog-item.js";
import { catalogItemsGetCatalogItem } from "../funcs/catalog-items-get-catalog-item.js";
import { catalogItemsListCatalogItems } from "../funcs/catalog-items-list-catalog-items.js";
import { catalogItemsUpdateCatalogItem } from "../funcs/catalog-items-update-catalog-item.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class CatalogItems extends ClientSDK {
  /**
   * List catalog items
   */
  async listCatalogItems(
    security: operations.ListCatalogItemsSecurity,
    request?: operations.ListCatalogItemsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListCatalogItemsResponse> {
    return unwrapAsync(catalogItemsListCatalogItems(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a catalog item
   *
   * @remarks
   * `type: expense` items track cost; `type: charge` items track revenue.
   */
  async createCatalogItem(
    security: operations.CreateCatalogItemSecurity,
    request: models.CatalogItemCreate,
    options?: RequestOptions,
  ): Promise<models.CatalogItem> {
    return unwrapAsync(catalogItemsCreateCatalogItem(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a catalog item
   */
  async getCatalogItem(
    security: operations.GetCatalogItemSecurity,
    request: operations.GetCatalogItemRequest,
    options?: RequestOptions,
  ): Promise<models.CatalogItem> {
    return unwrapAsync(catalogItemsGetCatalogItem(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a catalog item
   */
  async updateCatalogItem(
    security: operations.UpdateCatalogItemSecurity,
    request: operations.UpdateCatalogItemRequest,
    options?: RequestOptions,
  ): Promise<models.CatalogItem> {
    return unwrapAsync(catalogItemsUpdateCatalogItem(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a catalog item
   */
  async deleteCatalogItem(
    security: operations.DeleteCatalogItemSecurity,
    request: operations.DeleteCatalogItemRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(catalogItemsDeleteCatalogItem(
      this,
      security,
      request,
      options,
    ));
  }
}
