/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { catalogItemsCreate } from "../funcs/catalog-items-create.js";
import { catalogItemsDelete } from "../funcs/catalog-items-delete.js";
import { catalogItemsGet } from "../funcs/catalog-items-get.js";
import { catalogItemsList } from "../funcs/catalog-items-list.js";
import { catalogItemsUpdate } from "../funcs/catalog-items-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class CatalogItems extends ClientSDK {
  /**
   * List catalog items
   */
  async list(
    security: operations.ListCatalogItemsSecurity,
    request?: operations.ListCatalogItemsRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListCatalogItemsResponse, { page: number }>
  > {
    return unwrapResultIterator(catalogItemsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a catalog item
   *
   * @remarks
   * `type: expense` items track cost; `type: charge` items track revenue.
   */
  async create(
    security: operations.CreateCatalogItemSecurity,
    request: operations.CreateCatalogItemRequest,
    options?: RequestOptions,
  ): Promise<models.CatalogItem> {
    return unwrapAsync(catalogItemsCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a catalog item
   */
  async get(
    security: operations.GetCatalogItemSecurity,
    request: operations.GetCatalogItemRequest,
    options?: RequestOptions,
  ): Promise<models.CatalogItem> {
    return unwrapAsync(catalogItemsGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a catalog item
   */
  async delete(
    security: operations.DeleteCatalogItemSecurity,
    request: operations.DeleteCatalogItemRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(catalogItemsDelete(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a catalog item
   */
  async update(
    security: operations.UpdateCatalogItemSecurity,
    request: operations.UpdateCatalogItemRequest,
    options?: RequestOptions,
  ): Promise<models.CatalogItem> {
    return unwrapAsync(catalogItemsUpdate(
      this,
      security,
      request,
      options,
    ));
  }
}
