/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contractsCreateContract } from "../funcs/contracts-create-contract.js";
import { contractsDeleteContract } from "../funcs/contracts-delete-contract.js";
import { contractsGetContract } from "../funcs/contracts-get-contract.js";
import { contractsListContracts } from "../funcs/contracts-list-contracts.js";
import { contractsUpdateContract } from "../funcs/contracts-update-contract.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Contracts extends ClientSDK {
  /**
   * List contracts
   */
  async listContracts(
    security: operations.ListContractsSecurity,
    request?: operations.ListContractsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListContractsResponse> {
    return unwrapAsync(contractsListContracts(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a draft contract
   *
   * @remarks
   * Creates a draft contract. Signing flow, signer assignment, and Tiptap content are dashboard-managed.
   */
  async createContract(
    security: operations.CreateContractSecurity,
    request: models.ContractCreate,
    options?: RequestOptions,
  ): Promise<models.Contract> {
    return unwrapAsync(contractsCreateContract(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a contract
   */
  async getContract(
    security: operations.GetContractSecurity,
    request: operations.GetContractRequest,
    options?: RequestOptions,
  ): Promise<models.Contract> {
    return unwrapAsync(contractsGetContract(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a contract (limited fields)
   *
   * @remarks
   * Only `title`, `effectiveDate`, `expirationDate`, and `archived` are editable via v1. `title`/`effectiveDate`/`expirationDate` are draft-only; `archived` is always editable.
   */
  async updateContract(
    security: operations.UpdateContractSecurity,
    request: operations.UpdateContractRequest,
    options?: RequestOptions,
  ): Promise<models.Contract> {
    return unwrapAsync(contractsUpdateContract(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a contract (only drafts)
   */
  async deleteContract(
    security: operations.DeleteContractSecurity,
    request: operations.DeleteContractRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(contractsDeleteContract(
      this,
      security,
      request,
      options,
    ));
  }
}
