/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contractsCreate } from "../funcs/contracts-create.js";
import { contractsDelete } from "../funcs/contracts-delete.js";
import { contractsGet } from "../funcs/contracts-get.js";
import { contractsList } from "../funcs/contracts-list.js";
import { contractsUpdate } from "../funcs/contracts-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Contracts extends ClientSDK {
  /**
   * List contracts
   */
  async list(
    security: operations.ListContractsSecurity,
    request?: operations.ListContractsRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListContractsResponse, { page: number }>> {
    return unwrapResultIterator(contractsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a draft contract
   *
   * @remarks
   * Creates a draft contract. Signing flow, signer assignment, and Tiptap content are dashboard-managed.
   */
  async create(
    security: operations.CreateContractSecurity,
    request: operations.CreateContractRequest,
    options?: RequestOptions,
  ): Promise<models.Contract> {
    return unwrapAsync(contractsCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a contract
   */
  async get(
    security: operations.GetContractSecurity,
    request: operations.GetContractRequest,
    options?: RequestOptions,
  ): Promise<models.Contract> {
    return unwrapAsync(contractsGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a contract (only drafts)
   */
  async delete(
    security: operations.DeleteContractSecurity,
    request: operations.DeleteContractRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(contractsDelete(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a contract (limited fields)
   *
   * @remarks
   * Only `title`, `effectiveDate`, `expirationDate`, and `archived` are editable via v1. `title`/`effectiveDate`/`expirationDate` are draft-only; `archived` is always editable.
   */
  async update(
    security: operations.UpdateContractSecurity,
    request: operations.UpdateContractRequest,
    options?: RequestOptions,
  ): Promise<models.Contract> {
    return unwrapAsync(contractsUpdate(
      this,
      security,
      request,
      options,
    ));
  }
}
