/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { contactsCreateContact } from "../funcs/contacts-create-contact.js";
import { contactsDeleteContact } from "../funcs/contacts-delete-contact.js";
import { contactsGetContact } from "../funcs/contacts-get-contact.js";
import { contactsListContacts } from "../funcs/contacts-list-contacts.js";
import { contactsUpdateContact } from "../funcs/contacts-update-contact.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Contacts extends ClientSDK {
  /**
   * List contacts
   */
  async listContacts(
    security: operations.ListContactsSecurity,
    request?: operations.ListContactsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListContactsResponse> {
    return unwrapAsync(contactsListContacts(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a contact
   */
  async createContact(
    security: operations.CreateContactSecurity,
    request: models.ContactCreate,
    options?: RequestOptions,
  ): Promise<models.Contact> {
    return unwrapAsync(contactsCreateContact(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a contact
   */
  async getContact(
    security: operations.GetContactSecurity,
    request: operations.GetContactRequest,
    options?: RequestOptions,
  ): Promise<models.Contact> {
    return unwrapAsync(contactsGetContact(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a contact
   */
  async deleteContact(
    security: operations.DeleteContactSecurity,
    request: operations.DeleteContactRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(contactsDeleteContact(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a contact
   */
  async updateContact(
    security: operations.UpdateContactSecurity,
    request: operations.UpdateContactRequest,
    options?: RequestOptions,
  ): Promise<models.Contact> {
    return unwrapAsync(contactsUpdateContact(
      this,
      security,
      request,
      options,
    ));
  }
}
