/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { documentVersionsGet } from "../funcs/document-versions-get.js";
import { documentVersionsList } from "../funcs/document-versions-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class DocumentVersions extends ClientSDK {
  /**
   * List document versions
   *
   * @remarks
   * Read-only audit trail of issued document versions across smart-files, invoices, and standalone contracts. Checkpoints (internal draft edit-history) are never returned. Frozen content and client access tokens are not exposed.
   */
  async list(
    security: operations.ListDocumentVersionsSecurity,
    request?: operations.ListDocumentVersionsRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListDocumentVersionsResponse, { page: number }>
  > {
    return unwrapResultIterator(documentVersionsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a document version
   */
  async get(
    security: operations.GetDocumentVersionSecurity,
    request: operations.GetDocumentVersionRequest,
    options?: RequestOptions,
  ): Promise<models.DocumentVersion> {
    return unwrapAsync(documentVersionsGet(
      this,
      security,
      request,
      options,
    ));
  }
}
