/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { eventDaysCreate } from "../funcs/event-days-create.js";
import { eventDaysDelete } from "../funcs/event-days-delete.js";
import { eventDaysGet } from "../funcs/event-days-get.js";
import { eventDaysList } from "../funcs/event-days-list.js";
import { eventDaysUpdate } from "../funcs/event-days-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class EventDays extends ClientSDK {
  /**
   * List event days
   */
  async list(
    security: operations.ListEventDaysSecurity,
    request?: operations.ListEventDaysRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListEventDaysResponse, { page: number }>> {
    return unwrapResultIterator(eventDaysList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create an event day
   */
  async create(
    security: operations.CreateEventDaySecurity,
    request: operations.CreateEventDayRequest,
    options?: RequestOptions,
  ): Promise<models.EventDay> {
    return unwrapAsync(eventDaysCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get an event day
   */
  async get(
    security: operations.GetEventDaySecurity,
    request: operations.GetEventDayRequest,
    options?: RequestOptions,
  ): Promise<models.EventDay> {
    return unwrapAsync(eventDaysGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete an event day
   */
  async delete(
    security: operations.DeleteEventDaySecurity,
    request: operations.DeleteEventDayRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(eventDaysDelete(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update an event day
   */
  async update(
    security: operations.UpdateEventDaySecurity,
    request: operations.UpdateEventDayRequest,
    options?: RequestOptions,
  ): Promise<models.EventDay> {
    return unwrapAsync(eventDaysUpdate(
      this,
      security,
      request,
      options,
    ));
  }
}
