/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { formSubmissionsGet } from "../funcs/form-submissions-get.js";
import { formSubmissionsList } from "../funcs/form-submissions-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class FormSubmissions extends ClientSDK {
  /**
   * List form submissions
   *
   * @remarks
   * Answers are omitted from the list (returned as `null`); fetch a single submission to read them.
   */
  async list(
    security: operations.ListFormSubmissionsSecurity,
    request?: operations.ListFormSubmissionsRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListFormSubmissionsResponse, { page: number }>
  > {
    return unwrapResultIterator(formSubmissionsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a form submission (with answers)
   */
  async get(
    security: operations.GetFormSubmissionSecurity,
    request: operations.GetFormSubmissionRequest,
    options?: RequestOptions,
  ): Promise<models.FormSubmission> {
    return unwrapAsync(formSubmissionsGet(
      this,
      security,
      request,
      options,
    ));
  }
}
