/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { formAttachmentsGet } from "../funcs/form-attachments-get.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class FormAttachments extends ClientSDK {
  /**
   * Get a form attachment download link
   *
   * @remarks
   * Returns the attachment metadata plus a short-lived direct download link. The link expires — fetch it promptly and do not store it; request the attachment again for a fresh one. The scope is `form-submissions:read`: an attachment belongs to a submission, so a token that may read submissions may read their files. The link always downloads rather than renders inline, because these bytes were uploaded by an anonymous visitor through a public form.
   */
  async get(
    security: operations.GetFormAttachmentSecurity,
    request: operations.GetFormAttachmentRequest,
    options?: RequestOptions,
  ): Promise<models.FormAttachmentDownload> {
    return unwrapAsync(formAttachmentsGet(
      this,
      security,
      request,
      options,
    ));
  }
}
