/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { formsGet } from "../funcs/forms-get.js";
import { formsList } from "../funcs/forms-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Forms extends ClientSDK {
  /**
   * List forms
   */
  async list(
    security: operations.ListFormsSecurity,
    request?: operations.ListFormsRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListFormsResponse, { page: number }>> {
    return unwrapResultIterator(formsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a form
   */
  async get(
    security: operations.GetFormSecurity,
    request: operations.GetFormRequest,
    options?: RequestOptions,
  ): Promise<models.Form> {
    return unwrapAsync(formsGet(
      this,
      security,
      request,
      options,
    ));
  }
}
