/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { formsAndAgreementsGet } from "../funcs/forms-and-agreements-get.js";
import { formsAndAgreementsList } from "../funcs/forms-and-agreements-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class FormsAndAgreements extends ClientSDK {
  /**
   * List proposals
   */
  async list(
    security: operations.ListClientDocumentsSecurity,
    request?: operations.ListClientDocumentsRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListClientDocumentsResponse, { page: number }>
  > {
    return unwrapResultIterator(formsAndAgreementsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a proposal
   */
  async get(
    security: operations.GetClientDocumentSecurity,
    request: operations.GetClientDocumentRequest,
    options?: RequestOptions,
  ): Promise<models.ClientDocument> {
    return unwrapAsync(formsAndAgreementsGet(
      this,
      security,
      request,
      options,
    ));
  }
}
