/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { inquiriesCreate } from "../funcs/inquiries-create.js";
import { inquiriesDelete } from "../funcs/inquiries-delete.js";
import { inquiriesGet } from "../funcs/inquiries-get.js";
import { inquiriesList } from "../funcs/inquiries-list.js";
import { inquiriesUpdate } from "../funcs/inquiries-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Inquiries extends ClientSDK {
  /**
   * List inquiries
   */
  async list(
    security: operations.ListInquiriesSecurity,
    request?: operations.ListInquiriesRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListInquiriesResponse, { page: number }>> {
    return unwrapResultIterator(inquiriesList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create an inquiry
   *
   * @remarks
   * Inquiries created via the API land in `new` status. Conversion (to Client + Project) is dashboard-only in v1.
   */
  async create(
    security: operations.CreateInquirySecurity,
    request: operations.CreateInquiryRequest,
    options?: RequestOptions,
  ): Promise<models.Inquiry> {
    return unwrapAsync(inquiriesCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get an inquiry
   */
  async get(
    security: operations.GetInquirySecurity,
    request: operations.GetInquiryRequest,
    options?: RequestOptions,
  ): Promise<models.Inquiry> {
    return unwrapAsync(inquiriesGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete an inquiry
   */
  async delete(
    security: operations.DeleteInquirySecurity,
    request: operations.DeleteInquiryRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(inquiriesDelete(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update an inquiry
   *
   * @remarks
   * Status `converted` is terminal and set by the dashboard conversion flow. Transitions out of `converted` or `spam` are blocked.
   */
  async update(
    security: operations.UpdateInquirySecurity,
    request: operations.UpdateInquiryRequest,
    options?: RequestOptions,
  ): Promise<models.Inquiry> {
    return unwrapAsync(inquiriesUpdate(
      this,
      security,
      request,
      options,
    ));
  }
}
