/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { inquiriesCreate } from "../funcs/inquiries-create.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Inquiries extends ClientSDK {
  /**
   * Submit an inquiry (capture a lead)
   */
  async create(
    security: operations.CreateInquirySecurity,
    request: operations.CreateInquiryRequest,
    options?: RequestOptions,
  ): Promise<models.Inquiry> {
    return unwrapAsync(inquiriesCreate(
      this,
      security,
      request,
      options,
    ));
  }
}
