/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesCreate } from "../funcs/invoices-create.js";
import { invoicesDelete } from "../funcs/invoices-delete.js";
import { invoicesGet } from "../funcs/invoices-get.js";
import { invoicesList } from "../funcs/invoices-list.js";
import { invoicesUpdate } from "../funcs/invoices-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Invoices extends ClientSDK {
  /**
   * List invoices
   */
  async list(
    security: operations.ListInvoicesSecurity,
    request?: operations.ListInvoicesRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListInvoicesResponse, { page: number }>> {
    return unwrapResultIterator(invoicesList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create an invoice
   *
   * @remarks
   * Status `paid` and `partial` are system-derived from Payments; do not set them directly. `overdue` is not a status — it is a derived read-only boolean field (past due with a balance owing).
   */
  async create(
    security: operations.CreateInvoiceSecurity,
    request: operations.CreateInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.Invoice> {
    return unwrapAsync(invoicesCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get an invoice
   */
  async get(
    security: operations.GetInvoiceSecurity,
    request: operations.GetInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.Invoice> {
    return unwrapAsync(invoicesGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete an invoice (only drafts)
   */
  async delete(
    security: operations.DeleteInvoiceSecurity,
    request: operations.DeleteInvoiceRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(invoicesDelete(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update an invoice (line items not editable in v1)
   */
  async update(
    security: operations.UpdateInvoiceSecurity,
    request: operations.UpdateInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.Invoice> {
    return unwrapAsync(invoicesUpdate(
      this,
      security,
      request,
      options,
    ));
  }
}
