/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesCreateInvoice } from "../funcs/invoices-create-invoice.js";
import { invoicesDeleteInvoice } from "../funcs/invoices-delete-invoice.js";
import { invoicesGetInvoice } from "../funcs/invoices-get-invoice.js";
import { invoicesListInvoices } from "../funcs/invoices-list-invoices.js";
import { invoicesUpdateInvoice } from "../funcs/invoices-update-invoice.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Invoices extends ClientSDK {
  /**
   * List invoices
   */
  async listInvoices(
    security: operations.ListInvoicesSecurity,
    request?: operations.ListInvoicesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListInvoicesResponse> {
    return unwrapAsync(invoicesListInvoices(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create an invoice
   *
   * @remarks
   * Status `paid`, `partial`, and `overdue` are system-derived from Payments and the due date; do not set them directly.
   */
  async createInvoice(
    security: operations.CreateInvoiceSecurity,
    request: models.InvoiceCreate,
    options?: RequestOptions,
  ): Promise<models.Invoice> {
    return unwrapAsync(invoicesCreateInvoice(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get an invoice
   */
  async getInvoice(
    security: operations.GetInvoiceSecurity,
    request: operations.GetInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.Invoice> {
    return unwrapAsync(invoicesGetInvoice(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete an invoice (only drafts)
   */
  async deleteInvoice(
    security: operations.DeleteInvoiceSecurity,
    request: operations.DeleteInvoiceRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(invoicesDeleteInvoice(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update an invoice (line items not editable in v1)
   */
  async updateInvoice(
    security: operations.UpdateInvoiceSecurity,
    request: operations.UpdateInvoiceRequest,
    options?: RequestOptions,
  ): Promise<models.Invoice> {
    return unwrapAsync(invoicesUpdateInvoice(
      this,
      security,
      request,
      options,
    ));
  }
}
