/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { milestonesCreate } from "../funcs/milestones-create.js";
import { milestonesDelete } from "../funcs/milestones-delete.js";
import { milestonesGet } from "../funcs/milestones-get.js";
import { milestonesList } from "../funcs/milestones-list.js";
import { milestonesUpdate } from "../funcs/milestones-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Milestones extends ClientSDK {
  /**
   * List milestones
   */
  async list(
    security: operations.ListMilestonesSecurity,
    request?: operations.ListMilestonesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListMilestonesResponse> {
    return unwrapAsync(milestonesList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a milestone
   *
   * @remarks
   * Milestones attach to either a project or a proposal — `parentType` + `parentId` are both required.
   */
  async create(
    security: operations.CreateMilestoneSecurity,
    request: models.MilestoneCreate,
    options?: RequestOptions,
  ): Promise<models.Milestone> {
    return unwrapAsync(milestonesCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a milestone
   */
  async get(
    security: operations.GetMilestoneSecurity,
    request: operations.GetMilestoneRequest,
    options?: RequestOptions,
  ): Promise<models.Milestone> {
    return unwrapAsync(milestonesGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a milestone
   */
  async update(
    security: operations.UpdateMilestoneSecurity,
    request: operations.UpdateMilestoneRequest,
    options?: RequestOptions,
  ): Promise<models.Milestone> {
    return unwrapAsync(milestonesUpdate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a milestone
   */
  async delete(
    security: operations.DeleteMilestoneSecurity,
    request: operations.DeleteMilestoneRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(milestonesDelete(
      this,
      security,
      request,
      options,
    ));
  }
}
