/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsCreate } from "../funcs/payments-create.js";
import { paymentsGet } from "../funcs/payments-get.js";
import { paymentsList } from "../funcs/payments-list.js";
import { paymentsUpdate } from "../funcs/payments-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Payments extends ClientSDK {
  /**
   * List payments
   */
  async list(
    security: operations.ListPaymentsSecurity,
    request?: operations.ListPaymentsRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListPaymentsResponse, { page: number }>> {
    return unwrapResultIterator(paymentsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Record a manual payment
   *
   * @remarks
   * Records a manually-collected payment (check, bank transfer, cash, etc.). Stripe payments are recorded automatically via webhooks and cannot be created here. Payments are immutable after creation except for `reference` and `notes`. To reverse a payment, record a refund (kind=refund, negative amount, refundOfId pointing at the original).
   */
  async create(
    security: operations.CreatePaymentSecurity,
    request: operations.CreatePaymentRequest,
    options?: RequestOptions,
  ): Promise<models.Payment> {
    return unwrapAsync(paymentsCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a payment
   */
  async get(
    security: operations.GetPaymentSecurity,
    request: operations.GetPaymentRequest,
    options?: RequestOptions,
  ): Promise<models.Payment> {
    return unwrapAsync(paymentsGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a payment (notes/reference only — payments are otherwise immutable)
   */
  async update(
    security: operations.UpdatePaymentSecurity,
    request: operations.UpdatePaymentRequest,
    options?: RequestOptions,
  ): Promise<models.Payment> {
    return unwrapAsync(paymentsUpdate(
      this,
      security,
      request,
      options,
    ));
  }
}
