/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { paymentsCreatePayment } from "../funcs/payments-create-payment.js";
import { paymentsGetPayment } from "../funcs/payments-get-payment.js";
import { paymentsListPayments } from "../funcs/payments-list-payments.js";
import { paymentsUpdatePayment } from "../funcs/payments-update-payment.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Payments extends ClientSDK {
  /**
   * List payments
   */
  async listPayments(
    security: operations.ListPaymentsSecurity,
    request?: operations.ListPaymentsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPaymentsResponse> {
    return unwrapAsync(paymentsListPayments(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Record a manual payment
   *
   * @remarks
   * Records a manually-collected payment (check, bank transfer, cash, etc.). Stripe payments are recorded automatically via webhooks and cannot be created here. Payments are immutable after creation except for `reference` and `notes`. To reverse a payment, record a refund (kind=refund, negative amount, refundOfId pointing at the original).
   */
  async createPayment(
    security: operations.CreatePaymentSecurity,
    request: models.PaymentCreate,
    options?: RequestOptions,
  ): Promise<models.Payment> {
    return unwrapAsync(paymentsCreatePayment(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a payment
   */
  async getPayment(
    security: operations.GetPaymentSecurity,
    request: operations.GetPaymentRequest,
    options?: RequestOptions,
  ): Promise<models.Payment> {
    return unwrapAsync(paymentsGetPayment(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a payment (notes/reference only — payments are otherwise immutable)
   */
  async updatePayment(
    security: operations.UpdatePaymentSecurity,
    request: operations.UpdatePaymentRequest,
    options?: RequestOptions,
  ): Promise<models.Payment> {
    return unwrapAsync(paymentsUpdatePayment(
      this,
      security,
      request,
      options,
    ));
  }
}
