/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { payoutsGetPayout } from "../funcs/payouts-get-payout.js";
import { payoutsListPayouts } from "../funcs/payouts-list-payouts.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Payouts extends ClientSDK {
  /**
   * List payouts
   */
  async listPayouts(
    security: operations.ListPayoutsSecurity,
    request?: operations.ListPayoutsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListPayoutsResponse> {
    return unwrapAsync(payoutsListPayouts(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a payout
   */
  async getPayout(
    security: operations.GetPayoutSecurity,
    request: operations.GetPayoutRequest,
    options?: RequestOptions,
  ): Promise<models.Payout> {
    return unwrapAsync(payoutsGetPayout(
      this,
      security,
      request,
      options,
    ));
  }
}
