/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectsCreate } from "../funcs/projects-create.js";
import { projectsDelete } from "../funcs/projects-delete.js";
import { projectsGet } from "../funcs/projects-get.js";
import { projectsList } from "../funcs/projects-list.js";
import { projectsUpdate } from "../funcs/projects-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Projects extends ClientSDK {
  /**
   * List projects
   */
  async list(
    security: operations.ListProjectsSecurity,
    request?: operations.ListProjectsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListProjectsResponse> {
    return unwrapAsync(projectsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a project
   */
  async create(
    security: operations.CreateProjectSecurity,
    request: models.ProjectCreate,
    options?: RequestOptions,
  ): Promise<models.Project> {
    return unwrapAsync(projectsCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a project
   */
  async get(
    security: operations.GetProjectSecurity,
    request: operations.GetProjectRequest,
    options?: RequestOptions,
  ): Promise<models.Project> {
    return unwrapAsync(projectsGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a project
   */
  async update(
    security: operations.UpdateProjectSecurity,
    request: operations.UpdateProjectRequest,
    options?: RequestOptions,
  ): Promise<models.Project> {
    return unwrapAsync(projectsUpdate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a project
   */
  async delete(
    security: operations.DeleteProjectSecurity,
    request: operations.DeleteProjectRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(projectsDelete(
      this,
      security,
      request,
      options,
    ));
  }
}
