/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { proposalsCreateProposal } from "../funcs/proposals-create-proposal.js";
import { proposalsDeleteProposal } from "../funcs/proposals-delete-proposal.js";
import { proposalsGetProposal } from "../funcs/proposals-get-proposal.js";
import { proposalsListProposals } from "../funcs/proposals-list-proposals.js";
import { proposalsUpdateProposal } from "../funcs/proposals-update-proposal.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Proposals extends ClientSDK {
  /**
   * List proposals
   */
  async listProposals(
    security: operations.ListProposalsSecurity,
    request?: operations.ListProposalsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListProposalsResponse> {
    return unwrapAsync(proposalsListProposals(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a proposal (metadata only — rich-text content is dashboard-managed)
   *
   * @remarks
   * Creates a draft proposal. The narrative content (Tiptap document) and line items are not editable via the v1 API; use the dashboard.
   */
  async createProposal(
    security: operations.CreateProposalSecurity,
    request: models.ProposalCreate,
    options?: RequestOptions,
  ): Promise<models.Proposal> {
    return unwrapAsync(proposalsCreateProposal(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a proposal
   */
  async getProposal(
    security: operations.GetProposalSecurity,
    request: operations.GetProposalRequest,
    options?: RequestOptions,
  ): Promise<models.Proposal> {
    return unwrapAsync(proposalsGetProposal(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a proposal
   *
   * @remarks
   * Status transitions to `accepted`/`rejected`/`expired` are system-driven; do not set them directly.
   */
  async updateProposal(
    security: operations.UpdateProposalSecurity,
    request: operations.UpdateProposalRequest,
    options?: RequestOptions,
  ): Promise<models.Proposal> {
    return unwrapAsync(proposalsUpdateProposal(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a proposal (only drafts)
   */
  async deleteProposal(
    security: operations.DeleteProposalSecurity,
    request: operations.DeleteProposalRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(proposalsDeleteProposal(
      this,
      security,
      request,
      options,
    ));
  }
}
