/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { proposalsCreate } from "../funcs/proposals-create.js";
import { proposalsDelete } from "../funcs/proposals-delete.js";
import { proposalsGet } from "../funcs/proposals-get.js";
import { proposalsList } from "../funcs/proposals-list.js";
import { proposalsUpdate } from "../funcs/proposals-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Proposals extends ClientSDK {
  /**
   * List proposals
   */
  async list(
    security: operations.ListProposalsSecurity,
    request?: operations.ListProposalsRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListProposalsResponse, { page: number }>> {
    return unwrapResultIterator(proposalsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a proposal (metadata only — rich-text content is dashboard-managed)
   *
   * @remarks
   * Creates a draft proposal. The narrative content (Tiptap document) and line items are not editable via the v1 API; use the dashboard.
   */
  async create(
    security: operations.CreateProposalSecurity,
    request: operations.CreateProposalRequest,
    options?: RequestOptions,
  ): Promise<models.Proposal> {
    return unwrapAsync(proposalsCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a proposal
   */
  async get(
    security: operations.GetProposalSecurity,
    request: operations.GetProposalRequest,
    options?: RequestOptions,
  ): Promise<models.Proposal> {
    return unwrapAsync(proposalsGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a proposal (only drafts)
   */
  async delete(
    security: operations.DeleteProposalSecurity,
    request: operations.DeleteProposalRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(proposalsDelete(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a proposal
   *
   * @remarks
   * Status transitions to `accepted`/`rejected`/`expired` are system-driven; do not set them directly.
   */
  async update(
    security: operations.UpdateProposalSecurity,
    request: operations.UpdateProposalRequest,
    options?: RequestOptions,
  ): Promise<models.Proposal> {
    return unwrapAsync(proposalsUpdate(
      this,
      security,
      request,
      options,
    ));
  }
}
