/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { salesGet } from "../funcs/sales-get.js";
import { salesList } from "../funcs/sales-list.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Sales extends ClientSDK {
  /**
   * List sales
   */
  async list(
    security: operations.ListSalesSecurity,
    request?: operations.ListSalesRequest | undefined,
    options?: RequestOptions,
  ): Promise<PageIterator<operations.ListSalesResponse, { page: number }>> {
    return unwrapResultIterator(salesList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a sale
   */
  async get(
    security: operations.GetSaleSecurity,
    request: operations.GetSaleRequest,
    options?: RequestOptions,
  ): Promise<models.Sale> {
    return unwrapAsync(salesGet(
      this,
      security,
      request,
      options,
    ));
  }
}
