/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ClientSDK } from "../lib/sdks.js";
import { CalendarEvents } from "./calendar-events.js";
import { CatalogItems } from "./catalog-items.js";
import { Clients } from "./clients.js";
import { Contacts } from "./contacts.js";
import { Contracts } from "./contracts.js";
import { DocumentVersions } from "./document-versions.js";
import { EventDayVendors } from "./event-day-vendors.js";
import { EventDays } from "./event-days.js";
import { FormSubmissions } from "./form-submissions.js";
import { FormsAndAgreements } from "./forms-and-agreements.js";
import { Forms } from "./forms.js";
import { Inquiries } from "./inquiries.js";
import { Invoices } from "./invoices.js";
import { Milestones } from "./milestones.js";
import { Payments } from "./payments.js";
import { Payouts } from "./payouts.js";
import { Projects } from "./projects.js";
import { TimeEntries } from "./time-entries.js";
import { TimelineItems } from "./timeline-items.js";
import { Transactions } from "./transactions.js";
import { Vendors } from "./vendors.js";
import { Venues } from "./venues.js";
import { Webhooks } from "./webhooks.js";

export class ClientCasa extends ClientSDK {
  private _clients?: Clients;
  get clients(): Clients {
    return (this._clients ??= new Clients(this._options));
  }

  private _contacts?: Contacts;
  get contacts(): Contacts {
    return (this._contacts ??= new Contacts(this._options));
  }

  private _projects?: Projects;
  get projects(): Projects {
    return (this._projects ??= new Projects(this._options));
  }

  private _invoices?: Invoices;
  get invoices(): Invoices {
    return (this._invoices ??= new Invoices(this._options));
  }

  private _contracts?: Contracts;
  get contracts(): Contracts {
    return (this._contracts ??= new Contracts(this._options));
  }

  private _formsAndAgreements?: FormsAndAgreements;
  get formsAndAgreements(): FormsAndAgreements {
    return (this._formsAndAgreements ??= new FormsAndAgreements(this._options));
  }

  private _documentVersions?: DocumentVersions;
  get documentVersions(): DocumentVersions {
    return (this._documentVersions ??= new DocumentVersions(this._options));
  }

  private _forms?: Forms;
  get forms(): Forms {
    return (this._forms ??= new Forms(this._options));
  }

  private _formSubmissions?: FormSubmissions;
  get formSubmissions(): FormSubmissions {
    return (this._formSubmissions ??= new FormSubmissions(this._options));
  }

  private _inquiries?: Inquiries;
  get inquiries(): Inquiries {
    return (this._inquiries ??= new Inquiries(this._options));
  }

  private _payments?: Payments;
  get payments(): Payments {
    return (this._payments ??= new Payments(this._options));
  }

  private _payouts?: Payouts;
  get payouts(): Payouts {
    return (this._payouts ??= new Payouts(this._options));
  }

  private _timeEntries?: TimeEntries;
  get timeEntries(): TimeEntries {
    return (this._timeEntries ??= new TimeEntries(this._options));
  }

  private _milestones?: Milestones;
  get milestones(): Milestones {
    return (this._milestones ??= new Milestones(this._options));
  }

  private _calendarEvents?: CalendarEvents;
  get calendarEvents(): CalendarEvents {
    return (this._calendarEvents ??= new CalendarEvents(this._options));
  }

  private _transactions?: Transactions;
  get transactions(): Transactions {
    return (this._transactions ??= new Transactions(this._options));
  }

  private _catalogItems?: CatalogItems;
  get catalogItems(): CatalogItems {
    return (this._catalogItems ??= new CatalogItems(this._options));
  }

  private _eventDays?: EventDays;
  get eventDays(): EventDays {
    return (this._eventDays ??= new EventDays(this._options));
  }

  private _timelineItems?: TimelineItems;
  get timelineItems(): TimelineItems {
    return (this._timelineItems ??= new TimelineItems(this._options));
  }

  private _eventDayVendors?: EventDayVendors;
  get eventDayVendors(): EventDayVendors {
    return (this._eventDayVendors ??= new EventDayVendors(this._options));
  }

  private _vendors?: Vendors;
  get vendors(): Vendors {
    return (this._vendors ??= new Vendors(this._options));
  }

  private _venues?: Venues;
  get venues(): Venues {
    return (this._venues ??= new Venues(this._options));
  }

  private _webhooks?: Webhooks;
  get webhooks(): Webhooks {
    return (this._webhooks ??= new Webhooks(this._options));
  }
}
