/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { timelineItemsCreate } from "../funcs/timeline-items-create.js";
import { timelineItemsDelete } from "../funcs/timeline-items-delete.js";
import { timelineItemsGet } from "../funcs/timeline-items-get.js";
import { timelineItemsList } from "../funcs/timeline-items-list.js";
import { timelineItemsUpdate } from "../funcs/timeline-items-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class TimelineItems extends ClientSDK {
  /**
   * List timeline items
   */
  async list(
    security: operations.ListTimelineItemsSecurity,
    request?: operations.ListTimelineItemsRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListTimelineItemsResponse, { page: number }>
  > {
    return unwrapResultIterator(timelineItemsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a timeline item
   */
  async create(
    security: operations.CreateTimelineItemSecurity,
    request: operations.CreateTimelineItemRequest,
    options?: RequestOptions,
  ): Promise<models.TimelineItem> {
    return unwrapAsync(timelineItemsCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a timeline item
   */
  async get(
    security: operations.GetTimelineItemSecurity,
    request: operations.GetTimelineItemRequest,
    options?: RequestOptions,
  ): Promise<models.TimelineItem> {
    return unwrapAsync(timelineItemsGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a timeline item
   */
  async delete(
    security: operations.DeleteTimelineItemSecurity,
    request: operations.DeleteTimelineItemRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(timelineItemsDelete(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a timeline item
   */
  async update(
    security: operations.UpdateTimelineItemSecurity,
    request: operations.UpdateTimelineItemRequest,
    options?: RequestOptions,
  ): Promise<models.TimelineItem> {
    return unwrapAsync(timelineItemsUpdate(
      this,
      security,
      request,
      options,
    ));
  }
}
