/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { timeEntriesCreate } from "../funcs/time-entries-create.js";
import { timeEntriesDelete } from "../funcs/time-entries-delete.js";
import { timeEntriesGet } from "../funcs/time-entries-get.js";
import { timeEntriesList } from "../funcs/time-entries-list.js";
import { timeEntriesUpdate } from "../funcs/time-entries-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class TimeEntries extends ClientSDK {
  /**
   * List time entries
   */
  async list(
    security: operations.ListTimeEntriesSecurity,
    request?: operations.ListTimeEntriesRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListTimeEntriesResponse, { page: number }>
  > {
    return unwrapResultIterator(timeEntriesList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a time entry
   */
  async create(
    security: operations.CreateTimeEntrySecurity,
    request: operations.CreateTimeEntryRequest,
    options?: RequestOptions,
  ): Promise<models.TimeEntry> {
    return unwrapAsync(timeEntriesCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a time entry
   */
  async get(
    security: operations.GetTimeEntrySecurity,
    request: operations.GetTimeEntryRequest,
    options?: RequestOptions,
  ): Promise<models.TimeEntry> {
    return unwrapAsync(timeEntriesGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a time entry
   *
   * @remarks
   * Time entries billed to a paid invoice cannot be deleted.
   */
  async delete(
    security: operations.DeleteTimeEntrySecurity,
    request: operations.DeleteTimeEntryRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(timeEntriesDelete(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a time entry
   *
   * @remarks
   * Time entries billed to a paid invoice cannot be edited (the date field is immutable in that case).
   */
  async update(
    security: operations.UpdateTimeEntrySecurity,
    request: operations.UpdateTimeEntryRequest,
    options?: RequestOptions,
  ): Promise<models.TimeEntry> {
    return unwrapAsync(timeEntriesUpdate(
      this,
      security,
      request,
      options,
    ));
  }
}
