/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { timeEntriesCreateTimeEntry } from "../funcs/time-entries-create-time-entry.js";
import { timeEntriesDeleteTimeEntry } from "../funcs/time-entries-delete-time-entry.js";
import { timeEntriesGetTimeEntry } from "../funcs/time-entries-get-time-entry.js";
import { timeEntriesListTimeEntries } from "../funcs/time-entries-list-time-entries.js";
import { timeEntriesUpdateTimeEntry } from "../funcs/time-entries-update-time-entry.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class TimeEntries extends ClientSDK {
  /**
   * List time entries
   */
  async listTimeEntries(
    security: operations.ListTimeEntriesSecurity,
    request?: operations.ListTimeEntriesRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListTimeEntriesResponse> {
    return unwrapAsync(timeEntriesListTimeEntries(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a time entry
   */
  async createTimeEntry(
    security: operations.CreateTimeEntrySecurity,
    request: models.TimeEntryCreate,
    options?: RequestOptions,
  ): Promise<models.TimeEntry> {
    return unwrapAsync(timeEntriesCreateTimeEntry(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a time entry
   */
  async getTimeEntry(
    security: operations.GetTimeEntrySecurity,
    request: operations.GetTimeEntryRequest,
    options?: RequestOptions,
  ): Promise<models.TimeEntry> {
    return unwrapAsync(timeEntriesGetTimeEntry(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a time entry
   *
   * @remarks
   * Time entries billed to a paid invoice cannot be deleted.
   */
  async deleteTimeEntry(
    security: operations.DeleteTimeEntrySecurity,
    request: operations.DeleteTimeEntryRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(timeEntriesDeleteTimeEntry(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a time entry
   *
   * @remarks
   * Time entries billed to a paid invoice cannot be edited (the date field is immutable in that case).
   */
  async updateTimeEntry(
    security: operations.UpdateTimeEntrySecurity,
    request: operations.UpdateTimeEntryRequest,
    options?: RequestOptions,
  ): Promise<models.TimeEntry> {
    return unwrapAsync(timeEntriesUpdateTimeEntry(
      this,
      security,
      request,
      options,
    ));
  }
}
