/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsCreateTransaction } from "../funcs/transactions-create-transaction.js";
import { transactionsDeleteTransaction } from "../funcs/transactions-delete-transaction.js";
import { transactionsGetTransaction } from "../funcs/transactions-get-transaction.js";
import { transactionsListTransactions } from "../funcs/transactions-list-transactions.js";
import { transactionsUpdateTransaction } from "../funcs/transactions-update-transaction.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Transactions extends ClientSDK {
  /**
   * List transactions
   */
  async listTransactions(
    security: operations.ListTransactionsSecurity,
    request?: operations.ListTransactionsRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListTransactionsResponse> {
    return unwrapAsync(transactionsListTransactions(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a transaction (expense or charge)
   */
  async createTransaction(
    security: operations.CreateTransactionSecurity,
    request: models.TransactionCreate,
    options?: RequestOptions,
  ): Promise<models.Transaction> {
    return unwrapAsync(transactionsCreateTransaction(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a transaction
   */
  async getTransaction(
    security: operations.GetTransactionSecurity,
    request: operations.GetTransactionRequest,
    options?: RequestOptions,
  ): Promise<models.Transaction> {
    return unwrapAsync(transactionsGetTransaction(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a transaction
   *
   * @remarks
   * Transactions billed to a sent/paid invoice may be frozen — the server will return 409 if so.
   */
  async updateTransaction(
    security: operations.UpdateTransactionSecurity,
    request: operations.UpdateTransactionRequest,
    options?: RequestOptions,
  ): Promise<models.Transaction> {
    return unwrapAsync(transactionsUpdateTransaction(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a transaction
   *
   * @remarks
   * Transactions billed to a sent/paid invoice cannot be deleted.
   */
  async deleteTransaction(
    security: operations.DeleteTransactionSecurity,
    request: operations.DeleteTransactionRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(transactionsDeleteTransaction(
      this,
      security,
      request,
      options,
    ));
  }
}
