/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { transactionsCreate } from "../funcs/transactions-create.js";
import { transactionsDelete } from "../funcs/transactions-delete.js";
import { transactionsGet } from "../funcs/transactions-get.js";
import { transactionsList } from "../funcs/transactions-list.js";
import { transactionsUpdate } from "../funcs/transactions-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";
import { PageIterator, unwrapResultIterator } from "../types/operations.js";

export class Transactions extends ClientSDK {
  /**
   * List transactions
   */
  async list(
    security: operations.ListTransactionsSecurity,
    request?: operations.ListTransactionsRequest | undefined,
    options?: RequestOptions,
  ): Promise<
    PageIterator<operations.ListTransactionsResponse, { page: number }>
  > {
    return unwrapResultIterator(transactionsList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Create a transaction (expense or charge)
   */
  async create(
    security: operations.CreateTransactionSecurity,
    request: operations.CreateTransactionRequest,
    options?: RequestOptions,
  ): Promise<models.Transaction> {
    return unwrapAsync(transactionsCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a transaction
   */
  async get(
    security: operations.GetTransactionSecurity,
    request: operations.GetTransactionRequest,
    options?: RequestOptions,
  ): Promise<models.Transaction> {
    return unwrapAsync(transactionsGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a transaction
   *
   * @remarks
   * Transactions billed to a sent/paid invoice cannot be deleted.
   */
  async delete(
    security: operations.DeleteTransactionSecurity,
    request: operations.DeleteTransactionRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(transactionsDelete(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a transaction
   *
   * @remarks
   * Transactions billed to a sent/paid invoice may be frozen — the server will return 409 if so.
   */
  async update(
    security: operations.UpdateTransactionSecurity,
    request: operations.UpdateTransactionRequest,
    options?: RequestOptions,
  ): Promise<models.Transaction> {
    return unwrapAsync(transactionsUpdate(
      this,
      security,
      request,
      options,
    ));
  }
}
