/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksCreate } from "../funcs/webhooks-create.js";
import { webhooksDelete } from "../funcs/webhooks-delete.js";
import { webhooksGet } from "../funcs/webhooks-get.js";
import { webhooksList } from "../funcs/webhooks-list.js";
import { webhooksUpdate } from "../funcs/webhooks-update.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as models from "../models/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * List webhook subscriptions
   */
  async list(
    security: operations.ListWebhooksSecurity,
    request?: operations.ListWebhooksRequest | undefined,
    options?: RequestOptions,
  ): Promise<operations.ListWebhooksResponse> {
    return unwrapAsync(webhooksList(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Subscribe to events
   *
   * @remarks
   * Creates a webhook endpoint. URL must be HTTPS. If `secret` is provided, every delivery includes an `X-Signature: sha256=…` header computed over `${X-Webhook-Timestamp}.${body}`.
   */
  async create(
    security: operations.CreateWebhookSecurity,
    request: models.WebhookCreate,
    options?: RequestOptions,
  ): Promise<models.Webhook> {
    return unwrapAsync(webhooksCreate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Get a webhook
   */
  async get(
    security: operations.GetWebhookSecurity,
    request: operations.GetWebhookRequest,
    options?: RequestOptions,
  ): Promise<models.Webhook> {
    return unwrapAsync(webhooksGet(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Update a webhook
   *
   * @remarks
   * Pass `secret: null` to remove the signing secret. Pass a new string to rotate.
   */
  async update(
    security: operations.UpdateWebhookSecurity,
    request: operations.UpdateWebhookRequest,
    options?: RequestOptions,
  ): Promise<models.Webhook> {
    return unwrapAsync(webhooksUpdate(
      this,
      security,
      request,
      options,
    ));
  }

  /**
   * Delete a webhook
   */
  async delete(
    security: operations.DeleteWebhookSecurity,
    request: operations.DeleteWebhookRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(webhooksDelete(
      this,
      security,
      request,
      options,
    ));
  }
}
