/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @clientcasa/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx clientsList.example.ts
 */

import { ClientCasa } from "@clientcasa/sdk";

const clientCasa = new ClientCasa();

async function main() {
  const result = await clientCasa.clients.list({
    apiKey: process.env["CLIENTCASA_API_KEY"] ?? "",
  }, {});

  for await (const page of result) {
    console.log(page);
  }
}

main().catch(console.error);
