workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    ClientCasa API:
        inputs:
            - location: ./openapi.json
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/delmare-digital/clientcasa/client-casa-api
targets:
    client-casa:
        target: typescript
        source: ClientCasa API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/delmare-digital/clientcasa/client-casa-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
