workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    ClientCasa API:
        inputs:
            - location: https://www.clientcasa.com/api/v1/openapi.json
        output: .speakeasy/out.openapi.yaml
        registry:
            location: registry.speakeasyapi.dev/delmare-digital/clientcasa/client-casa-api
targets:
    client-casa:
        target: typescript
        source: ClientCasa API
        publish:
            npm:
                token: $npm_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/delmare-digital/clientcasa/client-casa-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
