/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateTimeEntrySecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export type CreateTimeEntrySecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateTimeEntrySecurity$outboundSchema: z.ZodMiniType<
  CreateTimeEntrySecurity$Outbound,
  CreateTimeEntrySecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createTimeEntrySecurityToJSON(
  createTimeEntrySecurity: CreateTimeEntrySecurity,
): string {
  return JSON.stringify(
    CreateTimeEntrySecurity$outboundSchema.parse(createTimeEntrySecurity),
  );
}
