/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateTransactionSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export type CreateTransactionSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateTransactionSecurity$outboundSchema: z.ZodMiniType<
  CreateTransactionSecurity$Outbound,
  CreateTransactionSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createTransactionSecurityToJSON(
  createTransactionSecurity: CreateTransactionSecurity,
): string {
  return JSON.stringify(
    CreateTransactionSecurity$outboundSchema.parse(createTransactionSecurity),
  );
}
