/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateMilestoneSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export type CreateMilestoneSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateMilestoneSecurity$outboundSchema: z.ZodMiniType<
  CreateMilestoneSecurity$Outbound,
  CreateMilestoneSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createMilestoneSecurityToJSON(
  createMilestoneSecurity: CreateMilestoneSecurity,
): string {
  return JSON.stringify(
    CreateMilestoneSecurity$outboundSchema.parse(createMilestoneSecurity),
  );
}
