/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateVenueSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type CreateVenueRequest = {
  /**
   * Optional unique key that makes this create safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.VenueCreate;
};

/** @internal */
export type CreateVenueSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateVenueSecurity$outboundSchema: z.ZodMiniType<
  CreateVenueSecurity$Outbound,
  CreateVenueSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createVenueSecurityToJSON(
  createVenueSecurity: CreateVenueSecurity,
): string {
  return JSON.stringify(
    CreateVenueSecurity$outboundSchema.parse(createVenueSecurity),
  );
}

/** @internal */
export type CreateVenueRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: models.VenueCreate$Outbound;
};

/** @internal */
export const CreateVenueRequest$outboundSchema: z.ZodMiniType<
  CreateVenueRequest$Outbound,
  CreateVenueRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.VenueCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createVenueRequestToJSON(
  createVenueRequest: CreateVenueRequest,
): string {
  return JSON.stringify(
    CreateVenueRequest$outboundSchema.parse(createVenueRequest),
  );
}
