/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateProjectSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export type CreateProjectSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateProjectSecurity$outboundSchema: z.ZodMiniType<
  CreateProjectSecurity$Outbound,
  CreateProjectSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createProjectSecurityToJSON(
  createProjectSecurity: CreateProjectSecurity,
): string {
  return JSON.stringify(
    CreateProjectSecurity$outboundSchema.parse(createProjectSecurity),
  );
}
