/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateTransactionSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type CreateTransactionRequest = {
  /**
   * Optional unique key that makes this create safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.TransactionCreate;
};

/** @internal */
export type CreateTransactionSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateTransactionSecurity$outboundSchema: z.ZodMiniType<
  CreateTransactionSecurity$Outbound,
  CreateTransactionSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createTransactionSecurityToJSON(
  createTransactionSecurity: CreateTransactionSecurity,
): string {
  return JSON.stringify(
    CreateTransactionSecurity$outboundSchema.parse(createTransactionSecurity),
  );
}

/** @internal */
export type CreateTransactionRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: models.TransactionCreate$Outbound;
};

/** @internal */
export const CreateTransactionRequest$outboundSchema: z.ZodMiniType<
  CreateTransactionRequest$Outbound,
  CreateTransactionRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.TransactionCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createTransactionRequestToJSON(
  createTransactionRequest: CreateTransactionRequest,
): string {
  return JSON.stringify(
    CreateTransactionRequest$outboundSchema.parse(createTransactionRequest),
  );
}
