/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateContactSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export type CreateContactSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateContactSecurity$outboundSchema: z.ZodMiniType<
  CreateContactSecurity$Outbound,
  CreateContactSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createContactSecurityToJSON(
  createContactSecurity: CreateContactSecurity,
): string {
  return JSON.stringify(
    CreateContactSecurity$outboundSchema.parse(createContactSecurity),
  );
}
