/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateCatalogItemSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export type CreateCatalogItemSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateCatalogItemSecurity$outboundSchema: z.ZodMiniType<
  CreateCatalogItemSecurity$Outbound,
  CreateCatalogItemSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createCatalogItemSecurityToJSON(
  createCatalogItemSecurity: CreateCatalogItemSecurity,
): string {
  return JSON.stringify(
    CreateCatalogItemSecurity$outboundSchema.parse(createCatalogItemSecurity),
  );
}
