/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateClientSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export type CreateClientSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateClientSecurity$outboundSchema: z.ZodMiniType<
  CreateClientSecurity$Outbound,
  CreateClientSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createClientSecurityToJSON(
  createClientSecurity: CreateClientSecurity,
): string {
  return JSON.stringify(
    CreateClientSecurity$outboundSchema.parse(createClientSecurity),
  );
}
