/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateProposalSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export type CreateProposalSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateProposalSecurity$outboundSchema: z.ZodMiniType<
  CreateProposalSecurity$Outbound,
  CreateProposalSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createProposalSecurityToJSON(
  createProposalSecurity: CreateProposalSecurity,
): string {
  return JSON.stringify(
    CreateProposalSecurity$outboundSchema.parse(createProposalSecurity),
  );
}
