/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateVendorSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type CreateVendorRequest = {
  /**
   * Optional unique key that makes this create safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.VendorCreate;
};

/** @internal */
export type CreateVendorSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateVendorSecurity$outboundSchema: z.ZodMiniType<
  CreateVendorSecurity$Outbound,
  CreateVendorSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createVendorSecurityToJSON(
  createVendorSecurity: CreateVendorSecurity,
): string {
  return JSON.stringify(
    CreateVendorSecurity$outboundSchema.parse(createVendorSecurity),
  );
}

/** @internal */
export type CreateVendorRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: models.VendorCreate$Outbound;
};

/** @internal */
export const CreateVendorRequest$outboundSchema: z.ZodMiniType<
  CreateVendorRequest$Outbound,
  CreateVendorRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.VendorCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createVendorRequestToJSON(
  createVendorRequest: CreateVendorRequest,
): string {
  return JSON.stringify(
    CreateVendorRequest$outboundSchema.parse(createVendorRequest),
  );
}
