/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateTimelineItemSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type CreateTimelineItemRequest = {
  /**
   * Optional unique key that makes this create safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.TimelineItemCreate;
};

/** @internal */
export type CreateTimelineItemSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateTimelineItemSecurity$outboundSchema: z.ZodMiniType<
  CreateTimelineItemSecurity$Outbound,
  CreateTimelineItemSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createTimelineItemSecurityToJSON(
  createTimelineItemSecurity: CreateTimelineItemSecurity,
): string {
  return JSON.stringify(
    CreateTimelineItemSecurity$outboundSchema.parse(createTimelineItemSecurity),
  );
}

/** @internal */
export type CreateTimelineItemRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: models.TimelineItemCreate$Outbound;
};

/** @internal */
export const CreateTimelineItemRequest$outboundSchema: z.ZodMiniType<
  CreateTimelineItemRequest$Outbound,
  CreateTimelineItemRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.TimelineItemCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createTimelineItemRequestToJSON(
  createTimelineItemRequest: CreateTimelineItemRequest,
): string {
  return JSON.stringify(
    CreateTimelineItemRequest$outboundSchema.parse(createTimelineItemRequest),
  );
}
