/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateInquirySecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type CreateInquiryRequest = {
  /**
   * Optional unique key that makes this create safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.InquiryCreate;
};

/** @internal */
export type CreateInquirySecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateInquirySecurity$outboundSchema: z.ZodMiniType<
  CreateInquirySecurity$Outbound,
  CreateInquirySecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createInquirySecurityToJSON(
  createInquirySecurity: CreateInquirySecurity,
): string {
  return JSON.stringify(
    CreateInquirySecurity$outboundSchema.parse(createInquirySecurity),
  );
}

/** @internal */
export type CreateInquiryRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: models.InquiryCreate$Outbound;
};

/** @internal */
export const CreateInquiryRequest$outboundSchema: z.ZodMiniType<
  CreateInquiryRequest$Outbound,
  CreateInquiryRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.InquiryCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createInquiryRequestToJSON(
  createInquiryRequest: CreateInquiryRequest,
): string {
  return JSON.stringify(
    CreateInquiryRequest$outboundSchema.parse(createInquiryRequest),
  );
}
