/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CreateInvoiceSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export type CreateInvoiceSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateInvoiceSecurity$outboundSchema: z.ZodMiniType<
  CreateInvoiceSecurity$Outbound,
  CreateInvoiceSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createInvoiceSecurityToJSON(
  createInvoiceSecurity: CreateInvoiceSecurity,
): string {
  return JSON.stringify(
    CreateInvoiceSecurity$outboundSchema.parse(createInvoiceSecurity),
  );
}
