/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type CreateEventDaySecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type CreateEventDayRequest = {
  /**
   * Optional unique key that makes this create safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.EventDayCreate;
};

/** @internal */
export type CreateEventDaySecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const CreateEventDaySecurity$outboundSchema: z.ZodMiniType<
  CreateEventDaySecurity$Outbound,
  CreateEventDaySecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function createEventDaySecurityToJSON(
  createEventDaySecurity: CreateEventDaySecurity,
): string {
  return JSON.stringify(
    CreateEventDaySecurity$outboundSchema.parse(createEventDaySecurity),
  );
}

/** @internal */
export type CreateEventDayRequest$Outbound = {
  "Idempotency-Key"?: string | undefined;
  body: models.EventDayCreate$Outbound;
};

/** @internal */
export const CreateEventDayRequest$outboundSchema: z.ZodMiniType<
  CreateEventDayRequest$Outbound,
  CreateEventDayRequest
> = z.pipe(
  z.object({
    idempotencyKey: z.optional(z.string()),
    body: models.EventDayCreate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function createEventDayRequestToJSON(
  createEventDayRequest: CreateEventDayRequest,
): string {
  return JSON.stringify(
    CreateEventDayRequest$outboundSchema.parse(createEventDayRequest),
  );
}
