/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteWebhookSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteWebhookRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteWebhookSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteWebhookSecurity$outboundSchema: z.ZodMiniType<
  DeleteWebhookSecurity$Outbound,
  DeleteWebhookSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteWebhookSecurityToJSON(
  deleteWebhookSecurity: DeleteWebhookSecurity,
): string {
  return JSON.stringify(
    DeleteWebhookSecurity$outboundSchema.parse(deleteWebhookSecurity),
  );
}

/** @internal */
export type DeleteWebhookRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteWebhookRequest$outboundSchema: z.ZodMiniType<
  DeleteWebhookRequest$Outbound,
  DeleteWebhookRequest
> = z.object({
  id: z.string(),
});

export function deleteWebhookRequestToJSON(
  deleteWebhookRequest: DeleteWebhookRequest,
): string {
  return JSON.stringify(
    DeleteWebhookRequest$outboundSchema.parse(deleteWebhookRequest),
  );
}
