/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteInvoiceSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteInvoiceRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteInvoiceSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteInvoiceSecurity$outboundSchema: z.ZodMiniType<
  DeleteInvoiceSecurity$Outbound,
  DeleteInvoiceSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteInvoiceSecurityToJSON(
  deleteInvoiceSecurity: DeleteInvoiceSecurity,
): string {
  return JSON.stringify(
    DeleteInvoiceSecurity$outboundSchema.parse(deleteInvoiceSecurity),
  );
}

/** @internal */
export type DeleteInvoiceRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteInvoiceRequest$outboundSchema: z.ZodMiniType<
  DeleteInvoiceRequest$Outbound,
  DeleteInvoiceRequest
> = z.object({
  id: z.string(),
});

export function deleteInvoiceRequestToJSON(
  deleteInvoiceRequest: DeleteInvoiceRequest,
): string {
  return JSON.stringify(
    DeleteInvoiceRequest$outboundSchema.parse(deleteInvoiceRequest),
  );
}
