/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteVendorSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteVendorRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteVendorSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteVendorSecurity$outboundSchema: z.ZodMiniType<
  DeleteVendorSecurity$Outbound,
  DeleteVendorSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteVendorSecurityToJSON(
  deleteVendorSecurity: DeleteVendorSecurity,
): string {
  return JSON.stringify(
    DeleteVendorSecurity$outboundSchema.parse(deleteVendorSecurity),
  );
}

/** @internal */
export type DeleteVendorRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteVendorRequest$outboundSchema: z.ZodMiniType<
  DeleteVendorRequest$Outbound,
  DeleteVendorRequest
> = z.object({
  id: z.string(),
});

export function deleteVendorRequestToJSON(
  deleteVendorRequest: DeleteVendorRequest,
): string {
  return JSON.stringify(
    DeleteVendorRequest$outboundSchema.parse(deleteVendorRequest),
  );
}
