/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteClientSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteClientRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteClientSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteClientSecurity$outboundSchema: z.ZodMiniType<
  DeleteClientSecurity$Outbound,
  DeleteClientSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteClientSecurityToJSON(
  deleteClientSecurity: DeleteClientSecurity,
): string {
  return JSON.stringify(
    DeleteClientSecurity$outboundSchema.parse(deleteClientSecurity),
  );
}

/** @internal */
export type DeleteClientRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteClientRequest$outboundSchema: z.ZodMiniType<
  DeleteClientRequest$Outbound,
  DeleteClientRequest
> = z.object({
  id: z.string(),
});

export function deleteClientRequestToJSON(
  deleteClientRequest: DeleteClientRequest,
): string {
  return JSON.stringify(
    DeleteClientRequest$outboundSchema.parse(deleteClientRequest),
  );
}
