/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteTransactionSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteTransactionRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteTransactionSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteTransactionSecurity$outboundSchema: z.ZodMiniType<
  DeleteTransactionSecurity$Outbound,
  DeleteTransactionSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteTransactionSecurityToJSON(
  deleteTransactionSecurity: DeleteTransactionSecurity,
): string {
  return JSON.stringify(
    DeleteTransactionSecurity$outboundSchema.parse(deleteTransactionSecurity),
  );
}

/** @internal */
export type DeleteTransactionRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteTransactionRequest$outboundSchema: z.ZodMiniType<
  DeleteTransactionRequest$Outbound,
  DeleteTransactionRequest
> = z.object({
  id: z.string(),
});

export function deleteTransactionRequestToJSON(
  deleteTransactionRequest: DeleteTransactionRequest,
): string {
  return JSON.stringify(
    DeleteTransactionRequest$outboundSchema.parse(deleteTransactionRequest),
  );
}
