/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteEventDayVendorSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteEventDayVendorRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteEventDayVendorSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteEventDayVendorSecurity$outboundSchema: z.ZodMiniType<
  DeleteEventDayVendorSecurity$Outbound,
  DeleteEventDayVendorSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteEventDayVendorSecurityToJSON(
  deleteEventDayVendorSecurity: DeleteEventDayVendorSecurity,
): string {
  return JSON.stringify(
    DeleteEventDayVendorSecurity$outboundSchema.parse(
      deleteEventDayVendorSecurity,
    ),
  );
}

/** @internal */
export type DeleteEventDayVendorRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteEventDayVendorRequest$outboundSchema: z.ZodMiniType<
  DeleteEventDayVendorRequest$Outbound,
  DeleteEventDayVendorRequest
> = z.object({
  id: z.string(),
});

export function deleteEventDayVendorRequestToJSON(
  deleteEventDayVendorRequest: DeleteEventDayVendorRequest,
): string {
  return JSON.stringify(
    DeleteEventDayVendorRequest$outboundSchema.parse(
      deleteEventDayVendorRequest,
    ),
  );
}
