/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteMilestoneSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteMilestoneRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteMilestoneSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteMilestoneSecurity$outboundSchema: z.ZodMiniType<
  DeleteMilestoneSecurity$Outbound,
  DeleteMilestoneSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteMilestoneSecurityToJSON(
  deleteMilestoneSecurity: DeleteMilestoneSecurity,
): string {
  return JSON.stringify(
    DeleteMilestoneSecurity$outboundSchema.parse(deleteMilestoneSecurity),
  );
}

/** @internal */
export type DeleteMilestoneRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteMilestoneRequest$outboundSchema: z.ZodMiniType<
  DeleteMilestoneRequest$Outbound,
  DeleteMilestoneRequest
> = z.object({
  id: z.string(),
});

export function deleteMilestoneRequestToJSON(
  deleteMilestoneRequest: DeleteMilestoneRequest,
): string {
  return JSON.stringify(
    DeleteMilestoneRequest$outboundSchema.parse(deleteMilestoneRequest),
  );
}
