/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteCatalogItemSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteCatalogItemRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteCatalogItemSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteCatalogItemSecurity$outboundSchema: z.ZodMiniType<
  DeleteCatalogItemSecurity$Outbound,
  DeleteCatalogItemSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteCatalogItemSecurityToJSON(
  deleteCatalogItemSecurity: DeleteCatalogItemSecurity,
): string {
  return JSON.stringify(
    DeleteCatalogItemSecurity$outboundSchema.parse(deleteCatalogItemSecurity),
  );
}

/** @internal */
export type DeleteCatalogItemRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteCatalogItemRequest$outboundSchema: z.ZodMiniType<
  DeleteCatalogItemRequest$Outbound,
  DeleteCatalogItemRequest
> = z.object({
  id: z.string(),
});

export function deleteCatalogItemRequestToJSON(
  deleteCatalogItemRequest: DeleteCatalogItemRequest,
): string {
  return JSON.stringify(
    DeleteCatalogItemRequest$outboundSchema.parse(deleteCatalogItemRequest),
  );
}
