/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteProposalSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteProposalRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteProposalSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteProposalSecurity$outboundSchema: z.ZodMiniType<
  DeleteProposalSecurity$Outbound,
  DeleteProposalSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteProposalSecurityToJSON(
  deleteProposalSecurity: DeleteProposalSecurity,
): string {
  return JSON.stringify(
    DeleteProposalSecurity$outboundSchema.parse(deleteProposalSecurity),
  );
}

/** @internal */
export type DeleteProposalRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteProposalRequest$outboundSchema: z.ZodMiniType<
  DeleteProposalRequest$Outbound,
  DeleteProposalRequest
> = z.object({
  id: z.string(),
});

export function deleteProposalRequestToJSON(
  deleteProposalRequest: DeleteProposalRequest,
): string {
  return JSON.stringify(
    DeleteProposalRequest$outboundSchema.parse(deleteProposalRequest),
  );
}
