/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteTimelineItemSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteTimelineItemRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteTimelineItemSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteTimelineItemSecurity$outboundSchema: z.ZodMiniType<
  DeleteTimelineItemSecurity$Outbound,
  DeleteTimelineItemSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteTimelineItemSecurityToJSON(
  deleteTimelineItemSecurity: DeleteTimelineItemSecurity,
): string {
  return JSON.stringify(
    DeleteTimelineItemSecurity$outboundSchema.parse(deleteTimelineItemSecurity),
  );
}

/** @internal */
export type DeleteTimelineItemRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteTimelineItemRequest$outboundSchema: z.ZodMiniType<
  DeleteTimelineItemRequest$Outbound,
  DeleteTimelineItemRequest
> = z.object({
  id: z.string(),
});

export function deleteTimelineItemRequestToJSON(
  deleteTimelineItemRequest: DeleteTimelineItemRequest,
): string {
  return JSON.stringify(
    DeleteTimelineItemRequest$outboundSchema.parse(deleteTimelineItemRequest),
  );
}
