/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteInquirySecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteInquiryRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteInquirySecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteInquirySecurity$outboundSchema: z.ZodMiniType<
  DeleteInquirySecurity$Outbound,
  DeleteInquirySecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteInquirySecurityToJSON(
  deleteInquirySecurity: DeleteInquirySecurity,
): string {
  return JSON.stringify(
    DeleteInquirySecurity$outboundSchema.parse(deleteInquirySecurity),
  );
}

/** @internal */
export type DeleteInquiryRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteInquiryRequest$outboundSchema: z.ZodMiniType<
  DeleteInquiryRequest$Outbound,
  DeleteInquiryRequest
> = z.object({
  id: z.string(),
});

export function deleteInquiryRequestToJSON(
  deleteInquiryRequest: DeleteInquiryRequest,
): string {
  return JSON.stringify(
    DeleteInquiryRequest$outboundSchema.parse(deleteInquiryRequest),
  );
}
