/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteContactSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteContactRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteContactSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteContactSecurity$outboundSchema: z.ZodMiniType<
  DeleteContactSecurity$Outbound,
  DeleteContactSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteContactSecurityToJSON(
  deleteContactSecurity: DeleteContactSecurity,
): string {
  return JSON.stringify(
    DeleteContactSecurity$outboundSchema.parse(deleteContactSecurity),
  );
}

/** @internal */
export type DeleteContactRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteContactRequest$outboundSchema: z.ZodMiniType<
  DeleteContactRequest$Outbound,
  DeleteContactRequest
> = z.object({
  id: z.string(),
});

export function deleteContactRequestToJSON(
  deleteContactRequest: DeleteContactRequest,
): string {
  return JSON.stringify(
    DeleteContactRequest$outboundSchema.parse(deleteContactRequest),
  );
}
