/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteTimeEntrySecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteTimeEntryRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteTimeEntrySecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteTimeEntrySecurity$outboundSchema: z.ZodMiniType<
  DeleteTimeEntrySecurity$Outbound,
  DeleteTimeEntrySecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteTimeEntrySecurityToJSON(
  deleteTimeEntrySecurity: DeleteTimeEntrySecurity,
): string {
  return JSON.stringify(
    DeleteTimeEntrySecurity$outboundSchema.parse(deleteTimeEntrySecurity),
  );
}

/** @internal */
export type DeleteTimeEntryRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteTimeEntryRequest$outboundSchema: z.ZodMiniType<
  DeleteTimeEntryRequest$Outbound,
  DeleteTimeEntryRequest
> = z.object({
  id: z.string(),
});

export function deleteTimeEntryRequestToJSON(
  deleteTimeEntryRequest: DeleteTimeEntryRequest,
): string {
  return JSON.stringify(
    DeleteTimeEntryRequest$outboundSchema.parse(deleteTimeEntryRequest),
  );
}
