/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteContractSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteContractRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteContractSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteContractSecurity$outboundSchema: z.ZodMiniType<
  DeleteContractSecurity$Outbound,
  DeleteContractSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteContractSecurityToJSON(
  deleteContractSecurity: DeleteContractSecurity,
): string {
  return JSON.stringify(
    DeleteContractSecurity$outboundSchema.parse(deleteContractSecurity),
  );
}

/** @internal */
export type DeleteContractRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteContractRequest$outboundSchema: z.ZodMiniType<
  DeleteContractRequest$Outbound,
  DeleteContractRequest
> = z.object({
  id: z.string(),
});

export function deleteContractRequestToJSON(
  deleteContractRequest: DeleteContractRequest,
): string {
  return JSON.stringify(
    DeleteContractRequest$outboundSchema.parse(deleteContractRequest),
  );
}
