/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteEventDaySecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type DeleteEventDayRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type DeleteEventDaySecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const DeleteEventDaySecurity$outboundSchema: z.ZodMiniType<
  DeleteEventDaySecurity$Outbound,
  DeleteEventDaySecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function deleteEventDaySecurityToJSON(
  deleteEventDaySecurity: DeleteEventDaySecurity,
): string {
  return JSON.stringify(
    DeleteEventDaySecurity$outboundSchema.parse(deleteEventDaySecurity),
  );
}

/** @internal */
export type DeleteEventDayRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteEventDayRequest$outboundSchema: z.ZodMiniType<
  DeleteEventDayRequest$Outbound,
  DeleteEventDayRequest
> = z.object({
  id: z.string(),
});

export function deleteEventDayRequestToJSON(
  deleteEventDayRequest: DeleteEventDayRequest,
): string {
  return JSON.stringify(
    DeleteEventDayRequest$outboundSchema.parse(deleteEventDayRequest),
  );
}
