/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetInquirySecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetInquiryRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetInquirySecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetInquirySecurity$outboundSchema: z.ZodMiniType<
  GetInquirySecurity$Outbound,
  GetInquirySecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getInquirySecurityToJSON(
  getInquirySecurity: GetInquirySecurity,
): string {
  return JSON.stringify(
    GetInquirySecurity$outboundSchema.parse(getInquirySecurity),
  );
}

/** @internal */
export type GetInquiryRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetInquiryRequest$outboundSchema: z.ZodMiniType<
  GetInquiryRequest$Outbound,
  GetInquiryRequest
> = z.object({
  id: z.string(),
});

export function getInquiryRequestToJSON(
  getInquiryRequest: GetInquiryRequest,
): string {
  return JSON.stringify(
    GetInquiryRequest$outboundSchema.parse(getInquiryRequest),
  );
}
