/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetCatalogItemSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetCatalogItemRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetCatalogItemSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetCatalogItemSecurity$outboundSchema: z.ZodMiniType<
  GetCatalogItemSecurity$Outbound,
  GetCatalogItemSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getCatalogItemSecurityToJSON(
  getCatalogItemSecurity: GetCatalogItemSecurity,
): string {
  return JSON.stringify(
    GetCatalogItemSecurity$outboundSchema.parse(getCatalogItemSecurity),
  );
}

/** @internal */
export type GetCatalogItemRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCatalogItemRequest$outboundSchema: z.ZodMiniType<
  GetCatalogItemRequest$Outbound,
  GetCatalogItemRequest
> = z.object({
  id: z.string(),
});

export function getCatalogItemRequestToJSON(
  getCatalogItemRequest: GetCatalogItemRequest,
): string {
  return JSON.stringify(
    GetCatalogItemRequest$outboundSchema.parse(getCatalogItemRequest),
  );
}
