/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetFormSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetFormRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetFormSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetFormSecurity$outboundSchema: z.ZodMiniType<
  GetFormSecurity$Outbound,
  GetFormSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getFormSecurityToJSON(
  getFormSecurity: GetFormSecurity,
): string {
  return JSON.stringify(GetFormSecurity$outboundSchema.parse(getFormSecurity));
}

/** @internal */
export type GetFormRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetFormRequest$outboundSchema: z.ZodMiniType<
  GetFormRequest$Outbound,
  GetFormRequest
> = z.object({
  id: z.string(),
});

export function getFormRequestToJSON(getFormRequest: GetFormRequest): string {
  return JSON.stringify(GetFormRequest$outboundSchema.parse(getFormRequest));
}
