/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetInvoiceSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetInvoiceRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetInvoiceSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetInvoiceSecurity$outboundSchema: z.ZodMiniType<
  GetInvoiceSecurity$Outbound,
  GetInvoiceSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getInvoiceSecurityToJSON(
  getInvoiceSecurity: GetInvoiceSecurity,
): string {
  return JSON.stringify(
    GetInvoiceSecurity$outboundSchema.parse(getInvoiceSecurity),
  );
}

/** @internal */
export type GetInvoiceRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetInvoiceRequest$outboundSchema: z.ZodMiniType<
  GetInvoiceRequest$Outbound,
  GetInvoiceRequest
> = z.object({
  id: z.string(),
});

export function getInvoiceRequestToJSON(
  getInvoiceRequest: GetInvoiceRequest,
): string {
  return JSON.stringify(
    GetInvoiceRequest$outboundSchema.parse(getInvoiceRequest),
  );
}
