/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetClientSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetClientRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetClientSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetClientSecurity$outboundSchema: z.ZodMiniType<
  GetClientSecurity$Outbound,
  GetClientSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getClientSecurityToJSON(
  getClientSecurity: GetClientSecurity,
): string {
  return JSON.stringify(
    GetClientSecurity$outboundSchema.parse(getClientSecurity),
  );
}

/** @internal */
export type GetClientRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetClientRequest$outboundSchema: z.ZodMiniType<
  GetClientRequest$Outbound,
  GetClientRequest
> = z.object({
  id: z.string(),
});

export function getClientRequestToJSON(
  getClientRequest: GetClientRequest,
): string {
  return JSON.stringify(
    GetClientRequest$outboundSchema.parse(getClientRequest),
  );
}
