/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetProjectSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetProjectRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetProjectSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetProjectSecurity$outboundSchema: z.ZodMiniType<
  GetProjectSecurity$Outbound,
  GetProjectSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getProjectSecurityToJSON(
  getProjectSecurity: GetProjectSecurity,
): string {
  return JSON.stringify(
    GetProjectSecurity$outboundSchema.parse(getProjectSecurity),
  );
}

/** @internal */
export type GetProjectRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetProjectRequest$outboundSchema: z.ZodMiniType<
  GetProjectRequest$Outbound,
  GetProjectRequest
> = z.object({
  id: z.string(),
});

export function getProjectRequestToJSON(
  getProjectRequest: GetProjectRequest,
): string {
  return JSON.stringify(
    GetProjectRequest$outboundSchema.parse(getProjectRequest),
  );
}
