/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetTimelineItemSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetTimelineItemRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetTimelineItemSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetTimelineItemSecurity$outboundSchema: z.ZodMiniType<
  GetTimelineItemSecurity$Outbound,
  GetTimelineItemSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getTimelineItemSecurityToJSON(
  getTimelineItemSecurity: GetTimelineItemSecurity,
): string {
  return JSON.stringify(
    GetTimelineItemSecurity$outboundSchema.parse(getTimelineItemSecurity),
  );
}

/** @internal */
export type GetTimelineItemRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetTimelineItemRequest$outboundSchema: z.ZodMiniType<
  GetTimelineItemRequest$Outbound,
  GetTimelineItemRequest
> = z.object({
  id: z.string(),
});

export function getTimelineItemRequestToJSON(
  getTimelineItemRequest: GetTimelineItemRequest,
): string {
  return JSON.stringify(
    GetTimelineItemRequest$outboundSchema.parse(getTimelineItemRequest),
  );
}
