/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetEventDayVendorSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetEventDayVendorRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetEventDayVendorSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetEventDayVendorSecurity$outboundSchema: z.ZodMiniType<
  GetEventDayVendorSecurity$Outbound,
  GetEventDayVendorSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getEventDayVendorSecurityToJSON(
  getEventDayVendorSecurity: GetEventDayVendorSecurity,
): string {
  return JSON.stringify(
    GetEventDayVendorSecurity$outboundSchema.parse(getEventDayVendorSecurity),
  );
}

/** @internal */
export type GetEventDayVendorRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetEventDayVendorRequest$outboundSchema: z.ZodMiniType<
  GetEventDayVendorRequest$Outbound,
  GetEventDayVendorRequest
> = z.object({
  id: z.string(),
});

export function getEventDayVendorRequestToJSON(
  getEventDayVendorRequest: GetEventDayVendorRequest,
): string {
  return JSON.stringify(
    GetEventDayVendorRequest$outboundSchema.parse(getEventDayVendorRequest),
  );
}
