/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetEventDaySecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetEventDayRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetEventDaySecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetEventDaySecurity$outboundSchema: z.ZodMiniType<
  GetEventDaySecurity$Outbound,
  GetEventDaySecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getEventDaySecurityToJSON(
  getEventDaySecurity: GetEventDaySecurity,
): string {
  return JSON.stringify(
    GetEventDaySecurity$outboundSchema.parse(getEventDaySecurity),
  );
}

/** @internal */
export type GetEventDayRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetEventDayRequest$outboundSchema: z.ZodMiniType<
  GetEventDayRequest$Outbound,
  GetEventDayRequest
> = z.object({
  id: z.string(),
});

export function getEventDayRequestToJSON(
  getEventDayRequest: GetEventDayRequest,
): string {
  return JSON.stringify(
    GetEventDayRequest$outboundSchema.parse(getEventDayRequest),
  );
}
