/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetWebhookSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetWebhookRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetWebhookSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetWebhookSecurity$outboundSchema: z.ZodMiniType<
  GetWebhookSecurity$Outbound,
  GetWebhookSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getWebhookSecurityToJSON(
  getWebhookSecurity: GetWebhookSecurity,
): string {
  return JSON.stringify(
    GetWebhookSecurity$outboundSchema.parse(getWebhookSecurity),
  );
}

/** @internal */
export type GetWebhookRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetWebhookRequest$outboundSchema: z.ZodMiniType<
  GetWebhookRequest$Outbound,
  GetWebhookRequest
> = z.object({
  id: z.string(),
});

export function getWebhookRequestToJSON(
  getWebhookRequest: GetWebhookRequest,
): string {
  return JSON.stringify(
    GetWebhookRequest$outboundSchema.parse(getWebhookRequest),
  );
}
