/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetFormAttachmentSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetFormAttachmentRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetFormAttachmentSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetFormAttachmentSecurity$outboundSchema: z.ZodMiniType<
  GetFormAttachmentSecurity$Outbound,
  GetFormAttachmentSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getFormAttachmentSecurityToJSON(
  getFormAttachmentSecurity: GetFormAttachmentSecurity,
): string {
  return JSON.stringify(
    GetFormAttachmentSecurity$outboundSchema.parse(getFormAttachmentSecurity),
  );
}

/** @internal */
export type GetFormAttachmentRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetFormAttachmentRequest$outboundSchema: z.ZodMiniType<
  GetFormAttachmentRequest$Outbound,
  GetFormAttachmentRequest
> = z.object({
  id: z.string(),
});

export function getFormAttachmentRequestToJSON(
  getFormAttachmentRequest: GetFormAttachmentRequest,
): string {
  return JSON.stringify(
    GetFormAttachmentRequest$outboundSchema.parse(getFormAttachmentRequest),
  );
}
