/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetContractSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetContractRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetContractSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetContractSecurity$outboundSchema: z.ZodMiniType<
  GetContractSecurity$Outbound,
  GetContractSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getContractSecurityToJSON(
  getContractSecurity: GetContractSecurity,
): string {
  return JSON.stringify(
    GetContractSecurity$outboundSchema.parse(getContractSecurity),
  );
}

/** @internal */
export type GetContractRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetContractRequest$outboundSchema: z.ZodMiniType<
  GetContractRequest$Outbound,
  GetContractRequest
> = z.object({
  id: z.string(),
});

export function getContractRequestToJSON(
  getContractRequest: GetContractRequest,
): string {
  return JSON.stringify(
    GetContractRequest$outboundSchema.parse(getContractRequest),
  );
}
