/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetCalendarEventSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetCalendarEventRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetCalendarEventSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetCalendarEventSecurity$outboundSchema: z.ZodMiniType<
  GetCalendarEventSecurity$Outbound,
  GetCalendarEventSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getCalendarEventSecurityToJSON(
  getCalendarEventSecurity: GetCalendarEventSecurity,
): string {
  return JSON.stringify(
    GetCalendarEventSecurity$outboundSchema.parse(getCalendarEventSecurity),
  );
}

/** @internal */
export type GetCalendarEventRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetCalendarEventRequest$outboundSchema: z.ZodMiniType<
  GetCalendarEventRequest$Outbound,
  GetCalendarEventRequest
> = z.object({
  id: z.string(),
});

export function getCalendarEventRequestToJSON(
  getCalendarEventRequest: GetCalendarEventRequest,
): string {
  return JSON.stringify(
    GetCalendarEventRequest$outboundSchema.parse(getCalendarEventRequest),
  );
}
