/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetClientDocumentSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetClientDocumentRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetClientDocumentSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetClientDocumentSecurity$outboundSchema: z.ZodMiniType<
  GetClientDocumentSecurity$Outbound,
  GetClientDocumentSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getClientDocumentSecurityToJSON(
  getClientDocumentSecurity: GetClientDocumentSecurity,
): string {
  return JSON.stringify(
    GetClientDocumentSecurity$outboundSchema.parse(getClientDocumentSecurity),
  );
}

/** @internal */
export type GetClientDocumentRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetClientDocumentRequest$outboundSchema: z.ZodMiniType<
  GetClientDocumentRequest$Outbound,
  GetClientDocumentRequest
> = z.object({
  id: z.string(),
});

export function getClientDocumentRequestToJSON(
  getClientDocumentRequest: GetClientDocumentRequest,
): string {
  return JSON.stringify(
    GetClientDocumentRequest$outboundSchema.parse(getClientDocumentRequest),
  );
}
