/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetContactSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetContactRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetContactSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetContactSecurity$outboundSchema: z.ZodMiniType<
  GetContactSecurity$Outbound,
  GetContactSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getContactSecurityToJSON(
  getContactSecurity: GetContactSecurity,
): string {
  return JSON.stringify(
    GetContactSecurity$outboundSchema.parse(getContactSecurity),
  );
}

/** @internal */
export type GetContactRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetContactRequest$outboundSchema: z.ZodMiniType<
  GetContactRequest$Outbound,
  GetContactRequest
> = z.object({
  id: z.string(),
});

export function getContactRequestToJSON(
  getContactRequest: GetContactRequest,
): string {
  return JSON.stringify(
    GetContactRequest$outboundSchema.parse(getContactRequest),
  );
}
