/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetVendorSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetVendorRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetVendorSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetVendorSecurity$outboundSchema: z.ZodMiniType<
  GetVendorSecurity$Outbound,
  GetVendorSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getVendorSecurityToJSON(
  getVendorSecurity: GetVendorSecurity,
): string {
  return JSON.stringify(
    GetVendorSecurity$outboundSchema.parse(getVendorSecurity),
  );
}

/** @internal */
export type GetVendorRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetVendorRequest$outboundSchema: z.ZodMiniType<
  GetVendorRequest$Outbound,
  GetVendorRequest
> = z.object({
  id: z.string(),
});

export function getVendorRequestToJSON(
  getVendorRequest: GetVendorRequest,
): string {
  return JSON.stringify(
    GetVendorRequest$outboundSchema.parse(getVendorRequest),
  );
}
