/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetDocumentVersionSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetDocumentVersionRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetDocumentVersionSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetDocumentVersionSecurity$outboundSchema: z.ZodMiniType<
  GetDocumentVersionSecurity$Outbound,
  GetDocumentVersionSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getDocumentVersionSecurityToJSON(
  getDocumentVersionSecurity: GetDocumentVersionSecurity,
): string {
  return JSON.stringify(
    GetDocumentVersionSecurity$outboundSchema.parse(getDocumentVersionSecurity),
  );
}

/** @internal */
export type GetDocumentVersionRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetDocumentVersionRequest$outboundSchema: z.ZodMiniType<
  GetDocumentVersionRequest$Outbound,
  GetDocumentVersionRequest
> = z.object({
  id: z.string(),
});

export function getDocumentVersionRequestToJSON(
  getDocumentVersionRequest: GetDocumentVersionRequest,
): string {
  return JSON.stringify(
    GetDocumentVersionRequest$outboundSchema.parse(getDocumentVersionRequest),
  );
}
