/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetSaleSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type GetSaleRequest = {
  /**
   * UUID v4
   */
  id: string;
};

/** @internal */
export type GetSaleSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const GetSaleSecurity$outboundSchema: z.ZodMiniType<
  GetSaleSecurity$Outbound,
  GetSaleSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function getSaleSecurityToJSON(
  getSaleSecurity: GetSaleSecurity,
): string {
  return JSON.stringify(GetSaleSecurity$outboundSchema.parse(getSaleSecurity));
}

/** @internal */
export type GetSaleRequest$Outbound = {
  id: string;
};

/** @internal */
export const GetSaleRequest$outboundSchema: z.ZodMiniType<
  GetSaleRequest$Outbound,
  GetSaleRequest
> = z.object({
  id: z.string(),
});

export function getSaleRequestToJSON(getSaleRequest: GetSaleRequest): string {
  return JSON.stringify(GetSaleRequest$outboundSchema.parse(getSaleRequest));
}
