/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListSalesSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const ListSalesStatus = {
  Completed: "completed",
  Refunded: "refunded",
  PartiallyRefunded: "partially-refunded",
  Voided: "voided",
} as const;
export type ListSalesStatus = ClosedEnum<typeof ListSalesStatus>;

export const Channel = {
  Pos: "pos",
  Manual: "manual",
  Stripe: "stripe",
  Shopify: "shopify",
  Etsy: "etsy",
  SquareImport: "square-import",
  Api: "api",
} as const;
export type Channel = ClosedEnum<typeof Channel>;

export type ListSalesRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  status?: ListSalesStatus | undefined;
  channel?: Channel | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
  /**
   * UUID v4
   */
  businessId?: string | undefined;
  saleDateFrom?: Date | undefined;
  saleDateTo?: Date | undefined;
};

export type ListSalesResponse = {
  result: models.SaleList;
};

/** @internal */
export type ListSalesSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListSalesSecurity$outboundSchema: z.ZodMiniType<
  ListSalesSecurity$Outbound,
  ListSalesSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listSalesSecurityToJSON(
  listSalesSecurity: ListSalesSecurity,
): string {
  return JSON.stringify(
    ListSalesSecurity$outboundSchema.parse(listSalesSecurity),
  );
}

/** @internal */
export const ListSalesStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListSalesStatus
> = z.enum(ListSalesStatus);

/** @internal */
export const Channel$outboundSchema: z.ZodMiniEnum<typeof Channel> = z.enum(
  Channel,
);

/** @internal */
export type ListSalesRequest$Outbound = {
  page: number;
  pageSize: number;
  status?: string | undefined;
  channel?: string | undefined;
  clientId?: string | undefined;
  businessId?: string | undefined;
  saleDateFrom?: string | undefined;
  saleDateTo?: string | undefined;
};

/** @internal */
export const ListSalesRequest$outboundSchema: z.ZodMiniType<
  ListSalesRequest$Outbound,
  ListSalesRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  status: z.optional(ListSalesStatus$outboundSchema),
  channel: z.optional(Channel$outboundSchema),
  clientId: z.optional(z.string()),
  businessId: z.optional(z.string()),
  saleDateFrom: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  saleDateTo: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
});

export function listSalesRequestToJSON(
  listSalesRequest: ListSalesRequest,
): string {
  return JSON.stringify(
    ListSalesRequest$outboundSchema.parse(listSalesRequest),
  );
}

/** @internal */
export const ListSalesResponse$inboundSchema: z.ZodMiniType<
  ListSalesResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.SaleList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listSalesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListSalesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListSalesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListSalesResponse' from JSON`,
  );
}
