/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListEventDayVendorsSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type ListEventDayVendorsRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  eventDayId?: string | undefined;
  vendorId?: string | undefined;
};

export type ListEventDayVendorsResponse = {
  result: models.EventDayVendorList;
};

/** @internal */
export type ListEventDayVendorsSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListEventDayVendorsSecurity$outboundSchema: z.ZodMiniType<
  ListEventDayVendorsSecurity$Outbound,
  ListEventDayVendorsSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listEventDayVendorsSecurityToJSON(
  listEventDayVendorsSecurity: ListEventDayVendorsSecurity,
): string {
  return JSON.stringify(
    ListEventDayVendorsSecurity$outboundSchema.parse(
      listEventDayVendorsSecurity,
    ),
  );
}

/** @internal */
export type ListEventDayVendorsRequest$Outbound = {
  page: number;
  pageSize: number;
  eventDayId?: string | undefined;
  vendorId?: string | undefined;
};

/** @internal */
export const ListEventDayVendorsRequest$outboundSchema: z.ZodMiniType<
  ListEventDayVendorsRequest$Outbound,
  ListEventDayVendorsRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  eventDayId: z.optional(z.string()),
  vendorId: z.optional(z.string()),
});

export function listEventDayVendorsRequestToJSON(
  listEventDayVendorsRequest: ListEventDayVendorsRequest,
): string {
  return JSON.stringify(
    ListEventDayVendorsRequest$outboundSchema.parse(listEventDayVendorsRequest),
  );
}

/** @internal */
export const ListEventDayVendorsResponse$inboundSchema: z.ZodMiniType<
  ListEventDayVendorsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.EventDayVendorList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listEventDayVendorsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListEventDayVendorsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListEventDayVendorsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListEventDayVendorsResponse' from JSON`,
  );
}
