/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListPayoutsSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const ListPayoutsStatus = {
  Pending: "pending",
  InTransit: "in_transit",
  Paid: "paid",
  Failed: "failed",
  Canceled: "canceled",
} as const;
export type ListPayoutsStatus = ClosedEnum<typeof ListPayoutsStatus>;

export type ListPayoutsRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  status?: ListPayoutsStatus | undefined;
  arrivalDateFrom?: Date | undefined;
  arrivalDateTo?: Date | undefined;
};

/**
 * OK
 */
export type ListPayoutsResponse = {
  data: Array<models.Payout>;
  pagination: models.PaginationMeta;
};

/** @internal */
export type ListPayoutsSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListPayoutsSecurity$outboundSchema: z.ZodMiniType<
  ListPayoutsSecurity$Outbound,
  ListPayoutsSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listPayoutsSecurityToJSON(
  listPayoutsSecurity: ListPayoutsSecurity,
): string {
  return JSON.stringify(
    ListPayoutsSecurity$outboundSchema.parse(listPayoutsSecurity),
  );
}

/** @internal */
export const ListPayoutsStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListPayoutsStatus
> = z.enum(ListPayoutsStatus);

/** @internal */
export type ListPayoutsRequest$Outbound = {
  page: number;
  pageSize: number;
  status?: string | undefined;
  arrivalDateFrom?: string | undefined;
  arrivalDateTo?: string | undefined;
};

/** @internal */
export const ListPayoutsRequest$outboundSchema: z.ZodMiniType<
  ListPayoutsRequest$Outbound,
  ListPayoutsRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  status: z.optional(ListPayoutsStatus$outboundSchema),
  arrivalDateFrom: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  arrivalDateTo: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
});

export function listPayoutsRequestToJSON(
  listPayoutsRequest: ListPayoutsRequest,
): string {
  return JSON.stringify(
    ListPayoutsRequest$outboundSchema.parse(listPayoutsRequest),
  );
}

/** @internal */
export const ListPayoutsResponse$inboundSchema: z.ZodMiniType<
  ListPayoutsResponse,
  unknown
> = z.object({
  data: z.array(models.Payout$inboundSchema),
  pagination: models.PaginationMeta$inboundSchema,
});

export function listPayoutsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListPayoutsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListPayoutsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListPayoutsResponse' from JSON`,
  );
}
