/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListVenuesSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const ListVenuesStatus = {
  Active: "active",
  Archived: "archived",
} as const;
export type ListVenuesStatus = ClosedEnum<typeof ListVenuesStatus>;

export type ListVenuesRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  status?: ListVenuesStatus | undefined;
};

export type ListVenuesResponse = {
  result: models.VenueList;
};

/** @internal */
export type ListVenuesSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListVenuesSecurity$outboundSchema: z.ZodMiniType<
  ListVenuesSecurity$Outbound,
  ListVenuesSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listVenuesSecurityToJSON(
  listVenuesSecurity: ListVenuesSecurity,
): string {
  return JSON.stringify(
    ListVenuesSecurity$outboundSchema.parse(listVenuesSecurity),
  );
}

/** @internal */
export const ListVenuesStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListVenuesStatus
> = z.enum(ListVenuesStatus);

/** @internal */
export type ListVenuesRequest$Outbound = {
  page: number;
  pageSize: number;
  status?: string | undefined;
};

/** @internal */
export const ListVenuesRequest$outboundSchema: z.ZodMiniType<
  ListVenuesRequest$Outbound,
  ListVenuesRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  status: z.optional(ListVenuesStatus$outboundSchema),
});

export function listVenuesRequestToJSON(
  listVenuesRequest: ListVenuesRequest,
): string {
  return JSON.stringify(
    ListVenuesRequest$outboundSchema.parse(listVenuesRequest),
  );
}

/** @internal */
export const ListVenuesResponse$inboundSchema: z.ZodMiniType<
  ListVenuesResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.VenueList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listVenuesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListVenuesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListVenuesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListVenuesResponse' from JSON`,
  );
}
