/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListCalendarEventsSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type ListCalendarEventsRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  /**
   * UUID v4
   */
  projectId?: string | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
  /**
   * ISO 8601 timestamp (UTC)
   */
  startsAfter?: Date | undefined;
  /**
   * ISO 8601 timestamp (UTC)
   */
  startsBefore?: Date | undefined;
};

export type ListCalendarEventsResponse = {
  result: models.CalendarEventList;
};

/** @internal */
export type ListCalendarEventsSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListCalendarEventsSecurity$outboundSchema: z.ZodMiniType<
  ListCalendarEventsSecurity$Outbound,
  ListCalendarEventsSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listCalendarEventsSecurityToJSON(
  listCalendarEventsSecurity: ListCalendarEventsSecurity,
): string {
  return JSON.stringify(
    ListCalendarEventsSecurity$outboundSchema.parse(listCalendarEventsSecurity),
  );
}

/** @internal */
export type ListCalendarEventsRequest$Outbound = {
  page: number;
  pageSize: number;
  projectId?: string | undefined;
  clientId?: string | undefined;
  startsAfter?: string | undefined;
  startsBefore?: string | undefined;
};

/** @internal */
export const ListCalendarEventsRequest$outboundSchema: z.ZodMiniType<
  ListCalendarEventsRequest$Outbound,
  ListCalendarEventsRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  projectId: z.optional(z.string()),
  clientId: z.optional(z.string()),
  startsAfter: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  startsBefore: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
});

export function listCalendarEventsRequestToJSON(
  listCalendarEventsRequest: ListCalendarEventsRequest,
): string {
  return JSON.stringify(
    ListCalendarEventsRequest$outboundSchema.parse(listCalendarEventsRequest),
  );
}

/** @internal */
export const ListCalendarEventsResponse$inboundSchema: z.ZodMiniType<
  ListCalendarEventsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.CalendarEventList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listCalendarEventsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCalendarEventsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCalendarEventsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCalendarEventsResponse' from JSON`,
  );
}
