/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListMilestonesSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const ParentType = {
  Proposals: "proposals",
  Projects: "projects",
} as const;
export type ParentType = ClosedEnum<typeof ParentType>;

export const ListMilestonesStatus = {
  Pending: "pending",
  InProgress: "in-progress",
  Completed: "completed",
} as const;
export type ListMilestonesStatus = ClosedEnum<typeof ListMilestonesStatus>;

export type ListMilestonesRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  parentType?: ParentType | undefined;
  /**
   * UUID v4
   */
  parentId?: string | undefined;
  status?: ListMilestonesStatus | undefined;
};

/**
 * OK
 */
export type ListMilestonesResponse = {
  data: Array<models.Milestone>;
  pagination: models.PaginationMeta;
};

/** @internal */
export type ListMilestonesSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListMilestonesSecurity$outboundSchema: z.ZodMiniType<
  ListMilestonesSecurity$Outbound,
  ListMilestonesSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listMilestonesSecurityToJSON(
  listMilestonesSecurity: ListMilestonesSecurity,
): string {
  return JSON.stringify(
    ListMilestonesSecurity$outboundSchema.parse(listMilestonesSecurity),
  );
}

/** @internal */
export const ParentType$outboundSchema: z.ZodMiniEnum<typeof ParentType> = z
  .enum(ParentType);

/** @internal */
export const ListMilestonesStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListMilestonesStatus
> = z.enum(ListMilestonesStatus);

/** @internal */
export type ListMilestonesRequest$Outbound = {
  page: number;
  pageSize: number;
  parentType?: string | undefined;
  parentId?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const ListMilestonesRequest$outboundSchema: z.ZodMiniType<
  ListMilestonesRequest$Outbound,
  ListMilestonesRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  parentType: z.optional(ParentType$outboundSchema),
  parentId: z.optional(z.string()),
  status: z.optional(ListMilestonesStatus$outboundSchema),
});

export function listMilestonesRequestToJSON(
  listMilestonesRequest: ListMilestonesRequest,
): string {
  return JSON.stringify(
    ListMilestonesRequest$outboundSchema.parse(listMilestonesRequest),
  );
}

/** @internal */
export const ListMilestonesResponse$inboundSchema: z.ZodMiniType<
  ListMilestonesResponse,
  unknown
> = z.object({
  data: z.array(models.Milestone$inboundSchema),
  pagination: models.PaginationMeta$inboundSchema,
});

export function listMilestonesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListMilestonesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListMilestonesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListMilestonesResponse' from JSON`,
  );
}
