/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListClientDocumentsSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const ListClientDocumentsStatus = {
  Draft: "draft",
  Sent: "sent",
  Viewed: "viewed",
  InProgress: "in_progress",
  Accepted: "accepted",
  Completed: "completed",
  Expired: "expired",
  Void: "void",
} as const;
export type ListClientDocumentsStatus = ClosedEnum<
  typeof ListClientDocumentsStatus
>;

export type ListClientDocumentsRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  status?: ListClientDocumentsStatus | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
  /**
   * UUID v4
   */
  contactId?: string | undefined;
};

export type ListClientDocumentsResponse = {
  result: models.ClientDocumentList;
};

/** @internal */
export type ListClientDocumentsSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListClientDocumentsSecurity$outboundSchema: z.ZodMiniType<
  ListClientDocumentsSecurity$Outbound,
  ListClientDocumentsSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listClientDocumentsSecurityToJSON(
  listClientDocumentsSecurity: ListClientDocumentsSecurity,
): string {
  return JSON.stringify(
    ListClientDocumentsSecurity$outboundSchema.parse(
      listClientDocumentsSecurity,
    ),
  );
}

/** @internal */
export const ListClientDocumentsStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListClientDocumentsStatus
> = z.enum(ListClientDocumentsStatus);

/** @internal */
export type ListClientDocumentsRequest$Outbound = {
  page: number;
  pageSize: number;
  status?: string | undefined;
  clientId?: string | undefined;
  contactId?: string | undefined;
};

/** @internal */
export const ListClientDocumentsRequest$outboundSchema: z.ZodMiniType<
  ListClientDocumentsRequest$Outbound,
  ListClientDocumentsRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  status: z.optional(ListClientDocumentsStatus$outboundSchema),
  clientId: z.optional(z.string()),
  contactId: z.optional(z.string()),
});

export function listClientDocumentsRequestToJSON(
  listClientDocumentsRequest: ListClientDocumentsRequest,
): string {
  return JSON.stringify(
    ListClientDocumentsRequest$outboundSchema.parse(listClientDocumentsRequest),
  );
}

/** @internal */
export const ListClientDocumentsResponse$inboundSchema: z.ZodMiniType<
  ListClientDocumentsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.ClientDocumentList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listClientDocumentsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListClientDocumentsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListClientDocumentsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListClientDocumentsResponse' from JSON`,
  );
}
