/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListInvoicesSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const ListInvoicesStatus = {
  Draft: "draft",
  Sent: "sent",
  Partial: "partial",
  Paid: "paid",
  Void: "void",
} as const;
export type ListInvoicesStatus = ClosedEnum<typeof ListInvoicesStatus>;

/**
 * Filter by the derived overdue condition. `true` → sent/partial invoices past their due date; `false` → everything else. (Replaces the removed `status=overdue` filter.)
 */
export const Overdue = {
  True: "true",
  False: "false",
} as const;
/**
 * Filter by the derived overdue condition. `true` → sent/partial invoices past their due date; `false` → everything else. (Replaces the removed `status=overdue` filter.)
 */
export type Overdue = ClosedEnum<typeof Overdue>;

export type ListInvoicesRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
  status?: ListInvoicesStatus | undefined;
  /**
   * Filter by the derived overdue condition. `true` → sent/partial invoices past their due date; `false` → everything else. (Replaces the removed `status=overdue` filter.)
   */
  overdue?: Overdue | undefined;
};

export type ListInvoicesResponse = {
  result: models.InvoiceList;
};

/** @internal */
export type ListInvoicesSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListInvoicesSecurity$outboundSchema: z.ZodMiniType<
  ListInvoicesSecurity$Outbound,
  ListInvoicesSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listInvoicesSecurityToJSON(
  listInvoicesSecurity: ListInvoicesSecurity,
): string {
  return JSON.stringify(
    ListInvoicesSecurity$outboundSchema.parse(listInvoicesSecurity),
  );
}

/** @internal */
export const ListInvoicesStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListInvoicesStatus
> = z.enum(ListInvoicesStatus);

/** @internal */
export const Overdue$outboundSchema: z.ZodMiniEnum<typeof Overdue> = z.enum(
  Overdue,
);

/** @internal */
export type ListInvoicesRequest$Outbound = {
  page: number;
  pageSize: number;
  clientId?: string | undefined;
  status?: string | undefined;
  overdue?: string | undefined;
};

/** @internal */
export const ListInvoicesRequest$outboundSchema: z.ZodMiniType<
  ListInvoicesRequest$Outbound,
  ListInvoicesRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  clientId: z.optional(z.string()),
  status: z.optional(ListInvoicesStatus$outboundSchema),
  overdue: z.optional(Overdue$outboundSchema),
});

export function listInvoicesRequestToJSON(
  listInvoicesRequest: ListInvoicesRequest,
): string {
  return JSON.stringify(
    ListInvoicesRequest$outboundSchema.parse(listInvoicesRequest),
  );
}

/** @internal */
export const ListInvoicesResponse$inboundSchema: z.ZodMiniType<
  ListInvoicesResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.InvoiceList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listInvoicesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListInvoicesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListInvoicesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListInvoicesResponse' from JSON`,
  );
}
