/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListTimelineItemsSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const ListTimelineItemsStatus = {
  Pending: "pending",
  InProgress: "in-progress",
  Completed: "completed",
  Skipped: "skipped",
} as const;
export type ListTimelineItemsStatus = ClosedEnum<
  typeof ListTimelineItemsStatus
>;

export type ListTimelineItemsRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  eventDayId?: string | undefined;
  status?: ListTimelineItemsStatus | undefined;
};

export type ListTimelineItemsResponse = {
  result: models.TimelineItemList;
};

/** @internal */
export type ListTimelineItemsSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListTimelineItemsSecurity$outboundSchema: z.ZodMiniType<
  ListTimelineItemsSecurity$Outbound,
  ListTimelineItemsSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listTimelineItemsSecurityToJSON(
  listTimelineItemsSecurity: ListTimelineItemsSecurity,
): string {
  return JSON.stringify(
    ListTimelineItemsSecurity$outboundSchema.parse(listTimelineItemsSecurity),
  );
}

/** @internal */
export const ListTimelineItemsStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListTimelineItemsStatus
> = z.enum(ListTimelineItemsStatus);

/** @internal */
export type ListTimelineItemsRequest$Outbound = {
  page: number;
  pageSize: number;
  eventDayId?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const ListTimelineItemsRequest$outboundSchema: z.ZodMiniType<
  ListTimelineItemsRequest$Outbound,
  ListTimelineItemsRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  eventDayId: z.optional(z.string()),
  status: z.optional(ListTimelineItemsStatus$outboundSchema),
});

export function listTimelineItemsRequestToJSON(
  listTimelineItemsRequest: ListTimelineItemsRequest,
): string {
  return JSON.stringify(
    ListTimelineItemsRequest$outboundSchema.parse(listTimelineItemsRequest),
  );
}

/** @internal */
export const ListTimelineItemsResponse$inboundSchema: z.ZodMiniType<
  ListTimelineItemsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.TimelineItemList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listTimelineItemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTimelineItemsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTimelineItemsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTimelineItemsResponse' from JSON`,
  );
}
