/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListFormSubmissionsSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const ListFormSubmissionsKind = {
  Inquiry: "inquiry",
  Questionnaire: "questionnaire",
} as const;
export type ListFormSubmissionsKind = ClosedEnum<
  typeof ListFormSubmissionsKind
>;

export const ListFormSubmissionsStatus = {
  InProgress: "in_progress",
  Submitted: "submitted",
} as const;
export type ListFormSubmissionsStatus = ClosedEnum<
  typeof ListFormSubmissionsStatus
>;

export type ListFormSubmissionsRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  /**
   * UUID v4
   */
  formId?: string | undefined;
  kind?: ListFormSubmissionsKind | undefined;
  status?: ListFormSubmissionsStatus | undefined;
  /**
   * UUID v4
   */
  contactId?: string | undefined;
};

export type ListFormSubmissionsResponse = {
  result: models.FormSubmissionList;
};

/** @internal */
export type ListFormSubmissionsSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListFormSubmissionsSecurity$outboundSchema: z.ZodMiniType<
  ListFormSubmissionsSecurity$Outbound,
  ListFormSubmissionsSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listFormSubmissionsSecurityToJSON(
  listFormSubmissionsSecurity: ListFormSubmissionsSecurity,
): string {
  return JSON.stringify(
    ListFormSubmissionsSecurity$outboundSchema.parse(
      listFormSubmissionsSecurity,
    ),
  );
}

/** @internal */
export const ListFormSubmissionsKind$outboundSchema: z.ZodMiniEnum<
  typeof ListFormSubmissionsKind
> = z.enum(ListFormSubmissionsKind);

/** @internal */
export const ListFormSubmissionsStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListFormSubmissionsStatus
> = z.enum(ListFormSubmissionsStatus);

/** @internal */
export type ListFormSubmissionsRequest$Outbound = {
  page: number;
  pageSize: number;
  formId?: string | undefined;
  kind?: string | undefined;
  status?: string | undefined;
  contactId?: string | undefined;
};

/** @internal */
export const ListFormSubmissionsRequest$outboundSchema: z.ZodMiniType<
  ListFormSubmissionsRequest$Outbound,
  ListFormSubmissionsRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  formId: z.optional(z.string()),
  kind: z.optional(ListFormSubmissionsKind$outboundSchema),
  status: z.optional(ListFormSubmissionsStatus$outboundSchema),
  contactId: z.optional(z.string()),
});

export function listFormSubmissionsRequestToJSON(
  listFormSubmissionsRequest: ListFormSubmissionsRequest,
): string {
  return JSON.stringify(
    ListFormSubmissionsRequest$outboundSchema.parse(listFormSubmissionsRequest),
  );
}

/** @internal */
export const ListFormSubmissionsResponse$inboundSchema: z.ZodMiniType<
  ListFormSubmissionsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.FormSubmissionList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listFormSubmissionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListFormSubmissionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListFormSubmissionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListFormSubmissionsResponse' from JSON`,
  );
}
