/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListClientsSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const ListClientsStatus = {
  Prospect: "prospect",
  Active: "active",
  Inactive: "inactive",
} as const;
export type ListClientsStatus = ClosedEnum<typeof ListClientsStatus>;

export type ListClientsRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  status?: ListClientsStatus | undefined;
};

/**
 * OK
 */
export type ListClientsResponse = {
  data: Array<models.Client>;
  pagination: models.PaginationMeta;
};

/** @internal */
export type ListClientsSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListClientsSecurity$outboundSchema: z.ZodMiniType<
  ListClientsSecurity$Outbound,
  ListClientsSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listClientsSecurityToJSON(
  listClientsSecurity: ListClientsSecurity,
): string {
  return JSON.stringify(
    ListClientsSecurity$outboundSchema.parse(listClientsSecurity),
  );
}

/** @internal */
export const ListClientsStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListClientsStatus
> = z.enum(ListClientsStatus);

/** @internal */
export type ListClientsRequest$Outbound = {
  page: number;
  pageSize: number;
  status?: string | undefined;
};

/** @internal */
export const ListClientsRequest$outboundSchema: z.ZodMiniType<
  ListClientsRequest$Outbound,
  ListClientsRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  status: z.optional(ListClientsStatus$outboundSchema),
});

export function listClientsRequestToJSON(
  listClientsRequest: ListClientsRequest,
): string {
  return JSON.stringify(
    ListClientsRequest$outboundSchema.parse(listClientsRequest),
  );
}

/** @internal */
export const ListClientsResponse$inboundSchema: z.ZodMiniType<
  ListClientsResponse,
  unknown
> = z.object({
  data: z.array(models.Client$inboundSchema),
  pagination: models.PaginationMeta$inboundSchema,
});

export function listClientsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListClientsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListClientsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListClientsResponse' from JSON`,
  );
}
