/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListContractsSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const ListContractsStatus = {
  Draft: "draft",
  Sent: "sent",
  Viewed: "viewed",
  Active: "active",
  Completed: "completed",
  Expired: "expired",
  Voided: "voided",
} as const;
export type ListContractsStatus = ClosedEnum<typeof ListContractsStatus>;

export type ListContractsRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
  status?: ListContractsStatus | undefined;
};

export type ListContractsResponse = {
  result: models.ContractList;
};

/** @internal */
export type ListContractsSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListContractsSecurity$outboundSchema: z.ZodMiniType<
  ListContractsSecurity$Outbound,
  ListContractsSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listContractsSecurityToJSON(
  listContractsSecurity: ListContractsSecurity,
): string {
  return JSON.stringify(
    ListContractsSecurity$outboundSchema.parse(listContractsSecurity),
  );
}

/** @internal */
export const ListContractsStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListContractsStatus
> = z.enum(ListContractsStatus);

/** @internal */
export type ListContractsRequest$Outbound = {
  page: number;
  pageSize: number;
  clientId?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const ListContractsRequest$outboundSchema: z.ZodMiniType<
  ListContractsRequest$Outbound,
  ListContractsRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  clientId: z.optional(z.string()),
  status: z.optional(ListContractsStatus$outboundSchema),
});

export function listContractsRequestToJSON(
  listContractsRequest: ListContractsRequest,
): string {
  return JSON.stringify(
    ListContractsRequest$outboundSchema.parse(listContractsRequest),
  );
}

/** @internal */
export const ListContractsResponse$inboundSchema: z.ZodMiniType<
  ListContractsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.ContractList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listContractsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListContractsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListContractsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListContractsResponse' from JSON`,
  );
}
