/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListCatalogItemsSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const Type = {
  Expense: "expense",
  Charge: "charge",
} as const;
export type Type = ClosedEnum<typeof Type>;

export const ListCatalogItemsStatus = {
  Active: "active",
  Paused: "paused",
  Archived: "archived",
} as const;
export type ListCatalogItemsStatus = ClosedEnum<typeof ListCatalogItemsStatus>;

export type ListCatalogItemsRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  type?: Type | undefined;
  status?: ListCatalogItemsStatus | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
};

export type ListCatalogItemsResponse = {
  result: models.CatalogItemList;
};

/** @internal */
export type ListCatalogItemsSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListCatalogItemsSecurity$outboundSchema: z.ZodMiniType<
  ListCatalogItemsSecurity$Outbound,
  ListCatalogItemsSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listCatalogItemsSecurityToJSON(
  listCatalogItemsSecurity: ListCatalogItemsSecurity,
): string {
  return JSON.stringify(
    ListCatalogItemsSecurity$outboundSchema.parse(listCatalogItemsSecurity),
  );
}

/** @internal */
export const Type$outboundSchema: z.ZodMiniEnum<typeof Type> = z.enum(Type);

/** @internal */
export const ListCatalogItemsStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListCatalogItemsStatus
> = z.enum(ListCatalogItemsStatus);

/** @internal */
export type ListCatalogItemsRequest$Outbound = {
  page: number;
  pageSize: number;
  type?: string | undefined;
  status?: string | undefined;
  clientId?: string | undefined;
};

/** @internal */
export const ListCatalogItemsRequest$outboundSchema: z.ZodMiniType<
  ListCatalogItemsRequest$Outbound,
  ListCatalogItemsRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  type: z.optional(Type$outboundSchema),
  status: z.optional(ListCatalogItemsStatus$outboundSchema),
  clientId: z.optional(z.string()),
});

export function listCatalogItemsRequestToJSON(
  listCatalogItemsRequest: ListCatalogItemsRequest,
): string {
  return JSON.stringify(
    ListCatalogItemsRequest$outboundSchema.parse(listCatalogItemsRequest),
  );
}

/** @internal */
export const ListCatalogItemsResponse$inboundSchema: z.ZodMiniType<
  ListCatalogItemsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.CatalogItemList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listCatalogItemsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListCatalogItemsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListCatalogItemsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListCatalogItemsResponse' from JSON`,
  );
}
