/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListWebhooksSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const Event = {
  InvoiceSent: "invoice_sent",
  InvoiceDueSoon: "invoice_due_soon",
  InvoiceOverdue: "invoice_overdue",
  InvoicePaid: "invoice_paid",
  InvoicePaymentFailed: "invoice_payment_failed",
  InvoiceDisputed: "invoice_disputed",
  InvoicePaymentReminder: "invoice_payment_reminder",
  InvoiceViewed: "invoice_viewed",
  PaymentReceived: "payment_received",
  PaymentRefunded: "payment_refunded",
  PaymentApplied: "payment_applied",
  PaymentUnapplied: "payment_unapplied",
  PaymentDeleted: "payment_deleted",
  PaymentChargeback: "payment_chargeback",
  ReceiptSent: "receipt_sent",
  ScheduleDepositReady: "schedule_deposit_ready",
  ScheduleInstallmentDue: "schedule_installment_due",
  ScheduleInstallmentPaid: "schedule_installment_paid",
  ScheduleCompleted: "schedule_completed",
  DocumentProcessed: "document_processed",
  DocumentActionCreated: "document_action_created",
  DocumentActionApproved: "document_action_approved",
  DocumentNeedsReview: "document_needs_review",
  DocumentFailed: "document_failed",
  ClientCreated: "client_created",
  ContactCreated: "contact_created",
  ProjectCreated: "project_created",
  TimeEntryCreated: "time_entry_created",
  LeadCreated: "lead_created",
  ClientWon: "client_won",
  ClientLost: "client_lost",
  LeadStatusChanged: "lead_status_changed",
  MilestoneApproaching: "milestone_approaching",
  TimerRunningReminder: "timer_running_reminder",
  ContractSent: "contract_sent",
  ContractViewed: "contract_viewed",
  ContractSigned: "contract_signed",
  ContractRecipientSigned: "contract_recipient_signed",
  ContractCountersigned: "contract_countersigned",
  ContractCompleted: "contract_completed",
  ContractExpired: "contract_expired",
  ContractVoided: "contract_voided",
  SmartFileSent: "smart_file_sent",
  SmartFileViewed: "smart_file_viewed",
  SmartFileAccepted: "smart_file_accepted",
  SmartFileCompleted: "smart_file_completed",
  SmartFileExpired: "smart_file_expired",
  FormSubmissionCompleted: "form_submission_completed",
  SubscriptionPaymentFailed: "subscription_payment_failed",
  PayoutPaid: "payout_paid",
  PayoutFailed: "payout_failed",
  EventDayCreated: "event_day_created",
  EventDayPublished: "event_day_published",
  EventDayArchived: "event_day_archived",
  TimelineItemCompleted: "timeline_item_completed",
  TimelineReminderSent: "timeline_reminder_sent",
} as const;
export type Event = ClosedEnum<typeof Event>;

export type ListWebhooksRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  enabled?: boolean | null | undefined;
  event?: Event | undefined;
};

export type ListWebhooksResponse = {
  result: models.WebhookList;
};

/** @internal */
export type ListWebhooksSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListWebhooksSecurity$outboundSchema: z.ZodMiniType<
  ListWebhooksSecurity$Outbound,
  ListWebhooksSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listWebhooksSecurityToJSON(
  listWebhooksSecurity: ListWebhooksSecurity,
): string {
  return JSON.stringify(
    ListWebhooksSecurity$outboundSchema.parse(listWebhooksSecurity),
  );
}

/** @internal */
export const Event$outboundSchema: z.ZodMiniEnum<typeof Event> = z.enum(Event);

/** @internal */
export type ListWebhooksRequest$Outbound = {
  page: number;
  pageSize: number;
  enabled?: boolean | null | undefined;
  event?: string | undefined;
};

/** @internal */
export const ListWebhooksRequest$outboundSchema: z.ZodMiniType<
  ListWebhooksRequest$Outbound,
  ListWebhooksRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  enabled: z.optional(z.nullable(z.boolean())),
  event: z.optional(Event$outboundSchema),
});

export function listWebhooksRequestToJSON(
  listWebhooksRequest: ListWebhooksRequest,
): string {
  return JSON.stringify(
    ListWebhooksRequest$outboundSchema.parse(listWebhooksRequest),
  );
}

/** @internal */
export const ListWebhooksResponse$inboundSchema: z.ZodMiniType<
  ListWebhooksResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.WebhookList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listWebhooksResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListWebhooksResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListWebhooksResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListWebhooksResponse' from JSON`,
  );
}
