/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListDocumentVersionsSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const DocumentType = {
  SmartFile: "smart-file",
  Invoice: "invoice",
  StandaloneContract: "standalone-contract",
} as const;
export type DocumentType = ClosedEnum<typeof DocumentType>;

export type ListDocumentVersionsRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  documentType?: DocumentType | undefined;
  /**
   * Filter to a smart-file (client-document) id.
   */
  documentId?: string | undefined;
  /**
   * Filter to an invoice id.
   */
  invoiceId?: string | undefined;
  /**
   * Filter to a standalone-contract id.
   */
  contractId?: string | undefined;
};

export type ListDocumentVersionsResponse = {
  result: models.DocumentVersionList;
};

/** @internal */
export type ListDocumentVersionsSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListDocumentVersionsSecurity$outboundSchema: z.ZodMiniType<
  ListDocumentVersionsSecurity$Outbound,
  ListDocumentVersionsSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listDocumentVersionsSecurityToJSON(
  listDocumentVersionsSecurity: ListDocumentVersionsSecurity,
): string {
  return JSON.stringify(
    ListDocumentVersionsSecurity$outboundSchema.parse(
      listDocumentVersionsSecurity,
    ),
  );
}

/** @internal */
export const DocumentType$outboundSchema: z.ZodMiniEnum<typeof DocumentType> = z
  .enum(DocumentType);

/** @internal */
export type ListDocumentVersionsRequest$Outbound = {
  page: number;
  pageSize: number;
  documentType?: string | undefined;
  documentId?: string | undefined;
  invoiceId?: string | undefined;
  contractId?: string | undefined;
};

/** @internal */
export const ListDocumentVersionsRequest$outboundSchema: z.ZodMiniType<
  ListDocumentVersionsRequest$Outbound,
  ListDocumentVersionsRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  documentType: z.optional(DocumentType$outboundSchema),
  documentId: z.optional(z.string()),
  invoiceId: z.optional(z.string()),
  contractId: z.optional(z.string()),
});

export function listDocumentVersionsRequestToJSON(
  listDocumentVersionsRequest: ListDocumentVersionsRequest,
): string {
  return JSON.stringify(
    ListDocumentVersionsRequest$outboundSchema.parse(
      listDocumentVersionsRequest,
    ),
  );
}

/** @internal */
export const ListDocumentVersionsResponse$inboundSchema: z.ZodMiniType<
  ListDocumentVersionsResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.DocumentVersionList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listDocumentVersionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListDocumentVersionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListDocumentVersionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListDocumentVersionsResponse' from JSON`,
  );
}
