/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListInquiriesSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const ListInquiriesStatus = {
  New: "new",
  Contacted: "contacted",
  Qualified: "qualified",
  Converted: "converted",
  Declined: "declined",
  Spam: "spam",
} as const;
export type ListInquiriesStatus = ClosedEnum<typeof ListInquiriesStatus>;

export const Source = {
  InquiryForm: "inquiry_form",
  Manual: "manual",
  Referral: "referral",
  Other: "other",
} as const;
export type Source = ClosedEnum<typeof Source>;

export type ListInquiriesRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  status?: ListInquiriesStatus | undefined;
  source?: Source | undefined;
};

export type ListInquiriesResponse = {
  result: models.InquiryList;
};

/** @internal */
export type ListInquiriesSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListInquiriesSecurity$outboundSchema: z.ZodMiniType<
  ListInquiriesSecurity$Outbound,
  ListInquiriesSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listInquiriesSecurityToJSON(
  listInquiriesSecurity: ListInquiriesSecurity,
): string {
  return JSON.stringify(
    ListInquiriesSecurity$outboundSchema.parse(listInquiriesSecurity),
  );
}

/** @internal */
export const ListInquiriesStatus$outboundSchema: z.ZodMiniEnum<
  typeof ListInquiriesStatus
> = z.enum(ListInquiriesStatus);

/** @internal */
export const Source$outboundSchema: z.ZodMiniEnum<typeof Source> = z.enum(
  Source,
);

/** @internal */
export type ListInquiriesRequest$Outbound = {
  page: number;
  pageSize: number;
  status?: string | undefined;
  source?: string | undefined;
};

/** @internal */
export const ListInquiriesRequest$outboundSchema: z.ZodMiniType<
  ListInquiriesRequest$Outbound,
  ListInquiriesRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  status: z.optional(ListInquiriesStatus$outboundSchema),
  source: z.optional(Source$outboundSchema),
});

export function listInquiriesRequestToJSON(
  listInquiriesRequest: ListInquiriesRequest,
): string {
  return JSON.stringify(
    ListInquiriesRequest$outboundSchema.parse(listInquiriesRequest),
  );
}

/** @internal */
export const ListInquiriesResponse$inboundSchema: z.ZodMiniType<
  ListInquiriesResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.InquiryList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listInquiriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListInquiriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListInquiriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListInquiriesResponse' from JSON`,
  );
}
