/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListContactsSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export const Role = {
  Primary: "primary",
  Billing: "billing",
  Other: "other",
} as const;
export type Role = ClosedEnum<typeof Role>;

export type ListContactsRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
  role?: Role | undefined;
};

/**
 * OK
 */
export type ListContactsResponse = {
  data: Array<models.Contact>;
  pagination: models.PaginationMeta;
};

/** @internal */
export type ListContactsSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListContactsSecurity$outboundSchema: z.ZodMiniType<
  ListContactsSecurity$Outbound,
  ListContactsSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listContactsSecurityToJSON(
  listContactsSecurity: ListContactsSecurity,
): string {
  return JSON.stringify(
    ListContactsSecurity$outboundSchema.parse(listContactsSecurity),
  );
}

/** @internal */
export const Role$outboundSchema: z.ZodMiniEnum<typeof Role> = z.enum(Role);

/** @internal */
export type ListContactsRequest$Outbound = {
  page: number;
  pageSize: number;
  clientId?: string | undefined;
  role?: string | undefined;
};

/** @internal */
export const ListContactsRequest$outboundSchema: z.ZodMiniType<
  ListContactsRequest$Outbound,
  ListContactsRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  clientId: z.optional(z.string()),
  role: z.optional(Role$outboundSchema),
});

export function listContactsRequestToJSON(
  listContactsRequest: ListContactsRequest,
): string {
  return JSON.stringify(
    ListContactsRequest$outboundSchema.parse(listContactsRequest),
  );
}

/** @internal */
export const ListContactsResponse$inboundSchema: z.ZodMiniType<
  ListContactsResponse,
  unknown
> = z.object({
  data: z.array(models.Contact$inboundSchema),
  pagination: models.PaginationMeta$inboundSchema,
});

export function listContactsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListContactsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListContactsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListContactsResponse' from JSON`,
  );
}
