/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import * as models from "../index.js";

export type ListTimeEntriesSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type ListTimeEntriesRequest = {
  page?: number | undefined;
  pageSize?: number | undefined;
  /**
   * UUID v4
   */
  projectId?: string | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
  /**
   * UUID v4
   */
  memberId?: string | undefined;
  dateFrom?: Date | undefined;
  dateTo?: Date | undefined;
  billable?: boolean | null | undefined;
};

export type ListTimeEntriesResponse = {
  result: models.TimeEntryList;
};

/** @internal */
export type ListTimeEntriesSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const ListTimeEntriesSecurity$outboundSchema: z.ZodMiniType<
  ListTimeEntriesSecurity$Outbound,
  ListTimeEntriesSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function listTimeEntriesSecurityToJSON(
  listTimeEntriesSecurity: ListTimeEntriesSecurity,
): string {
  return JSON.stringify(
    ListTimeEntriesSecurity$outboundSchema.parse(listTimeEntriesSecurity),
  );
}

/** @internal */
export type ListTimeEntriesRequest$Outbound = {
  page: number;
  pageSize: number;
  projectId?: string | undefined;
  clientId?: string | undefined;
  memberId?: string | undefined;
  dateFrom?: string | undefined;
  dateTo?: string | undefined;
  billable?: boolean | null | undefined;
};

/** @internal */
export const ListTimeEntriesRequest$outboundSchema: z.ZodMiniType<
  ListTimeEntriesRequest$Outbound,
  ListTimeEntriesRequest
> = z.object({
  page: z._default(z.int(), 1),
  pageSize: z._default(z.int(), 25),
  projectId: z.optional(z.string()),
  clientId: z.optional(z.string()),
  memberId: z.optional(z.string()),
  dateFrom: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  dateTo: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  billable: z.optional(z.nullable(z.boolean())),
});

export function listTimeEntriesRequestToJSON(
  listTimeEntriesRequest: ListTimeEntriesRequest,
): string {
  return JSON.stringify(
    ListTimeEntriesRequest$outboundSchema.parse(listTimeEntriesRequest),
  );
}

/** @internal */
export const ListTimeEntriesResponse$inboundSchema: z.ZodMiniType<
  ListTimeEntriesResponse,
  unknown
> = z.pipe(
  z.object({
    Result: models.TimeEntryList$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "Result": "result",
    });
  }),
);

export function listTimeEntriesResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTimeEntriesResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTimeEntriesResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTimeEntriesResponse' from JSON`,
  );
}
