/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateTimelineItemSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateTimelineItemRequest = {
  /**
   * UUID v4
   */
  id: string;
  body: models.TimelineItemUpdate;
};

/** @internal */
export type UpdateTimelineItemSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateTimelineItemSecurity$outboundSchema: z.ZodMiniType<
  UpdateTimelineItemSecurity$Outbound,
  UpdateTimelineItemSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateTimelineItemSecurityToJSON(
  updateTimelineItemSecurity: UpdateTimelineItemSecurity,
): string {
  return JSON.stringify(
    UpdateTimelineItemSecurity$outboundSchema.parse(updateTimelineItemSecurity),
  );
}

/** @internal */
export type UpdateTimelineItemRequest$Outbound = {
  id: string;
  body: models.TimelineItemUpdate$Outbound;
};

/** @internal */
export const UpdateTimelineItemRequest$outboundSchema: z.ZodMiniType<
  UpdateTimelineItemRequest$Outbound,
  UpdateTimelineItemRequest
> = z.object({
  id: z.string(),
  body: models.TimelineItemUpdate$outboundSchema,
});

export function updateTimelineItemRequestToJSON(
  updateTimelineItemRequest: UpdateTimelineItemRequest,
): string {
  return JSON.stringify(
    UpdateTimelineItemRequest$outboundSchema.parse(updateTimelineItemRequest),
  );
}
