/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateCatalogItemSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateCatalogItemRequest = {
  /**
   * UUID v4
   */
  id: string;
  /**
   * Optional unique key that makes this request safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.CatalogItemUpdate;
};

/** @internal */
export type UpdateCatalogItemSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateCatalogItemSecurity$outboundSchema: z.ZodMiniType<
  UpdateCatalogItemSecurity$Outbound,
  UpdateCatalogItemSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateCatalogItemSecurityToJSON(
  updateCatalogItemSecurity: UpdateCatalogItemSecurity,
): string {
  return JSON.stringify(
    UpdateCatalogItemSecurity$outboundSchema.parse(updateCatalogItemSecurity),
  );
}

/** @internal */
export type UpdateCatalogItemRequest$Outbound = {
  id: string;
  "Idempotency-Key"?: string | undefined;
  body: models.CatalogItemUpdate$Outbound;
};

/** @internal */
export const UpdateCatalogItemRequest$outboundSchema: z.ZodMiniType<
  UpdateCatalogItemRequest$Outbound,
  UpdateCatalogItemRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: models.CatalogItemUpdate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function updateCatalogItemRequestToJSON(
  updateCatalogItemRequest: UpdateCatalogItemRequest,
): string {
  return JSON.stringify(
    UpdateCatalogItemRequest$outboundSchema.parse(updateCatalogItemRequest),
  );
}
