/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateVendorSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateVendorRequest = {
  /**
   * UUID v4
   */
  id: string;
  /**
   * Optional unique key that makes this request safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.VendorUpdate;
};

/** @internal */
export type UpdateVendorSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateVendorSecurity$outboundSchema: z.ZodMiniType<
  UpdateVendorSecurity$Outbound,
  UpdateVendorSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateVendorSecurityToJSON(
  updateVendorSecurity: UpdateVendorSecurity,
): string {
  return JSON.stringify(
    UpdateVendorSecurity$outboundSchema.parse(updateVendorSecurity),
  );
}

/** @internal */
export type UpdateVendorRequest$Outbound = {
  id: string;
  "Idempotency-Key"?: string | undefined;
  body: models.VendorUpdate$Outbound;
};

/** @internal */
export const UpdateVendorRequest$outboundSchema: z.ZodMiniType<
  UpdateVendorRequest$Outbound,
  UpdateVendorRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: models.VendorUpdate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function updateVendorRequestToJSON(
  updateVendorRequest: UpdateVendorRequest,
): string {
  return JSON.stringify(
    UpdateVendorRequest$outboundSchema.parse(updateVendorRequest),
  );
}
