/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateVenueSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateVenueRequest = {
  /**
   * UUID v4
   */
  id: string;
  body: models.VenueUpdate;
};

/** @internal */
export type UpdateVenueSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateVenueSecurity$outboundSchema: z.ZodMiniType<
  UpdateVenueSecurity$Outbound,
  UpdateVenueSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateVenueSecurityToJSON(
  updateVenueSecurity: UpdateVenueSecurity,
): string {
  return JSON.stringify(
    UpdateVenueSecurity$outboundSchema.parse(updateVenueSecurity),
  );
}

/** @internal */
export type UpdateVenueRequest$Outbound = {
  id: string;
  body: models.VenueUpdate$Outbound;
};

/** @internal */
export const UpdateVenueRequest$outboundSchema: z.ZodMiniType<
  UpdateVenueRequest$Outbound,
  UpdateVenueRequest
> = z.object({
  id: z.string(),
  body: models.VenueUpdate$outboundSchema,
});

export function updateVenueRequestToJSON(
  updateVenueRequest: UpdateVenueRequest,
): string {
  return JSON.stringify(
    UpdateVenueRequest$outboundSchema.parse(updateVenueRequest),
  );
}
