/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateProjectSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateProjectRequest = {
  /**
   * UUID v4
   */
  id: string;
  body: models.ProjectUpdate;
};

/** @internal */
export type UpdateProjectSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateProjectSecurity$outboundSchema: z.ZodMiniType<
  UpdateProjectSecurity$Outbound,
  UpdateProjectSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateProjectSecurityToJSON(
  updateProjectSecurity: UpdateProjectSecurity,
): string {
  return JSON.stringify(
    UpdateProjectSecurity$outboundSchema.parse(updateProjectSecurity),
  );
}

/** @internal */
export type UpdateProjectRequest$Outbound = {
  id: string;
  body: models.ProjectUpdate$Outbound;
};

/** @internal */
export const UpdateProjectRequest$outboundSchema: z.ZodMiniType<
  UpdateProjectRequest$Outbound,
  UpdateProjectRequest
> = z.object({
  id: z.string(),
  body: models.ProjectUpdate$outboundSchema,
});

export function updateProjectRequestToJSON(
  updateProjectRequest: UpdateProjectRequest,
): string {
  return JSON.stringify(
    UpdateProjectRequest$outboundSchema.parse(updateProjectRequest),
  );
}
