/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateEventDaySecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateEventDayRequest = {
  /**
   * UUID v4
   */
  id: string;
  body: models.EventDayUpdate;
};

/** @internal */
export type UpdateEventDaySecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateEventDaySecurity$outboundSchema: z.ZodMiniType<
  UpdateEventDaySecurity$Outbound,
  UpdateEventDaySecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateEventDaySecurityToJSON(
  updateEventDaySecurity: UpdateEventDaySecurity,
): string {
  return JSON.stringify(
    UpdateEventDaySecurity$outboundSchema.parse(updateEventDaySecurity),
  );
}

/** @internal */
export type UpdateEventDayRequest$Outbound = {
  id: string;
  body: models.EventDayUpdate$Outbound;
};

/** @internal */
export const UpdateEventDayRequest$outboundSchema: z.ZodMiniType<
  UpdateEventDayRequest$Outbound,
  UpdateEventDayRequest
> = z.object({
  id: z.string(),
  body: models.EventDayUpdate$outboundSchema,
});

export function updateEventDayRequestToJSON(
  updateEventDayRequest: UpdateEventDayRequest,
): string {
  return JSON.stringify(
    UpdateEventDayRequest$outboundSchema.parse(updateEventDayRequest),
  );
}
