/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateProposalSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateProposalRequest = {
  /**
   * UUID v4
   */
  id: string;
  body: models.ProposalUpdate;
};

/** @internal */
export type UpdateProposalSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateProposalSecurity$outboundSchema: z.ZodMiniType<
  UpdateProposalSecurity$Outbound,
  UpdateProposalSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateProposalSecurityToJSON(
  updateProposalSecurity: UpdateProposalSecurity,
): string {
  return JSON.stringify(
    UpdateProposalSecurity$outboundSchema.parse(updateProposalSecurity),
  );
}

/** @internal */
export type UpdateProposalRequest$Outbound = {
  id: string;
  body: models.ProposalUpdate$Outbound;
};

/** @internal */
export const UpdateProposalRequest$outboundSchema: z.ZodMiniType<
  UpdateProposalRequest$Outbound,
  UpdateProposalRequest
> = z.object({
  id: z.string(),
  body: models.ProposalUpdate$outboundSchema,
});

export function updateProposalRequestToJSON(
  updateProposalRequest: UpdateProposalRequest,
): string {
  return JSON.stringify(
    UpdateProposalRequest$outboundSchema.parse(updateProposalRequest),
  );
}
