/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateTimelineItemSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateTimelineItemRequest = {
  /**
   * UUID v4
   */
  id: string;
  /**
   * Optional unique key that makes this request safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.TimelineItemUpdate;
};

/** @internal */
export type UpdateTimelineItemSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateTimelineItemSecurity$outboundSchema: z.ZodMiniType<
  UpdateTimelineItemSecurity$Outbound,
  UpdateTimelineItemSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateTimelineItemSecurityToJSON(
  updateTimelineItemSecurity: UpdateTimelineItemSecurity,
): string {
  return JSON.stringify(
    UpdateTimelineItemSecurity$outboundSchema.parse(updateTimelineItemSecurity),
  );
}

/** @internal */
export type UpdateTimelineItemRequest$Outbound = {
  id: string;
  "Idempotency-Key"?: string | undefined;
  body: models.TimelineItemUpdate$Outbound;
};

/** @internal */
export const UpdateTimelineItemRequest$outboundSchema: z.ZodMiniType<
  UpdateTimelineItemRequest$Outbound,
  UpdateTimelineItemRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: models.TimelineItemUpdate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function updateTimelineItemRequestToJSON(
  updateTimelineItemRequest: UpdateTimelineItemRequest,
): string {
  return JSON.stringify(
    UpdateTimelineItemRequest$outboundSchema.parse(updateTimelineItemRequest),
  );
}
