/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateInquirySecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateInquiryRequest = {
  /**
   * UUID v4
   */
  id: string;
  body: models.InquiryUpdate;
};

/** @internal */
export type UpdateInquirySecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateInquirySecurity$outboundSchema: z.ZodMiniType<
  UpdateInquirySecurity$Outbound,
  UpdateInquirySecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateInquirySecurityToJSON(
  updateInquirySecurity: UpdateInquirySecurity,
): string {
  return JSON.stringify(
    UpdateInquirySecurity$outboundSchema.parse(updateInquirySecurity),
  );
}

/** @internal */
export type UpdateInquiryRequest$Outbound = {
  id: string;
  body: models.InquiryUpdate$Outbound;
};

/** @internal */
export const UpdateInquiryRequest$outboundSchema: z.ZodMiniType<
  UpdateInquiryRequest$Outbound,
  UpdateInquiryRequest
> = z.object({
  id: z.string(),
  body: models.InquiryUpdate$outboundSchema,
});

export function updateInquiryRequestToJSON(
  updateInquiryRequest: UpdateInquiryRequest,
): string {
  return JSON.stringify(
    UpdateInquiryRequest$outboundSchema.parse(updateInquiryRequest),
  );
}
