/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateClientSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateClientRequest = {
  /**
   * UUID v4
   */
  id: string;
  body: models.ClientUpdate;
};

/** @internal */
export type UpdateClientSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateClientSecurity$outboundSchema: z.ZodMiniType<
  UpdateClientSecurity$Outbound,
  UpdateClientSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateClientSecurityToJSON(
  updateClientSecurity: UpdateClientSecurity,
): string {
  return JSON.stringify(
    UpdateClientSecurity$outboundSchema.parse(updateClientSecurity),
  );
}

/** @internal */
export type UpdateClientRequest$Outbound = {
  id: string;
  body: models.ClientUpdate$Outbound;
};

/** @internal */
export const UpdateClientRequest$outboundSchema: z.ZodMiniType<
  UpdateClientRequest$Outbound,
  UpdateClientRequest
> = z.object({
  id: z.string(),
  body: models.ClientUpdate$outboundSchema,
});

export function updateClientRequestToJSON(
  updateClientRequest: UpdateClientRequest,
): string {
  return JSON.stringify(
    UpdateClientRequest$outboundSchema.parse(updateClientRequest),
  );
}
