/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateVenueSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateVenueRequest = {
  /**
   * UUID v4
   */
  id: string;
  /**
   * Optional unique key that makes this request safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.VenueUpdate;
};

/** @internal */
export type UpdateVenueSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateVenueSecurity$outboundSchema: z.ZodMiniType<
  UpdateVenueSecurity$Outbound,
  UpdateVenueSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateVenueSecurityToJSON(
  updateVenueSecurity: UpdateVenueSecurity,
): string {
  return JSON.stringify(
    UpdateVenueSecurity$outboundSchema.parse(updateVenueSecurity),
  );
}

/** @internal */
export type UpdateVenueRequest$Outbound = {
  id: string;
  "Idempotency-Key"?: string | undefined;
  body: models.VenueUpdate$Outbound;
};

/** @internal */
export const UpdateVenueRequest$outboundSchema: z.ZodMiniType<
  UpdateVenueRequest$Outbound,
  UpdateVenueRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: models.VenueUpdate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function updateVenueRequestToJSON(
  updateVenueRequest: UpdateVenueRequest,
): string {
  return JSON.stringify(
    UpdateVenueRequest$outboundSchema.parse(updateVenueRequest),
  );
}
