/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateTransactionSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateTransactionRequest = {
  /**
   * UUID v4
   */
  id: string;
  body: models.TransactionUpdate;
};

/** @internal */
export type UpdateTransactionSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateTransactionSecurity$outboundSchema: z.ZodMiniType<
  UpdateTransactionSecurity$Outbound,
  UpdateTransactionSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateTransactionSecurityToJSON(
  updateTransactionSecurity: UpdateTransactionSecurity,
): string {
  return JSON.stringify(
    UpdateTransactionSecurity$outboundSchema.parse(updateTransactionSecurity),
  );
}

/** @internal */
export type UpdateTransactionRequest$Outbound = {
  id: string;
  body: models.TransactionUpdate$Outbound;
};

/** @internal */
export const UpdateTransactionRequest$outboundSchema: z.ZodMiniType<
  UpdateTransactionRequest$Outbound,
  UpdateTransactionRequest
> = z.object({
  id: z.string(),
  body: models.TransactionUpdate$outboundSchema,
});

export function updateTransactionRequestToJSON(
  updateTransactionRequest: UpdateTransactionRequest,
): string {
  return JSON.stringify(
    UpdateTransactionRequest$outboundSchema.parse(updateTransactionRequest),
  );
}
