/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdatePaymentSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdatePaymentRequest = {
  /**
   * UUID v4
   */
  id: string;
  /**
   * Optional unique key that makes this request safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.PaymentUpdate;
};

/** @internal */
export type UpdatePaymentSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdatePaymentSecurity$outboundSchema: z.ZodMiniType<
  UpdatePaymentSecurity$Outbound,
  UpdatePaymentSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updatePaymentSecurityToJSON(
  updatePaymentSecurity: UpdatePaymentSecurity,
): string {
  return JSON.stringify(
    UpdatePaymentSecurity$outboundSchema.parse(updatePaymentSecurity),
  );
}

/** @internal */
export type UpdatePaymentRequest$Outbound = {
  id: string;
  "Idempotency-Key"?: string | undefined;
  body: models.PaymentUpdate$Outbound;
};

/** @internal */
export const UpdatePaymentRequest$outboundSchema: z.ZodMiniType<
  UpdatePaymentRequest$Outbound,
  UpdatePaymentRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: models.PaymentUpdate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function updatePaymentRequestToJSON(
  updatePaymentRequest: UpdatePaymentRequest,
): string {
  return JSON.stringify(
    UpdatePaymentRequest$outboundSchema.parse(updatePaymentRequest),
  );
}
