/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateCalendarEventSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateCalendarEventRequest = {
  /**
   * UUID v4
   */
  id: string;
  body: models.CalendarEventUpdate;
};

/** @internal */
export type UpdateCalendarEventSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateCalendarEventSecurity$outboundSchema: z.ZodMiniType<
  UpdateCalendarEventSecurity$Outbound,
  UpdateCalendarEventSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateCalendarEventSecurityToJSON(
  updateCalendarEventSecurity: UpdateCalendarEventSecurity,
): string {
  return JSON.stringify(
    UpdateCalendarEventSecurity$outboundSchema.parse(
      updateCalendarEventSecurity,
    ),
  );
}

/** @internal */
export type UpdateCalendarEventRequest$Outbound = {
  id: string;
  body: models.CalendarEventUpdate$Outbound;
};

/** @internal */
export const UpdateCalendarEventRequest$outboundSchema: z.ZodMiniType<
  UpdateCalendarEventRequest$Outbound,
  UpdateCalendarEventRequest
> = z.object({
  id: z.string(),
  body: models.CalendarEventUpdate$outboundSchema,
});

export function updateCalendarEventRequestToJSON(
  updateCalendarEventRequest: UpdateCalendarEventRequest,
): string {
  return JSON.stringify(
    UpdateCalendarEventRequest$outboundSchema.parse(updateCalendarEventRequest),
  );
}
