/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateContractSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateContractRequest = {
  /**
   * UUID v4
   */
  id: string;
  /**
   * Optional unique key that makes this request safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.ContractUpdate;
};

/** @internal */
export type UpdateContractSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateContractSecurity$outboundSchema: z.ZodMiniType<
  UpdateContractSecurity$Outbound,
  UpdateContractSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateContractSecurityToJSON(
  updateContractSecurity: UpdateContractSecurity,
): string {
  return JSON.stringify(
    UpdateContractSecurity$outboundSchema.parse(updateContractSecurity),
  );
}

/** @internal */
export type UpdateContractRequest$Outbound = {
  id: string;
  "Idempotency-Key"?: string | undefined;
  body: models.ContractUpdate$Outbound;
};

/** @internal */
export const UpdateContractRequest$outboundSchema: z.ZodMiniType<
  UpdateContractRequest$Outbound,
  UpdateContractRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: models.ContractUpdate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function updateContractRequestToJSON(
  updateContractRequest: UpdateContractRequest,
): string {
  return JSON.stringify(
    UpdateContractRequest$outboundSchema.parse(updateContractRequest),
  );
}
