/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateCalendarEventSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateCalendarEventRequest = {
  /**
   * UUID v4
   */
  id: string;
  /**
   * Optional unique key that makes this request safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.CalendarEventUpdate;
};

/** @internal */
export type UpdateCalendarEventSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateCalendarEventSecurity$outboundSchema: z.ZodMiniType<
  UpdateCalendarEventSecurity$Outbound,
  UpdateCalendarEventSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateCalendarEventSecurityToJSON(
  updateCalendarEventSecurity: UpdateCalendarEventSecurity,
): string {
  return JSON.stringify(
    UpdateCalendarEventSecurity$outboundSchema.parse(
      updateCalendarEventSecurity,
    ),
  );
}

/** @internal */
export type UpdateCalendarEventRequest$Outbound = {
  id: string;
  "Idempotency-Key"?: string | undefined;
  body: models.CalendarEventUpdate$Outbound;
};

/** @internal */
export const UpdateCalendarEventRequest$outboundSchema: z.ZodMiniType<
  UpdateCalendarEventRequest$Outbound,
  UpdateCalendarEventRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: models.CalendarEventUpdate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function updateCalendarEventRequestToJSON(
  updateCalendarEventRequest: UpdateCalendarEventRequest,
): string {
  return JSON.stringify(
    UpdateCalendarEventRequest$outboundSchema.parse(updateCalendarEventRequest),
  );
}
