/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateTimeEntrySecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateTimeEntryRequest = {
  /**
   * UUID v4
   */
  id: string;
  /**
   * Optional unique key that makes this request safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.TimeEntryUpdate;
};

/** @internal */
export type UpdateTimeEntrySecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateTimeEntrySecurity$outboundSchema: z.ZodMiniType<
  UpdateTimeEntrySecurity$Outbound,
  UpdateTimeEntrySecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateTimeEntrySecurityToJSON(
  updateTimeEntrySecurity: UpdateTimeEntrySecurity,
): string {
  return JSON.stringify(
    UpdateTimeEntrySecurity$outboundSchema.parse(updateTimeEntrySecurity),
  );
}

/** @internal */
export type UpdateTimeEntryRequest$Outbound = {
  id: string;
  "Idempotency-Key"?: string | undefined;
  body: models.TimeEntryUpdate$Outbound;
};

/** @internal */
export const UpdateTimeEntryRequest$outboundSchema: z.ZodMiniType<
  UpdateTimeEntryRequest$Outbound,
  UpdateTimeEntryRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: models.TimeEntryUpdate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function updateTimeEntryRequestToJSON(
  updateTimeEntryRequest: UpdateTimeEntryRequest,
): string {
  return JSON.stringify(
    UpdateTimeEntryRequest$outboundSchema.parse(updateTimeEntryRequest),
  );
}
