/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as models from "../index.js";

export type UpdateInvoiceSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateInvoiceRequest = {
  /**
   * UUID v4
   */
  id: string;
  /**
   * Optional unique key that makes this request safely retryable. Replaying the same key returns the original response instead of creating a duplicate; reusing a key with a different request body returns 409.
   */
  idempotencyKey?: string | undefined;
  body: models.InvoiceUpdate;
};

/** @internal */
export type UpdateInvoiceSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateInvoiceSecurity$outboundSchema: z.ZodMiniType<
  UpdateInvoiceSecurity$Outbound,
  UpdateInvoiceSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateInvoiceSecurityToJSON(
  updateInvoiceSecurity: UpdateInvoiceSecurity,
): string {
  return JSON.stringify(
    UpdateInvoiceSecurity$outboundSchema.parse(updateInvoiceSecurity),
  );
}

/** @internal */
export type UpdateInvoiceRequest$Outbound = {
  id: string;
  "Idempotency-Key"?: string | undefined;
  body: models.InvoiceUpdate$Outbound;
};

/** @internal */
export const UpdateInvoiceRequest$outboundSchema: z.ZodMiniType<
  UpdateInvoiceRequest$Outbound,
  UpdateInvoiceRequest
> = z.pipe(
  z.object({
    id: z.string(),
    idempotencyKey: z.optional(z.string()),
    body: models.InvoiceUpdate$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "Idempotency-Key",
    });
  }),
);

export function updateInvoiceRequestToJSON(
  updateInvoiceRequest: UpdateInvoiceRequest,
): string {
  return JSON.stringify(
    UpdateInvoiceRequest$outboundSchema.parse(updateInvoiceRequest),
  );
}
