/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateWebhookSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateWebhookRequest = {
  /**
   * UUID v4
   */
  id: string;
  body: models.WebhookUpdate;
};

/** @internal */
export type UpdateWebhookSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateWebhookSecurity$outboundSchema: z.ZodMiniType<
  UpdateWebhookSecurity$Outbound,
  UpdateWebhookSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateWebhookSecurityToJSON(
  updateWebhookSecurity: UpdateWebhookSecurity,
): string {
  return JSON.stringify(
    UpdateWebhookSecurity$outboundSchema.parse(updateWebhookSecurity),
  );
}

/** @internal */
export type UpdateWebhookRequest$Outbound = {
  id: string;
  body: models.WebhookUpdate$Outbound;
};

/** @internal */
export const UpdateWebhookRequest$outboundSchema: z.ZodMiniType<
  UpdateWebhookRequest$Outbound,
  UpdateWebhookRequest
> = z.object({
  id: z.string(),
  body: models.WebhookUpdate$outboundSchema,
});

export function updateWebhookRequestToJSON(
  updateWebhookRequest: UpdateWebhookRequest,
): string {
  return JSON.stringify(
    UpdateWebhookRequest$outboundSchema.parse(updateWebhookRequest),
  );
}
