/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as models from "../index.js";

export type UpdateContactSecurity = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

export type UpdateContactRequest = {
  /**
   * UUID v4
   */
  id: string;
  body: models.ContactUpdate;
};

/** @internal */
export type UpdateContactSecurity$Outbound = {
  apiKey?: string | undefined;
  bearer?: string | undefined;
};

/** @internal */
export const UpdateContactSecurity$outboundSchema: z.ZodMiniType<
  UpdateContactSecurity$Outbound,
  UpdateContactSecurity
> = z.object({
  apiKey: z.optional(z.string()),
  bearer: z.optional(z.string()),
});

export function updateContactSecurityToJSON(
  updateContactSecurity: UpdateContactSecurity,
): string {
  return JSON.stringify(
    UpdateContactSecurity$outboundSchema.parse(updateContactSecurity),
  );
}

/** @internal */
export type UpdateContactRequest$Outbound = {
  id: string;
  body: models.ContactUpdate$Outbound;
};

/** @internal */
export const UpdateContactRequest$outboundSchema: z.ZodMiniType<
  UpdateContactRequest$Outbound,
  UpdateContactRequest
> = z.object({
  id: z.string(),
  body: models.ContactUpdate$outboundSchema,
});

export function updateContactRequestToJSON(
  updateContactRequest: UpdateContactRequest,
): string {
  return JSON.stringify(
    UpdateContactRequest$outboundSchema.parse(updateContactRequest),
  );
}
