/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  CalendarEvent,
  CalendarEvent$inboundSchema,
} from "./calendar-event.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";

export type CalendarEventList = {
  data: Array<CalendarEvent>;
  pagination: PaginationMeta;
};

/** @internal */
export const CalendarEventList$inboundSchema: z.ZodMiniType<
  CalendarEventList,
  unknown
> = z.object({
  data: z.array(CalendarEvent$inboundSchema),
  pagination: PaginationMeta$inboundSchema,
});

export function calendarEventListFromJSON(
  jsonString: string,
): SafeParseResult<CalendarEventList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CalendarEventList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CalendarEventList' from JSON`,
  );
}
