/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const CalendarEventSource = {
  Manual: "manual",
  Google: "google",
  Microsoft: "microsoft",
  Apple: "apple",
} as const;
export type CalendarEventSource = OpenEnum<typeof CalendarEventSource>;

export type CalendarEvent = {
  /**
   * UUID v4
   */
  id: string;
  title: string;
  description: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  startDateTime: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  endDateTime: Date;
  allDay: boolean;
  /**
   * UUID v4
   */
  projectId: string | null;
  /**
   * UUID v4
   */
  clientId: string | null;
  actionable: boolean;
  /**
   * ISO 8601 timestamp (UTC)
   */
  completedAt: Date | null;
  recurring: boolean;
  rrule: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  recurrenceEnd: Date | null;
  source: CalendarEventSource;
  readOnly: boolean;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const CalendarEventSource$inboundSchema: z.ZodMiniType<
  CalendarEventSource,
  unknown
> = openEnums.inboundSchema(CalendarEventSource);

/** @internal */
export const CalendarEvent$inboundSchema: z.ZodMiniType<
  CalendarEvent,
  unknown
> = z.object({
  id: types.string(),
  title: types.string(),
  description: types.nullable(types.string()),
  startDateTime: types.date(),
  endDateTime: types.date(),
  allDay: types.boolean(),
  projectId: types.nullable(types.string()),
  clientId: types.nullable(types.string()),
  actionable: types.boolean(),
  completedAt: types.nullable(types.date()),
  recurring: types.boolean(),
  rrule: types.nullable(types.string()),
  recurrenceEnd: types.nullable(types.date()),
  source: CalendarEventSource$inboundSchema,
  readOnly: types.boolean(),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function calendarEventFromJSON(
  jsonString: string,
): SafeParseResult<CalendarEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CalendarEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CalendarEvent' from JSON`,
  );
}
