/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CalendarEventCreate = {
  title: string;
  description?: string | undefined;
  /**
   * ISO 8601 timestamp (UTC)
   */
  startDateTime: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  endDateTime: Date;
  allDay?: boolean | undefined;
  /**
   * UUID v4
   */
  projectId?: string | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
  actionable?: boolean | undefined;
  recurring?: boolean | undefined;
  rrule?: string | undefined;
  /**
   * ISO 8601 timestamp (UTC)
   */
  recurrenceEnd?: Date | undefined;
};

/** @internal */
export type CalendarEventCreate$Outbound = {
  title: string;
  description?: string | undefined;
  startDateTime: string;
  endDateTime: string;
  allDay: boolean;
  projectId?: string | undefined;
  clientId?: string | undefined;
  actionable: boolean;
  recurring: boolean;
  rrule?: string | undefined;
  recurrenceEnd?: string | undefined;
};

/** @internal */
export const CalendarEventCreate$outboundSchema: z.ZodMiniType<
  CalendarEventCreate$Outbound,
  CalendarEventCreate
> = z.object({
  title: z.string(),
  description: z.optional(z.string()),
  startDateTime: z.pipe(z.date(), z.transform(v => v.toISOString())),
  endDateTime: z.pipe(z.date(), z.transform(v => v.toISOString())),
  allDay: z._default(z.boolean(), false),
  projectId: z.optional(z.string()),
  clientId: z.optional(z.string()),
  actionable: z._default(z.boolean(), false),
  recurring: z._default(z.boolean(), false),
  rrule: z.optional(z.string()),
  recurrenceEnd: z.optional(
    z.pipe(z.date(), z.transform(v => v.toISOString())),
  ),
});

export function calendarEventCreateToJSON(
  calendarEventCreate: CalendarEventCreate,
): string {
  return JSON.stringify(
    CalendarEventCreate$outboundSchema.parse(calendarEventCreate),
  );
}
