/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type CalendarEventUpdate = {
  title?: string | undefined;
  description?: string | null | undefined;
  /**
   * ISO 8601 timestamp (UTC)
   */
  startDateTime?: Date | undefined;
  /**
   * ISO 8601 timestamp (UTC)
   */
  endDateTime?: Date | undefined;
  allDay?: boolean | undefined;
  /**
   * UUID v4
   */
  projectId?: string | null | undefined;
  /**
   * UUID v4
   */
  clientId?: string | null | undefined;
  actionable?: boolean | undefined;
  /**
   * ISO 8601 timestamp (UTC)
   */
  completedAt?: Date | null | undefined;
  recurring?: boolean | undefined;
  rrule?: string | null | undefined;
  /**
   * ISO 8601 timestamp (UTC)
   */
  recurrenceEnd?: Date | null | undefined;
};

/** @internal */
export type CalendarEventUpdate$Outbound = {
  title?: string | undefined;
  description?: string | null | undefined;
  startDateTime?: string | undefined;
  endDateTime?: string | undefined;
  allDay?: boolean | undefined;
  projectId?: string | null | undefined;
  clientId?: string | null | undefined;
  actionable?: boolean | undefined;
  completedAt?: string | null | undefined;
  recurring?: boolean | undefined;
  rrule?: string | null | undefined;
  recurrenceEnd?: string | null | undefined;
};

/** @internal */
export const CalendarEventUpdate$outboundSchema: z.ZodMiniType<
  CalendarEventUpdate$Outbound,
  CalendarEventUpdate
> = z.object({
  title: z.optional(z.string()),
  description: z.optional(z.nullable(z.string())),
  startDateTime: z.optional(
    z.pipe(z.date(), z.transform(v => v.toISOString())),
  ),
  endDateTime: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  allDay: z.optional(z.boolean()),
  projectId: z.optional(z.nullable(z.string())),
  clientId: z.optional(z.nullable(z.string())),
  actionable: z.optional(z.boolean()),
  completedAt: z.optional(
    z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  ),
  recurring: z.optional(z.boolean()),
  rrule: z.optional(z.nullable(z.string())),
  recurrenceEnd: z.optional(
    z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  ),
});

export function calendarEventUpdateToJSON(
  calendarEventUpdate: CalendarEventUpdate,
): string {
  return JSON.stringify(
    CalendarEventUpdate$outboundSchema.parse(calendarEventUpdate),
  );
}
