/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const CatalogItemCreateUnit = {
  Flat: "flat",
  Hour: "hour",
  Each: "each",
} as const;
export type CatalogItemCreateUnit = ClosedEnum<typeof CatalogItemCreateUnit>;

export const CatalogItemCreateDefaultFrequency = {
  OneTime: "one-time",
  Monthly: "monthly",
  Quarterly: "quarterly",
  Annual: "annual",
} as const;
export type CatalogItemCreateDefaultFrequency = ClosedEnum<
  typeof CatalogItemCreateDefaultFrequency
>;

export const CatalogItemCreateType = {
  Expense: "expense",
  Charge: "charge",
} as const;
export type CatalogItemCreateType = ClosedEnum<typeof CatalogItemCreateType>;

export const CatalogItemCreateStatus = {
  Active: "active",
  Paused: "paused",
  Archived: "archived",
} as const;
export type CatalogItemCreateStatus = ClosedEnum<
  typeof CatalogItemCreateStatus
>;

export type CatalogItemCreate = {
  name: string;
  invoiceLabel?: string | undefined;
  description?: string | undefined;
  invoiceDescription?: string | undefined;
  defaultRate?: number | undefined;
  unit?: CatalogItemCreateUnit | undefined;
  defaultFrequency?: CatalogItemCreateDefaultFrequency | undefined;
  type: CatalogItemCreateType;
  /**
   * UUID v4
   */
  taxCategoryId?: string | undefined;
  status?: CatalogItemCreateStatus | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
};

/** @internal */
export const CatalogItemCreateUnit$outboundSchema: z.ZodMiniEnum<
  typeof CatalogItemCreateUnit
> = z.enum(CatalogItemCreateUnit);

/** @internal */
export const CatalogItemCreateDefaultFrequency$outboundSchema: z.ZodMiniEnum<
  typeof CatalogItemCreateDefaultFrequency
> = z.enum(CatalogItemCreateDefaultFrequency);

/** @internal */
export const CatalogItemCreateType$outboundSchema: z.ZodMiniEnum<
  typeof CatalogItemCreateType
> = z.enum(CatalogItemCreateType);

/** @internal */
export const CatalogItemCreateStatus$outboundSchema: z.ZodMiniEnum<
  typeof CatalogItemCreateStatus
> = z.enum(CatalogItemCreateStatus);

/** @internal */
export type CatalogItemCreate$Outbound = {
  name: string;
  invoiceLabel?: string | undefined;
  description?: string | undefined;
  invoiceDescription?: string | undefined;
  defaultRate?: number | undefined;
  unit: string;
  defaultFrequency: string;
  type: string;
  taxCategoryId?: string | undefined;
  status: string;
  clientId?: string | undefined;
};

/** @internal */
export const CatalogItemCreate$outboundSchema: z.ZodMiniType<
  CatalogItemCreate$Outbound,
  CatalogItemCreate
> = z.object({
  name: z.string(),
  invoiceLabel: z.optional(z.string()),
  description: z.optional(z.string()),
  invoiceDescription: z.optional(z.string()),
  defaultRate: z.optional(z.number()),
  unit: z._default(CatalogItemCreateUnit$outboundSchema, "flat"),
  defaultFrequency: z._default(
    CatalogItemCreateDefaultFrequency$outboundSchema,
    "one-time",
  ),
  type: CatalogItemCreateType$outboundSchema,
  taxCategoryId: z.optional(z.string()),
  status: z._default(CatalogItemCreateStatus$outboundSchema, "active"),
  clientId: z.optional(z.string()),
});

export function catalogItemCreateToJSON(
  catalogItemCreate: CatalogItemCreate,
): string {
  return JSON.stringify(
    CatalogItemCreate$outboundSchema.parse(catalogItemCreate),
  );
}
