/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Client, Client$inboundSchema } from "./client.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";

export type ClientList = {
  data: Array<Client>;
  pagination: PaginationMeta;
};

/** @internal */
export const ClientList$inboundSchema: z.ZodMiniType<ClientList, unknown> = z
  .object({
    data: z.array(Client$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function clientListFromJSON(
  jsonString: string,
): SafeParseResult<ClientList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientList' from JSON`,
  );
}
