/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";
import {
  ClientTaxSettings,
  ClientTaxSettings$Outbound,
  ClientTaxSettings$outboundSchema,
} from "./client-tax-settings.js";

export const ClientCreateStatus = {
  New: "new",
  Contacted: "contacted",
  Qualified: "qualified",
  Active: "active",
  Inactive: "inactive",
  Declined: "declined",
  Spam: "spam",
} as const;
export type ClientCreateStatus = ClosedEnum<typeof ClientCreateStatus>;

export type ClientCreate = {
  name: string;
  status?: ClientCreateStatus | undefined;
  notes?: string | undefined;
  taxSettings?: ClientTaxSettings | undefined;
  invoiceRemindersEnabled?: boolean | undefined;
};

/** @internal */
export const ClientCreateStatus$outboundSchema: z.ZodMiniEnum<
  typeof ClientCreateStatus
> = z.enum(ClientCreateStatus);

/** @internal */
export type ClientCreate$Outbound = {
  name: string;
  status: string;
  notes?: string | undefined;
  taxSettings?: ClientTaxSettings$Outbound | undefined;
  invoiceRemindersEnabled?: boolean | undefined;
};

/** @internal */
export const ClientCreate$outboundSchema: z.ZodMiniType<
  ClientCreate$Outbound,
  ClientCreate
> = z.object({
  name: z.string(),
  status: z._default(ClientCreateStatus$outboundSchema, "active"),
  notes: z.optional(z.string()),
  taxSettings: z.optional(ClientTaxSettings$outboundSchema),
  invoiceRemindersEnabled: z.optional(z.boolean()),
});

export function clientCreateToJSON(clientCreate: ClientCreate): string {
  return JSON.stringify(ClientCreate$outboundSchema.parse(clientCreate));
}
