/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ClientDocumentKind = {
  SmartFile: "smart-file",
} as const;
export type ClientDocumentKind = ClosedEnum<typeof ClientDocumentKind>;

export const ClientDocumentStatus = {
  Draft: "draft",
  Sent: "sent",
  Viewed: "viewed",
  InProgress: "in_progress",
  Accepted: "accepted",
  Completed: "completed",
  Expired: "expired",
  Void: "void",
} as const;
export type ClientDocumentStatus = OpenEnum<typeof ClientDocumentStatus>;

export type ClientDocument = {
  /**
   * UUID v4
   */
  id: string;
  kind: ClientDocumentKind;
  title: string | null;
  status: ClientDocumentStatus;
  /**
   * UUID v4
   */
  contactId: string | null;
  /**
   * UUID v4
   */
  clientId: string | null;
  /**
   * UUID v4
   */
  projectId: string | null;
  /**
   * UUID v4
   */
  engagementProjectId: string | null;
  isTemplate: boolean;
  clientUrl: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  quoteConvertedAt: Date | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  expiresAt: Date | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const ClientDocumentKind$inboundSchema: z.ZodMiniEnum<
  typeof ClientDocumentKind
> = z.enum(ClientDocumentKind);

/** @internal */
export const ClientDocumentStatus$inboundSchema: z.ZodMiniType<
  ClientDocumentStatus,
  unknown
> = openEnums.inboundSchema(ClientDocumentStatus);

/** @internal */
export const ClientDocument$inboundSchema: z.ZodMiniType<
  ClientDocument,
  unknown
> = z.object({
  id: types.string(),
  kind: ClientDocumentKind$inboundSchema,
  title: types.nullable(types.string()),
  status: ClientDocumentStatus$inboundSchema,
  contactId: types.nullable(types.string()),
  clientId: types.nullable(types.string()),
  projectId: types.nullable(types.string()),
  engagementProjectId: types.nullable(types.string()),
  isTemplate: types.boolean(),
  clientUrl: types.nullable(types.string()),
  quoteConvertedAt: types.nullable(types.date()),
  expiresAt: types.nullable(types.date()),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function clientDocumentFromJSON(
  jsonString: string,
): SafeParseResult<ClientDocument, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientDocument$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientDocument' from JSON`,
  );
}
