/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import {
  ClientTaxSettings,
  ClientTaxSettings$inboundSchema,
} from "./client-tax-settings.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ClientStatus = {
  New: "new",
  Contacted: "contacted",
  Qualified: "qualified",
  Active: "active",
  Inactive: "inactive",
  Declined: "declined",
  Spam: "spam",
} as const;
export type ClientStatus = OpenEnum<typeof ClientStatus>;

export const RecurringBillingStatus = {
  Active: "active",
  PastDue: "past_due",
  Paused: "paused",
  Suspended: "suspended",
  PendingSetup: "pending_setup",
} as const;
export type RecurringBillingStatus = OpenEnum<typeof RecurringBillingStatus>;

export type RecurringBilling = {
  status: RecurringBillingStatus;
  nextBillingDate: Date | null;
};

export type Client = {
  /**
   * UUID v4
   */
  id: string;
  name: string;
  status: ClientStatus;
  notes: string | null;
  taxSettings: ClientTaxSettings;
  invoiceRemindersEnabled: boolean;
  recurringBilling: RecurringBilling | null;
  /**
   * UUID v4
   */
  sourceSubmissionId: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const ClientStatus$inboundSchema: z.ZodMiniType<ClientStatus, unknown> =
  openEnums.inboundSchema(ClientStatus);

/** @internal */
export const RecurringBillingStatus$inboundSchema: z.ZodMiniType<
  RecurringBillingStatus,
  unknown
> = openEnums.inboundSchema(RecurringBillingStatus);

/** @internal */
export const RecurringBilling$inboundSchema: z.ZodMiniType<
  RecurringBilling,
  unknown
> = z.object({
  status: RecurringBillingStatus$inboundSchema,
  nextBillingDate: types.nullable(types.date()),
});

export function recurringBillingFromJSON(
  jsonString: string,
): SafeParseResult<RecurringBilling, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RecurringBilling$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RecurringBilling' from JSON`,
  );
}

/** @internal */
export const Client$inboundSchema: z.ZodMiniType<Client, unknown> = z.object({
  id: types.string(),
  name: types.string(),
  status: ClientStatus$inboundSchema,
  notes: types.nullable(types.string()),
  taxSettings: ClientTaxSettings$inboundSchema,
  invoiceRemindersEnabled: types.boolean(),
  recurringBilling: types.nullable(
    z.lazy(() => RecurringBilling$inboundSchema),
  ),
  sourceSubmissionId: types.nullable(types.string()),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function clientFromJSON(
  jsonString: string,
): SafeParseResult<Client, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Client$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Client' from JSON`,
  );
}
