/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  ClientDocument,
  ClientDocument$inboundSchema,
} from "./client-document.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";

export type ClientDocumentList = {
  data: Array<ClientDocument>;
  pagination: PaginationMeta;
};

/** @internal */
export const ClientDocumentList$inboundSchema: z.ZodMiniType<
  ClientDocumentList,
  unknown
> = z.object({
  data: z.array(ClientDocument$inboundSchema),
  pagination: PaginationMeta$inboundSchema,
});

export function clientDocumentListFromJSON(
  jsonString: string,
): SafeParseResult<ClientDocumentList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ClientDocumentList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ClientDocumentList' from JSON`,
  );
}
