/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ContractCreate = {
  title: string;
  /**
   * UUID v4
   */
  clientId: string;
  /**
   * UUID v4
   */
  billingContactId?: string | undefined;
  /**
   * UUID v4
   */
  projectId?: string | undefined;
  /**
   * UUID v4
   */
  sourceTemplateId?: string | undefined;
  issueDate?: Date | undefined;
  effectiveDate?: Date | undefined;
  expirationDate?: Date | undefined;
  contractValue?: number | undefined;
};

/** @internal */
export type ContractCreate$Outbound = {
  title: string;
  clientId: string;
  billingContactId?: string | undefined;
  projectId?: string | undefined;
  sourceTemplateId?: string | undefined;
  issueDate?: string | undefined;
  effectiveDate?: string | undefined;
  expirationDate?: string | undefined;
  contractValue?: number | undefined;
};

/** @internal */
export const ContractCreate$outboundSchema: z.ZodMiniType<
  ContractCreate$Outbound,
  ContractCreate
> = z.object({
  title: z.string(),
  clientId: z.string(),
  billingContactId: z.optional(z.string()),
  projectId: z.optional(z.string()),
  sourceTemplateId: z.optional(z.string()),
  issueDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  effectiveDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  expirationDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  contractValue: z.optional(z.number()),
});

export function contractCreateToJSON(contractCreate: ContractCreate): string {
  return JSON.stringify(ContractCreate$outboundSchema.parse(contractCreate));
}
