/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { ClosedEnum, OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { smartUnion } from "../types/smart-union.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ContractStatus = {
  Draft: "draft",
  Sent: "sent",
  Viewed: "viewed",
  Active: "active",
  Completed: "completed",
  Expired: "expired",
  Voided: "voided",
} as const;
export type ContractStatus = OpenEnum<typeof ContractStatus>;

export const SigningMode = {
  ClientOnly: "client_only",
  CounterSign: "counter_sign",
  AutoCounterSign: "auto_counter_sign",
} as const;
export type SigningMode = OpenEnum<typeof SigningMode>;

export const ContentType = {
  Tiptap: "tiptap",
  Pdf: "pdf",
} as const;
export type ContentType = OpenEnum<typeof ContentType>;

export const EmailEnum = {
  Unknown: "",
} as const;
export type EmailEnum = ClosedEnum<typeof EmailEnum>;

export type Email = string | EmailEnum;

export type Signer = {
  /**
   * UUID v4
   */
  contactId: string | null;
  name: string;
  email: string | EmailEnum;
  role: string;
  order: number;
  status: string;
  /**
   * ISO 8601 timestamp (UTC)
   */
  signedAt: Date | null;
};

export type Contract = {
  /**
   * UUID v4
   */
  id: string;
  contractNumber: string;
  title: string;
  /**
   * UUID v4
   */
  clientId: string;
  /**
   * UUID v4
   */
  billingContactId: string | null;
  /**
   * UUID v4
   */
  proposalId: string | null;
  /**
   * UUID v4
   */
  projectId: string | null;
  /**
   * UUID v4
   */
  sourceTemplateId: string | null;
  status: ContractStatus;
  signingMode: SigningMode;
  contentType: ContentType;
  issueDate: Date | null;
  effectiveDate: Date | null;
  expirationDate: Date | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  signedDate: Date | null;
  currency: string;
  contractValue: number | null;
  signers: Array<Signer>;
  archived: boolean;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const ContractStatus$inboundSchema: z.ZodMiniType<
  ContractStatus,
  unknown
> = openEnums.inboundSchema(ContractStatus);

/** @internal */
export const SigningMode$inboundSchema: z.ZodMiniType<SigningMode, unknown> =
  openEnums.inboundSchema(SigningMode);

/** @internal */
export const ContentType$inboundSchema: z.ZodMiniType<ContentType, unknown> =
  openEnums.inboundSchema(ContentType);

/** @internal */
export const EmailEnum$inboundSchema: z.ZodMiniEnum<typeof EmailEnum> = z.enum(
  EmailEnum,
);

/** @internal */
export const Email$inboundSchema: z.ZodMiniType<Email, unknown> = smartUnion([
  types.string(),
  EmailEnum$inboundSchema,
]);

export function emailFromJSON(
  jsonString: string,
): SafeParseResult<Email, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Email$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Email' from JSON`,
  );
}

/** @internal */
export const Signer$inboundSchema: z.ZodMiniType<Signer, unknown> = z.object({
  contactId: types.nullable(types.string()),
  name: types.string(),
  email: smartUnion([types.string(), EmailEnum$inboundSchema]),
  role: types.string(),
  order: types.number(),
  status: types.string(),
  signedAt: types.nullable(types.date()),
});

export function signerFromJSON(
  jsonString: string,
): SafeParseResult<Signer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Signer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Signer' from JSON`,
  );
}

/** @internal */
export const Contract$inboundSchema: z.ZodMiniType<Contract, unknown> = z
  .object({
    id: types.string(),
    contractNumber: types.string(),
    title: types.string(),
    clientId: types.string(),
    billingContactId: types.nullable(types.string()),
    proposalId: types.nullable(types.string()),
    projectId: types.nullable(types.string()),
    sourceTemplateId: types.nullable(types.string()),
    status: ContractStatus$inboundSchema,
    signingMode: SigningMode$inboundSchema,
    contentType: ContentType$inboundSchema,
    issueDate: types.nullable(types.date()),
    effectiveDate: types.nullable(types.date()),
    expirationDate: types.nullable(types.date()),
    signedDate: types.nullable(types.date()),
    currency: types.string(),
    contractValue: types.nullable(types.number()),
    signers: z.array(z.lazy(() => Signer$inboundSchema)),
    archived: types.boolean(),
    createdAt: types.date(),
    updatedAt: types.date(),
  });

export function contractFromJSON(
  jsonString: string,
): SafeParseResult<Contract, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Contract$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Contract' from JSON`,
  );
}
