/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Contact, Contact$inboundSchema } from "./contact.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";

export type ContactList = {
  data: Array<Contact>;
  pagination: PaginationMeta;
};

/** @internal */
export const ContactList$inboundSchema: z.ZodMiniType<ContactList, unknown> = z
  .object({
    data: z.array(Contact$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function contactListFromJSON(
  jsonString: string,
): SafeParseResult<ContactList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContactList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContactList' from JSON`,
  );
}
