/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const ContactCreateRole = {
  Primary: "primary",
  Billing: "billing",
  Other: "other",
} as const;
export type ContactCreateRole = ClosedEnum<typeof ContactCreateRole>;

export type ContactCreate = {
  name: string;
  email?: string | undefined;
  phone?: string | undefined;
  title?: string | undefined;
  role?: ContactCreateRole | undefined;
  isPrimary?: boolean | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
};

/** @internal */
export const ContactCreateRole$outboundSchema: z.ZodMiniEnum<
  typeof ContactCreateRole
> = z.enum(ContactCreateRole);

/** @internal */
export type ContactCreate$Outbound = {
  name: string;
  email?: string | undefined;
  phone?: string | undefined;
  title?: string | undefined;
  role: string;
  isPrimary: boolean;
  clientId?: string | undefined;
};

/** @internal */
export const ContactCreate$outboundSchema: z.ZodMiniType<
  ContactCreate$Outbound,
  ContactCreate
> = z.object({
  name: z.string(),
  email: z.optional(z.string()),
  phone: z.optional(z.string()),
  title: z.optional(z.string()),
  role: z._default(ContactCreateRole$outboundSchema, "other"),
  isPrimary: z._default(z.boolean(), false),
  clientId: z.optional(z.string()),
});

export function contactCreateToJSON(contactCreate: ContactCreate): string {
  return JSON.stringify(ContactCreate$outboundSchema.parse(contactCreate));
}
