/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { Contract, Contract$inboundSchema } from "./contract.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";

export type ContractList = {
  data: Array<Contract>;
  pagination: PaginationMeta;
};

/** @internal */
export const ContractList$inboundSchema: z.ZodMiniType<ContractList, unknown> =
  z.object({
    data: z.array(Contract$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function contractListFromJSON(
  jsonString: string,
): SafeParseResult<ContractList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ContractList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ContractList' from JSON`,
  );
}
