/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ContractUpdate = {
  title?: string | undefined;
  effectiveDate?: Date | null | undefined;
  expirationDate?: Date | null | undefined;
  archived?: boolean | undefined;
};

/** @internal */
export type ContractUpdate$Outbound = {
  title?: string | undefined;
  effectiveDate?: string | null | undefined;
  expirationDate?: string | null | undefined;
  archived?: boolean | undefined;
};

/** @internal */
export const ContractUpdate$outboundSchema: z.ZodMiniType<
  ContractUpdate$Outbound,
  ContractUpdate
> = z.object({
  title: z.optional(z.string()),
  effectiveDate: z.optional(
    z.nullable(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    )),
  ),
  expirationDate: z.optional(
    z.nullable(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    )),
  ),
  archived: z.optional(z.boolean()),
});

export function contractUpdateToJSON(contractUpdate: ContractUpdate): string {
  return JSON.stringify(ContractUpdate$outboundSchema.parse(contractUpdate));
}
