/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ContactRole = {
  Primary: "primary",
  Billing: "billing",
  Other: "other",
} as const;
export type ContactRole = OpenEnum<typeof ContactRole>;

export type Contact = {
  /**
   * UUID v4
   */
  id: string;
  name: string;
  email: string | null;
  phone: string | null;
  title: string | null;
  role: ContactRole;
  isPrimary: boolean;
  /**
   * UUID v4
   */
  clientId: string | null;
  /**
   * UUID v4
   */
  inquiryId: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const ContactRole$inboundSchema: z.ZodMiniType<ContactRole, unknown> =
  openEnums.inboundSchema(ContactRole);

/** @internal */
export const Contact$inboundSchema: z.ZodMiniType<Contact, unknown> = z.object({
  id: types.string(),
  name: types.string(),
  email: types.nullable(types.string()),
  phone: types.nullable(types.string()),
  title: types.nullable(types.string()),
  role: ContactRole$inboundSchema,
  isPrimary: types.boolean(),
  clientId: types.nullable(types.string()),
  inquiryId: types.nullable(types.string()),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function contactFromJSON(
  jsonString: string,
): SafeParseResult<Contact, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Contact$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Contact' from JSON`,
  );
}
