/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const DocumentType = {
  SmartFile: "smart-file",
  Invoice: "invoice",
  StandaloneContract: "standalone-contract",
} as const;
export type DocumentType = OpenEnum<typeof DocumentType>;

export type DocumentRef = {
  relationTo: string;
  value: string;
};

export const VersionStatus = {
  Issued: "issued",
  Superseded: "superseded",
  Voided: "voided",
} as const;
export type VersionStatus = OpenEnum<typeof VersionStatus>;

export const AcceptedBy = {
  Client: "client",
  Operator: "operator",
  Signing: "signing",
  Backfill: "backfill",
} as const;
export type AcceptedBy = OpenEnum<typeof AcceptedBy>;

export type DocumentVersion = {
  /**
   * UUID v4
   */
  id: string;
  documentType: DocumentType;
  /**
   * UUID v4
   */
  documentId: string | null;
  documentRef: DocumentRef | null;
  versionNumber: number;
  subVersionNumber: number;
  versionStatus: VersionStatus;
  contentHash: string;
  currency: string;
  /**
   * ISO 8601 timestamp (UTC)
   */
  issuedAt: Date | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  viewedAt: Date | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  acceptedAt: Date | null;
  acceptedBy: AcceptedBy | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  supersededAt: Date | null;
  /**
   * UUID v4
   */
  supersededByVersionId: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  voidedAt: Date | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  quoteConvertedAt: Date | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  expiresAt: Date | null;
  /**
   * UUID v4
   */
  engagementProjectId: string | null;
  /**
   * UUID v4
   */
  parentVersionId: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const DocumentType$inboundSchema: z.ZodMiniType<DocumentType, unknown> =
  openEnums.inboundSchema(DocumentType);

/** @internal */
export const DocumentRef$inboundSchema: z.ZodMiniType<DocumentRef, unknown> = z
  .object({
    relationTo: types.string(),
    value: types.string(),
  });

export function documentRefFromJSON(
  jsonString: string,
): SafeParseResult<DocumentRef, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentRef$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentRef' from JSON`,
  );
}

/** @internal */
export const VersionStatus$inboundSchema: z.ZodMiniType<
  VersionStatus,
  unknown
> = openEnums.inboundSchema(VersionStatus);

/** @internal */
export const AcceptedBy$inboundSchema: z.ZodMiniType<AcceptedBy, unknown> =
  openEnums.inboundSchema(AcceptedBy);

/** @internal */
export const DocumentVersion$inboundSchema: z.ZodMiniType<
  DocumentVersion,
  unknown
> = z.object({
  id: types.string(),
  documentType: DocumentType$inboundSchema,
  documentId: types.nullable(types.string()),
  documentRef: types.nullable(z.lazy(() => DocumentRef$inboundSchema)),
  versionNumber: types.number(),
  subVersionNumber: types.number(),
  versionStatus: VersionStatus$inboundSchema,
  contentHash: types.string(),
  currency: types.string(),
  issuedAt: types.nullable(types.date()),
  viewedAt: types.nullable(types.date()),
  acceptedAt: types.nullable(types.date()),
  acceptedBy: types.nullable(AcceptedBy$inboundSchema),
  supersededAt: types.nullable(types.date()),
  supersededByVersionId: types.nullable(types.string()),
  voidedAt: types.nullable(types.date()),
  quoteConvertedAt: types.nullable(types.date()),
  expiresAt: types.nullable(types.date()),
  engagementProjectId: types.nullable(types.string()),
  parentVersionId: types.nullable(types.string()),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function documentVersionFromJSON(
  jsonString: string,
): SafeParseResult<DocumentVersion, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentVersion$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentVersion' from JSON`,
  );
}
