/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import {
  DocumentVersion,
  DocumentVersion$inboundSchema,
} from "./document-version.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";

export type DocumentVersionList = {
  data: Array<DocumentVersion>;
  pagination: PaginationMeta;
};

/** @internal */
export const DocumentVersionList$inboundSchema: z.ZodMiniType<
  DocumentVersionList,
  unknown
> = z.object({
  data: z.array(DocumentVersion$inboundSchema),
  pagination: PaginationMeta$inboundSchema,
});

export function documentVersionListFromJSON(
  jsonString: string,
): SafeParseResult<DocumentVersionList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DocumentVersionList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DocumentVersionList' from JSON`,
  );
}
