/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const EventDayUpdateStatus = {
  Draft: "draft",
  Published: "published",
  Archived: "archived",
} as const;
export type EventDayUpdateStatus = ClosedEnum<typeof EventDayUpdateStatus>;

export type EventDayUpdateVenueAddress = {
  name?: string | undefined;
  street?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  zip?: string | undefined;
  country?: string | undefined;
  lat?: number | undefined;
  lng?: number | undefined;
};

export type EventDayUpdateCustomAnchor = {
  key: string;
  label?: string | undefined;
  time?: string | undefined;
};

export type EventDayUpdate = {
  name?: string | null | undefined;
  date?: Date | undefined;
  status?: EventDayUpdateStatus | undefined;
  /**
   * UUID v4
   */
  projectId?: string | null | undefined;
  /**
   * UUID v4
   */
  clientId?: string | null | undefined;
  ceremonyTime?: string | null | undefined;
  eventStartTime?: string | null | undefined;
  venueTimezone?: string | null | undefined;
  venueAddress?: EventDayUpdateVenueAddress | undefined;
  venueNotes?: string | null | undefined;
  dayStartMinute?: number | undefined;
  dayEndMinute?: number | undefined;
  customAnchors?: Array<EventDayUpdateCustomAnchor> | undefined;
  isPrimary?: boolean | undefined;
  sortOrder?: number | undefined;
};

/** @internal */
export const EventDayUpdateStatus$outboundSchema: z.ZodMiniEnum<
  typeof EventDayUpdateStatus
> = z.enum(EventDayUpdateStatus);

/** @internal */
export type EventDayUpdateVenueAddress$Outbound = {
  name?: string | undefined;
  street?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  zip?: string | undefined;
  country?: string | undefined;
  lat?: number | undefined;
  lng?: number | undefined;
};

/** @internal */
export const EventDayUpdateVenueAddress$outboundSchema: z.ZodMiniType<
  EventDayUpdateVenueAddress$Outbound,
  EventDayUpdateVenueAddress
> = z.object({
  name: z.optional(z.string()),
  street: z.optional(z.string()),
  city: z.optional(z.string()),
  state: z.optional(z.string()),
  zip: z.optional(z.string()),
  country: z.optional(z.string()),
  lat: z.optional(z.number()),
  lng: z.optional(z.number()),
});

export function eventDayUpdateVenueAddressToJSON(
  eventDayUpdateVenueAddress: EventDayUpdateVenueAddress,
): string {
  return JSON.stringify(
    EventDayUpdateVenueAddress$outboundSchema.parse(eventDayUpdateVenueAddress),
  );
}

/** @internal */
export type EventDayUpdateCustomAnchor$Outbound = {
  key: string;
  label?: string | undefined;
  time?: string | undefined;
};

/** @internal */
export const EventDayUpdateCustomAnchor$outboundSchema: z.ZodMiniType<
  EventDayUpdateCustomAnchor$Outbound,
  EventDayUpdateCustomAnchor
> = z.object({
  key: z.string(),
  label: z.optional(z.string()),
  time: z.optional(z.string()),
});

export function eventDayUpdateCustomAnchorToJSON(
  eventDayUpdateCustomAnchor: EventDayUpdateCustomAnchor,
): string {
  return JSON.stringify(
    EventDayUpdateCustomAnchor$outboundSchema.parse(eventDayUpdateCustomAnchor),
  );
}

/** @internal */
export type EventDayUpdate$Outbound = {
  name?: string | null | undefined;
  date?: string | undefined;
  status?: string | undefined;
  projectId?: string | null | undefined;
  clientId?: string | null | undefined;
  ceremonyTime?: string | null | undefined;
  eventStartTime?: string | null | undefined;
  venueTimezone?: string | null | undefined;
  venueAddress?: EventDayUpdateVenueAddress$Outbound | undefined;
  venueNotes?: string | null | undefined;
  dayStartMinute?: number | undefined;
  dayEndMinute?: number | undefined;
  customAnchors?: Array<EventDayUpdateCustomAnchor$Outbound> | undefined;
  isPrimary?: boolean | undefined;
  sortOrder?: number | undefined;
};

/** @internal */
export const EventDayUpdate$outboundSchema: z.ZodMiniType<
  EventDayUpdate$Outbound,
  EventDayUpdate
> = z.object({
  name: z.optional(z.nullable(z.string())),
  date: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  status: z.optional(EventDayUpdateStatus$outboundSchema),
  projectId: z.optional(z.nullable(z.string())),
  clientId: z.optional(z.nullable(z.string())),
  ceremonyTime: z.optional(z.nullable(z.string())),
  eventStartTime: z.optional(z.nullable(z.string())),
  venueTimezone: z.optional(z.nullable(z.string())),
  venueAddress: z.optional(
    z.lazy(() => EventDayUpdateVenueAddress$outboundSchema),
  ),
  venueNotes: z.optional(z.nullable(z.string())),
  dayStartMinute: z.optional(z.int()),
  dayEndMinute: z.optional(z.int()),
  customAnchors: z.optional(
    z.array(z.lazy(() => EventDayUpdateCustomAnchor$outboundSchema)),
  ),
  isPrimary: z.optional(z.boolean()),
  sortOrder: z.optional(z.int()),
});

export function eventDayUpdateToJSON(eventDayUpdate: EventDayUpdate): string {
  return JSON.stringify(EventDayUpdate$outboundSchema.parse(eventDayUpdate));
}
