/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { EventDay, EventDay$inboundSchema } from "./event-day.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";

export type EventDayList = {
  data: Array<EventDay>;
  pagination: PaginationMeta;
};

/** @internal */
export const EventDayList$inboundSchema: z.ZodMiniType<EventDayList, unknown> =
  z.object({
    data: z.array(EventDay$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function eventDayListFromJSON(
  jsonString: string,
): SafeParseResult<EventDayList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventDayList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventDayList' from JSON`,
  );
}
