/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const EventDayVendorUpdateConfirmationStatus = {
  Unconfirmed: "unconfirmed",
  Confirmed: "confirmed",
  Declined: "declined",
} as const;
export type EventDayVendorUpdateConfirmationStatus = ClosedEnum<
  typeof EventDayVendorUpdateConfirmationStatus
>;

export type EventDayVendorUpdate = {
  eventDayId?: string | undefined;
  vendorId?: string | undefined;
  role?: string | undefined;
  callTime?: string | undefined;
  coverageStartTime?: string | undefined;
  coverageEndTime?: string | undefined;
  mealProvided?: boolean | undefined;
  mealNotes?: string | undefined;
  pointOfContact?: string | undefined;
  pointOfContactPhone?: string | undefined;
  internalNotes?: string | undefined;
  confirmationStatus?: EventDayVendorUpdateConfirmationStatus | undefined;
};

/** @internal */
export const EventDayVendorUpdateConfirmationStatus$outboundSchema:
  z.ZodMiniEnum<typeof EventDayVendorUpdateConfirmationStatus> = z.enum(
    EventDayVendorUpdateConfirmationStatus,
  );

/** @internal */
export type EventDayVendorUpdate$Outbound = {
  eventDayId?: string | undefined;
  vendorId?: string | undefined;
  role?: string | undefined;
  callTime?: string | undefined;
  coverageStartTime?: string | undefined;
  coverageEndTime?: string | undefined;
  mealProvided?: boolean | undefined;
  mealNotes?: string | undefined;
  pointOfContact?: string | undefined;
  pointOfContactPhone?: string | undefined;
  internalNotes?: string | undefined;
  confirmationStatus?: string | undefined;
};

/** @internal */
export const EventDayVendorUpdate$outboundSchema: z.ZodMiniType<
  EventDayVendorUpdate$Outbound,
  EventDayVendorUpdate
> = z.object({
  eventDayId: z.optional(z.string()),
  vendorId: z.optional(z.string()),
  role: z.optional(z.string()),
  callTime: z.optional(z.string()),
  coverageStartTime: z.optional(z.string()),
  coverageEndTime: z.optional(z.string()),
  mealProvided: z.optional(z.boolean()),
  mealNotes: z.optional(z.string()),
  pointOfContact: z.optional(z.string()),
  pointOfContactPhone: z.optional(z.string()),
  internalNotes: z.optional(z.string()),
  confirmationStatus: z.optional(
    EventDayVendorUpdateConfirmationStatus$outboundSchema,
  ),
});

export function eventDayVendorUpdateToJSON(
  eventDayVendorUpdate: EventDayVendorUpdate,
): string {
  return JSON.stringify(
    EventDayVendorUpdate$outboundSchema.parse(eventDayVendorUpdate),
  );
}
