/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const EventDayVendorCreateConfirmationStatus = {
  Unconfirmed: "unconfirmed",
  Confirmed: "confirmed",
  Declined: "declined",
} as const;
export type EventDayVendorCreateConfirmationStatus = ClosedEnum<
  typeof EventDayVendorCreateConfirmationStatus
>;

export type EventDayVendorCreate = {
  eventDayId: string;
  vendorId: string;
  role?: string | undefined;
  callTime?: string | undefined;
  coverageStartTime?: string | undefined;
  coverageEndTime?: string | undefined;
  mealProvided?: boolean | undefined;
  mealNotes?: string | undefined;
  pointOfContact?: string | undefined;
  pointOfContactPhone?: string | undefined;
  internalNotes?: string | undefined;
  confirmationStatus?: EventDayVendorCreateConfirmationStatus | undefined;
};

/** @internal */
export const EventDayVendorCreateConfirmationStatus$outboundSchema:
  z.ZodMiniEnum<typeof EventDayVendorCreateConfirmationStatus> = z.enum(
    EventDayVendorCreateConfirmationStatus,
  );

/** @internal */
export type EventDayVendorCreate$Outbound = {
  eventDayId: string;
  vendorId: string;
  role?: string | undefined;
  callTime?: string | undefined;
  coverageStartTime?: string | undefined;
  coverageEndTime?: string | undefined;
  mealProvided: boolean;
  mealNotes?: string | undefined;
  pointOfContact?: string | undefined;
  pointOfContactPhone?: string | undefined;
  internalNotes?: string | undefined;
  confirmationStatus: string;
};

/** @internal */
export const EventDayVendorCreate$outboundSchema: z.ZodMiniType<
  EventDayVendorCreate$Outbound,
  EventDayVendorCreate
> = z.object({
  eventDayId: z.string(),
  vendorId: z.string(),
  role: z.optional(z.string()),
  callTime: z.optional(z.string()),
  coverageStartTime: z.optional(z.string()),
  coverageEndTime: z.optional(z.string()),
  mealProvided: z._default(z.boolean(), false),
  mealNotes: z.optional(z.string()),
  pointOfContact: z.optional(z.string()),
  pointOfContactPhone: z.optional(z.string()),
  internalNotes: z.optional(z.string()),
  confirmationStatus: z._default(
    EventDayVendorCreateConfirmationStatus$outboundSchema,
    "unconfirmed",
  ),
});

export function eventDayVendorCreateToJSON(
  eventDayVendorCreate: EventDayVendorCreate,
): string {
  return JSON.stringify(
    EventDayVendorCreate$outboundSchema.parse(eventDayVendorCreate),
  );
}
