/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  EventDayVendor,
  EventDayVendor$inboundSchema,
} from "./event-day-vendor.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";

export type EventDayVendorList = {
  data: Array<EventDayVendor>;
  pagination: PaginationMeta;
};

/** @internal */
export const EventDayVendorList$inboundSchema: z.ZodMiniType<
  EventDayVendorList,
  unknown
> = z.object({
  data: z.array(EventDayVendor$inboundSchema),
  pagination: PaginationMeta$inboundSchema,
});

export function eventDayVendorListFromJSON(
  jsonString: string,
): SafeParseResult<EventDayVendorList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => EventDayVendorList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'EventDayVendorList' from JSON`,
  );
}
