/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const EventDayCreateStatus = {
  Draft: "draft",
  Published: "published",
  Archived: "archived",
} as const;
export type EventDayCreateStatus = ClosedEnum<typeof EventDayCreateStatus>;

export type EventDayCreateVenueAddress = {
  name?: string | undefined;
  street?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  zip?: string | undefined;
  country?: string | undefined;
  lat?: number | undefined;
  lng?: number | undefined;
};

export type EventDayCreateCustomAnchor = {
  key: string;
  label?: string | undefined;
  time?: string | undefined;
};

export type EventDayCreate = {
  name?: string | undefined;
  date: Date;
  status?: EventDayCreateStatus | undefined;
  /**
   * UUID v4
   */
  projectId?: string | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
  ceremonyTime?: string | undefined;
  eventStartTime?: string | undefined;
  venueTimezone?: string | undefined;
  venueAddress?: EventDayCreateVenueAddress | undefined;
  venueNotes?: string | undefined;
  dayStartMinute?: number | undefined;
  dayEndMinute?: number | undefined;
  customAnchors?: Array<EventDayCreateCustomAnchor> | undefined;
  isPrimary?: boolean | undefined;
  sortOrder?: number | undefined;
};

/** @internal */
export const EventDayCreateStatus$outboundSchema: z.ZodMiniEnum<
  typeof EventDayCreateStatus
> = z.enum(EventDayCreateStatus);

/** @internal */
export type EventDayCreateVenueAddress$Outbound = {
  name?: string | undefined;
  street?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  zip?: string | undefined;
  country?: string | undefined;
  lat?: number | undefined;
  lng?: number | undefined;
};

/** @internal */
export const EventDayCreateVenueAddress$outboundSchema: z.ZodMiniType<
  EventDayCreateVenueAddress$Outbound,
  EventDayCreateVenueAddress
> = z.object({
  name: z.optional(z.string()),
  street: z.optional(z.string()),
  city: z.optional(z.string()),
  state: z.optional(z.string()),
  zip: z.optional(z.string()),
  country: z.optional(z.string()),
  lat: z.optional(z.number()),
  lng: z.optional(z.number()),
});

export function eventDayCreateVenueAddressToJSON(
  eventDayCreateVenueAddress: EventDayCreateVenueAddress,
): string {
  return JSON.stringify(
    EventDayCreateVenueAddress$outboundSchema.parse(eventDayCreateVenueAddress),
  );
}

/** @internal */
export type EventDayCreateCustomAnchor$Outbound = {
  key: string;
  label?: string | undefined;
  time?: string | undefined;
};

/** @internal */
export const EventDayCreateCustomAnchor$outboundSchema: z.ZodMiniType<
  EventDayCreateCustomAnchor$Outbound,
  EventDayCreateCustomAnchor
> = z.object({
  key: z.string(),
  label: z.optional(z.string()),
  time: z.optional(z.string()),
});

export function eventDayCreateCustomAnchorToJSON(
  eventDayCreateCustomAnchor: EventDayCreateCustomAnchor,
): string {
  return JSON.stringify(
    EventDayCreateCustomAnchor$outboundSchema.parse(eventDayCreateCustomAnchor),
  );
}

/** @internal */
export type EventDayCreate$Outbound = {
  name?: string | undefined;
  date: string;
  status: string;
  projectId?: string | undefined;
  clientId?: string | undefined;
  ceremonyTime?: string | undefined;
  eventStartTime?: string | undefined;
  venueTimezone?: string | undefined;
  venueAddress?: EventDayCreateVenueAddress$Outbound | undefined;
  venueNotes?: string | undefined;
  dayStartMinute?: number | undefined;
  dayEndMinute?: number | undefined;
  customAnchors?: Array<EventDayCreateCustomAnchor$Outbound> | undefined;
  isPrimary?: boolean | undefined;
  sortOrder?: number | undefined;
};

/** @internal */
export const EventDayCreate$outboundSchema: z.ZodMiniType<
  EventDayCreate$Outbound,
  EventDayCreate
> = z.object({
  name: z.optional(z.string()),
  date: z.pipe(
    z.date(),
    z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
  ),
  status: z._default(EventDayCreateStatus$outboundSchema, "draft"),
  projectId: z.optional(z.string()),
  clientId: z.optional(z.string()),
  ceremonyTime: z.optional(z.string()),
  eventStartTime: z.optional(z.string()),
  venueTimezone: z.optional(z.string()),
  venueAddress: z.optional(
    z.lazy(() => EventDayCreateVenueAddress$outboundSchema),
  ),
  venueNotes: z.optional(z.string()),
  dayStartMinute: z.optional(z.int()),
  dayEndMinute: z.optional(z.int()),
  customAnchors: z.optional(
    z.array(z.lazy(() => EventDayCreateCustomAnchor$outboundSchema)),
  ),
  isPrimary: z.optional(z.boolean()),
  sortOrder: z.optional(z.int()),
});

export function eventDayCreateToJSON(eventDayCreate: EventDayCreate): string {
  return JSON.stringify(EventDayCreate$outboundSchema.parse(eventDayCreate));
}
