/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type FormSubmissionAnswer = {
  fieldId: string;
  question: string;
  answer: string;
};

/** @internal */
export const FormSubmissionAnswer$inboundSchema: z.ZodMiniType<
  FormSubmissionAnswer,
  unknown
> = z.object({
  fieldId: types.string(),
  question: types.string(),
  answer: types.string(),
});

export function formSubmissionAnswerFromJSON(
  jsonString: string,
): SafeParseResult<FormSubmissionAnswer, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FormSubmissionAnswer$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FormSubmissionAnswer' from JSON`,
  );
}
