/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FormSubmissionAnswer,
  FormSubmissionAnswer$inboundSchema,
} from "./form-submission-answer.js";

export const FormSubmissionKind = {
  Inquiry: "inquiry",
  Questionnaire: "questionnaire",
} as const;
export type FormSubmissionKind = OpenEnum<typeof FormSubmissionKind>;

export const FormSubmissionStatus = {
  InProgress: "in_progress",
  Submitted: "submitted",
} as const;
export type FormSubmissionStatus = OpenEnum<typeof FormSubmissionStatus>;

export type FormSubmission = {
  /**
   * UUID v4
   */
  id: string;
  /**
   * UUID v4
   */
  formId: string | null;
  kind: FormSubmissionKind | null;
  status: FormSubmissionStatus;
  /**
   * UUID v4
   */
  contactId: string | null;
  /**
   * UUID v4
   */
  clientId: string | null;
  source: string | null;
  submittedAt: Date | null;
  answers: Array<FormSubmissionAnswer> | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const FormSubmissionKind$inboundSchema: z.ZodMiniType<
  FormSubmissionKind,
  unknown
> = openEnums.inboundSchema(FormSubmissionKind);

/** @internal */
export const FormSubmissionStatus$inboundSchema: z.ZodMiniType<
  FormSubmissionStatus,
  unknown
> = openEnums.inboundSchema(FormSubmissionStatus);

/** @internal */
export const FormSubmission$inboundSchema: z.ZodMiniType<
  FormSubmission,
  unknown
> = z.object({
  id: types.string(),
  formId: types.nullable(types.string()),
  kind: types.nullable(FormSubmissionKind$inboundSchema),
  status: FormSubmissionStatus$inboundSchema,
  contactId: types.nullable(types.string()),
  clientId: types.nullable(types.string()),
  source: types.nullable(types.string()),
  submittedAt: types.nullable(types.date()),
  answers: types.nullable(z.array(FormSubmissionAnswer$inboundSchema)),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function formSubmissionFromJSON(
  jsonString: string,
): SafeParseResult<FormSubmission, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FormSubmission$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FormSubmission' from JSON`,
  );
}
