/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Form, Form$inboundSchema } from "./form.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";

export type FormList = {
  data: Array<Form>;
  pagination: PaginationMeta;
};

/** @internal */
export const FormList$inboundSchema: z.ZodMiniType<FormList, unknown> = z
  .object({
    data: z.array(Form$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function formListFromJSON(
  jsonString: string,
): SafeParseResult<FormList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FormList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FormList' from JSON`,
  );
}
