/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type FormAttachmentDownload = {
  /**
   * UUID v4
   */
  id: string;
  filename: string;
  mimeType: string | null;
  filesize: number | null;
  downloadUrl: string;
  /**
   * ISO 8601 timestamp (UTC)
   */
  expiresAt: Date;
};

/** @internal */
export const FormAttachmentDownload$inboundSchema: z.ZodMiniType<
  FormAttachmentDownload,
  unknown
> = z.object({
  id: types.string(),
  filename: types.string(),
  mimeType: types.nullable(types.string()),
  filesize: types.nullable(types.number()),
  downloadUrl: types.string(),
  expiresAt: types.date(),
});

export function formAttachmentDownloadFromJSON(
  jsonString: string,
): SafeParseResult<FormAttachmentDownload, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FormAttachmentDownload$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FormAttachmentDownload' from JSON`,
  );
}
