/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  FormSubmission,
  FormSubmission$inboundSchema,
} from "./form-submission.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";

export type FormSubmissionList = {
  data: Array<FormSubmission>;
  pagination: PaginationMeta;
};

/** @internal */
export const FormSubmissionList$inboundSchema: z.ZodMiniType<
  FormSubmissionList,
  unknown
> = z.object({
  data: z.array(FormSubmission$inboundSchema),
  pagination: PaginationMeta$inboundSchema,
});

export function formSubmissionListFromJSON(
  jsonString: string,
): SafeParseResult<FormSubmissionList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FormSubmissionList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FormSubmissionList' from JSON`,
  );
}
