/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const FormKind = {
  Inquiry: "inquiry",
  Questionnaire: "questionnaire",
} as const;
export type FormKind = OpenEnum<typeof FormKind>;

export type Form = {
  /**
   * UUID v4
   */
  id: string;
  name: string;
  title: string | null;
  description: string | null;
  kind: FormKind;
  slug: string | null;
  enabled: boolean;
  isDefault: boolean;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const FormKind$inboundSchema: z.ZodMiniType<FormKind, unknown> =
  openEnums.inboundSchema(FormKind);

/** @internal */
export const Form$inboundSchema: z.ZodMiniType<Form, unknown> = z.object({
  id: types.string(),
  name: types.string(),
  title: types.nullable(types.string()),
  description: types.nullable(types.string()),
  kind: FormKind$inboundSchema,
  slug: types.nullable(types.string()),
  enabled: types.boolean(),
  isDefault: types.boolean(),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function formFromJSON(
  jsonString: string,
): SafeParseResult<Form, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Form$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Form' from JSON`,
  );
}
