/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type FormSubmissionAttachment = {
  /**
   * UUID v4
   */
  id: string;
  filename: string;
  mimeType: string | null;
  filesize: number | null;
};

/** @internal */
export const FormSubmissionAttachment$inboundSchema: z.ZodMiniType<
  FormSubmissionAttachment,
  unknown
> = z.object({
  id: types.string(),
  filename: types.string(),
  mimeType: types.nullable(types.string()),
  filesize: types.nullable(types.number()),
});

export function formSubmissionAttachmentFromJSON(
  jsonString: string,
): SafeParseResult<FormSubmissionAttachment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => FormSubmissionAttachment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'FormSubmissionAttachment' from JSON`,
  );
}
