/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const InquiryCreateSource = {
  InquiryForm: "inquiry_form",
  Manual: "manual",
  Referral: "referral",
  Other: "other",
} as const;
export type InquiryCreateSource = ClosedEnum<typeof InquiryCreateSource>;

export type InquiryCreate = {
  name: string;
  email: string;
  phone?: string | undefined;
  preferredDate?: Date | undefined;
  message?: string | undefined;
  source?: InquiryCreateSource | undefined;
  customAnswers?: { [k: string]: any } | undefined;
  /**
   * UUID v4
   */
  contactId?: string | undefined;
  notes?: string | undefined;
};

/** @internal */
export const InquiryCreateSource$outboundSchema: z.ZodMiniEnum<
  typeof InquiryCreateSource
> = z.enum(InquiryCreateSource);

/** @internal */
export type InquiryCreate$Outbound = {
  name: string;
  email: string;
  phone?: string | undefined;
  preferredDate?: string | undefined;
  message?: string | undefined;
  source: string;
  customAnswers?: { [k: string]: any } | undefined;
  contactId?: string | undefined;
  notes?: string | undefined;
};

/** @internal */
export const InquiryCreate$outboundSchema: z.ZodMiniType<
  InquiryCreate$Outbound,
  InquiryCreate
> = z.object({
  name: z.string(),
  email: z.string(),
  phone: z.optional(z.string()),
  preferredDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  message: z.optional(z.string()),
  source: z._default(InquiryCreateSource$outboundSchema, "manual"),
  customAnswers: z.optional(z.record(z.string(), z.any())),
  contactId: z.optional(z.string()),
  notes: z.optional(z.string()),
});

export function inquiryCreateToJSON(inquiryCreate: InquiryCreate): string {
  return JSON.stringify(InquiryCreate$outboundSchema.parse(inquiryCreate));
}
