/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const InquiryStatus = {
  New: "new",
  Contacted: "contacted",
  Qualified: "qualified",
  Converted: "converted",
  Declined: "declined",
  Spam: "spam",
} as const;
export type InquiryStatus = OpenEnum<typeof InquiryStatus>;

export const InquirySource = {
  InquiryForm: "inquiry_form",
  Manual: "manual",
  Referral: "referral",
  Other: "other",
} as const;
export type InquirySource = OpenEnum<typeof InquirySource>;

export type Inquiry = {
  /**
   * UUID v4
   */
  id: string;
  name: string;
  email: string | null;
  phone: string | null;
  /**
   * UUID v4
   */
  contactId: string | null;
  inquirySlug: string | null;
  preferredDate: Date | null;
  message: string | null;
  status: InquiryStatus;
  source: InquirySource;
  customAnswers: { [k: string]: any } | null;
  /**
   * UUID v4
   */
  convertedClientId: string | null;
  /**
   * UUID v4
   */
  convertedProjectId: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  convertedAt: Date | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  lastContactedAt: Date | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  nextFollowUpAt: Date | null;
  notes: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const InquiryStatus$inboundSchema: z.ZodMiniType<
  InquiryStatus,
  unknown
> = openEnums.inboundSchema(InquiryStatus);

/** @internal */
export const InquirySource$inboundSchema: z.ZodMiniType<
  InquirySource,
  unknown
> = openEnums.inboundSchema(InquirySource);

/** @internal */
export const Inquiry$inboundSchema: z.ZodMiniType<Inquiry, unknown> = z.object({
  id: types.string(),
  name: types.string(),
  email: types.nullable(types.string()),
  phone: types.nullable(types.string()),
  contactId: types.nullable(types.string()),
  inquirySlug: types.nullable(types.string()),
  preferredDate: types.nullable(types.date()),
  message: types.nullable(types.string()),
  status: InquiryStatus$inboundSchema,
  source: InquirySource$inboundSchema,
  customAnswers: types.nullable(z.record(z.string(), z.any())),
  convertedClientId: types.nullable(types.string()),
  convertedProjectId: types.nullable(types.string()),
  convertedAt: types.nullable(types.date()),
  lastContactedAt: types.nullable(types.date()),
  nextFollowUpAt: types.nullable(types.date()),
  notes: types.nullable(types.string()),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function inquiryFromJSON(
  jsonString: string,
): SafeParseResult<Inquiry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Inquiry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Inquiry' from JSON`,
  );
}
