/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Inquiry, Inquiry$inboundSchema } from "./inquiry.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";

export type InquiryList = {
  data: Array<Inquiry>;
  pagination: PaginationMeta;
};

/** @internal */
export const InquiryList$inboundSchema: z.ZodMiniType<InquiryList, unknown> = z
  .object({
    data: z.array(Inquiry$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function inquiryListFromJSON(
  jsonString: string,
): SafeParseResult<InquiryList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InquiryList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InquiryList' from JSON`,
  );
}
