/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { ClosedEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const InquiryStatus = {
  Received: "received",
} as const;
export type InquiryStatus = ClosedEnum<typeof InquiryStatus>;

export type Inquiry = {
  /**
   * UUID v4
   */
  id: string;
  status: InquiryStatus;
  /**
   * UUID v4
   */
  clientId: string | null;
  /**
   * UUID v4
   */
  contactId: string | null;
  /**
   * UUID v4
   */
  submissionId: string | null;
};

/** @internal */
export const InquiryStatus$inboundSchema: z.ZodMiniEnum<typeof InquiryStatus> =
  z.enum(InquiryStatus);

/** @internal */
export const Inquiry$inboundSchema: z.ZodMiniType<Inquiry, unknown> = z.object({
  id: types.string(),
  status: InquiryStatus$inboundSchema,
  clientId: types.nullable(types.string()),
  contactId: types.nullable(types.string()),
  submissionId: types.nullable(types.string()),
});

export function inquiryFromJSON(
  jsonString: string,
): SafeParseResult<Inquiry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Inquiry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Inquiry' from JSON`,
  );
}
