/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { smartUnion } from "../types/smart-union.js";

export type Fields = string | Array<string>;

export type InquiryCreate = {
  name: string;
  email: string;
  phone?: string | undefined;
  preferredDate?: string | undefined;
  message?: string | undefined;
  fields?: { [k: string]: string | Array<string> } | undefined;
};

/** @internal */
export type Fields$Outbound = string | Array<string>;

/** @internal */
export const Fields$outboundSchema: z.ZodMiniType<Fields$Outbound, Fields> =
  smartUnion([z.string(), z.array(z.string())]);

export function fieldsToJSON(fields: Fields): string {
  return JSON.stringify(Fields$outboundSchema.parse(fields));
}

/** @internal */
export type InquiryCreate$Outbound = {
  name: string;
  email: string;
  phone?: string | undefined;
  preferredDate?: string | undefined;
  message?: string | undefined;
  fields?: { [k: string]: string | Array<string> } | undefined;
};

/** @internal */
export const InquiryCreate$outboundSchema: z.ZodMiniType<
  InquiryCreate$Outbound,
  InquiryCreate
> = z.object({
  name: z.string(),
  email: z.string(),
  phone: z.optional(z.string()),
  preferredDate: z.optional(z.string()),
  message: z.optional(z.string()),
  fields: z.optional(
    z.record(z.string(), smartUnion([z.string(), z.array(z.string())])),
  ),
});

export function inquiryCreateToJSON(inquiryCreate: InquiryCreate): string {
  return JSON.stringify(InquiryCreate$outboundSchema.parse(inquiryCreate));
}
