/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  InvoiceLineItem,
  InvoiceLineItem$inboundSchema,
} from "./invoice-line-item.js";

export const InvoiceStatus = {
  Draft: "draft",
  Sent: "sent",
  Partial: "partial",
  Paid: "paid",
  Overdue: "overdue",
  Void: "void",
} as const;
export type InvoiceStatus = OpenEnum<typeof InvoiceStatus>;

export type Invoice = {
  /**
   * UUID v4
   */
  id: string;
  invoiceNumber: string;
  /**
   * UUID v4
   */
  clientId: string;
  /**
   * UUID v4
   */
  billingContactId: string | null;
  projectIds: Array<string>;
  status: InvoiceStatus;
  subject: string | null;
  issueDate: Date;
  dueDate: Date;
  currency: string;
  subtotal: number;
  discountAmount: number;
  taxAmount: number;
  total: number;
  amountPaid: number;
  balanceDue: number;
  paymentTerms: string | null;
  notes: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  paidAt: Date | null;
  lineItems: Array<InvoiceLineItem>;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const InvoiceStatus$inboundSchema: z.ZodMiniType<
  InvoiceStatus,
  unknown
> = openEnums.inboundSchema(InvoiceStatus);

/** @internal */
export const Invoice$inboundSchema: z.ZodMiniType<Invoice, unknown> = z.object({
  id: types.string(),
  invoiceNumber: types.string(),
  clientId: types.string(),
  billingContactId: types.nullable(types.string()),
  projectIds: z.array(types.string()),
  status: InvoiceStatus$inboundSchema,
  subject: types.nullable(types.string()),
  issueDate: types.date(),
  dueDate: types.date(),
  currency: types.string(),
  subtotal: types.number(),
  discountAmount: types.number(),
  taxAmount: types.number(),
  total: types.number(),
  amountPaid: types.number(),
  balanceDue: types.number(),
  paymentTerms: types.nullable(types.string()),
  notes: types.nullable(types.string()),
  paidAt: types.nullable(types.date()),
  lineItems: z.array(InvoiceLineItem$inboundSchema),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function invoiceFromJSON(
  jsonString: string,
): SafeParseResult<Invoice, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Invoice$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Invoice' from JSON`,
  );
}
