/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const InvoiceCreateStatus = {
  Draft: "draft",
  Sent: "sent",
} as const;
export type InvoiceCreateStatus = ClosedEnum<typeof InvoiceCreateStatus>;

export type LineItem = {
  description: string;
  quantity: number;
  unitPrice: number;
  taxable?: boolean | undefined;
  discountPercent?: number | undefined;
};

export type InvoiceCreate = {
  /**
   * UUID v4
   */
  clientId: string;
  /**
   * UUID v4
   */
  billingContactId?: string | undefined;
  projectIds?: Array<string> | undefined;
  status?: InvoiceCreateStatus | undefined;
  subject?: string | undefined;
  issueDate?: Date | undefined;
  dueDate?: Date | undefined;
  paymentTerms?: string | undefined;
  notes?: string | undefined;
  lineItems: Array<LineItem>;
};

/** @internal */
export const InvoiceCreateStatus$outboundSchema: z.ZodMiniEnum<
  typeof InvoiceCreateStatus
> = z.enum(InvoiceCreateStatus);

/** @internal */
export type LineItem$Outbound = {
  description: string;
  quantity: number;
  unitPrice: number;
  taxable: boolean;
  discountPercent?: number | undefined;
};

/** @internal */
export const LineItem$outboundSchema: z.ZodMiniType<
  LineItem$Outbound,
  LineItem
> = z.object({
  description: z.string(),
  quantity: z.number(),
  unitPrice: z.number(),
  taxable: z._default(z.boolean(), false),
  discountPercent: z.optional(z.number()),
});

export function lineItemToJSON(lineItem: LineItem): string {
  return JSON.stringify(LineItem$outboundSchema.parse(lineItem));
}

/** @internal */
export type InvoiceCreate$Outbound = {
  clientId: string;
  billingContactId?: string | undefined;
  projectIds?: Array<string> | undefined;
  status: string;
  subject?: string | undefined;
  issueDate?: string | undefined;
  dueDate?: string | undefined;
  paymentTerms?: string | undefined;
  notes?: string | undefined;
  lineItems: Array<LineItem$Outbound>;
};

/** @internal */
export const InvoiceCreate$outboundSchema: z.ZodMiniType<
  InvoiceCreate$Outbound,
  InvoiceCreate
> = z.object({
  clientId: z.string(),
  billingContactId: z.optional(z.string()),
  projectIds: z.optional(z.array(z.string())),
  status: z._default(InvoiceCreateStatus$outboundSchema, "draft"),
  subject: z.optional(z.string()),
  issueDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  dueDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  paymentTerms: z.optional(z.string()),
  notes: z.optional(z.string()),
  lineItems: z.array(z.lazy(() => LineItem$outboundSchema)),
});

export function invoiceCreateToJSON(invoiceCreate: InvoiceCreate): string {
  return JSON.stringify(InvoiceCreate$outboundSchema.parse(invoiceCreate));
}
