/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const InvoiceUpdateStatus = {
  Sent: "sent",
  Void: "void",
} as const;
export type InvoiceUpdateStatus = ClosedEnum<typeof InvoiceUpdateStatus>;

export type InvoiceUpdate = {
  /**
   * UUID v4
   */
  billingContactId?: string | null | undefined;
  projectIds?: Array<string> | undefined;
  status?: InvoiceUpdateStatus | undefined;
  subject?: string | null | undefined;
  issueDate?: Date | undefined;
  dueDate?: Date | undefined;
  paymentTerms?: string | null | undefined;
  notes?: string | null | undefined;
};

/** @internal */
export const InvoiceUpdateStatus$outboundSchema: z.ZodMiniEnum<
  typeof InvoiceUpdateStatus
> = z.enum(InvoiceUpdateStatus);

/** @internal */
export type InvoiceUpdate$Outbound = {
  billingContactId?: string | null | undefined;
  projectIds?: Array<string> | undefined;
  status?: string | undefined;
  subject?: string | null | undefined;
  issueDate?: string | undefined;
  dueDate?: string | undefined;
  paymentTerms?: string | null | undefined;
  notes?: string | null | undefined;
};

/** @internal */
export const InvoiceUpdate$outboundSchema: z.ZodMiniType<
  InvoiceUpdate$Outbound,
  InvoiceUpdate
> = z.object({
  billingContactId: z.optional(z.nullable(z.string())),
  projectIds: z.optional(z.array(z.string())),
  status: z.optional(InvoiceUpdateStatus$outboundSchema),
  subject: z.optional(z.nullable(z.string())),
  issueDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  dueDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  paymentTerms: z.optional(z.nullable(z.string())),
  notes: z.optional(z.nullable(z.string())),
});

export function invoiceUpdateToJSON(invoiceUpdate: InvoiceUpdate): string {
  return JSON.stringify(InvoiceUpdate$outboundSchema.parse(invoiceUpdate));
}
