/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Invoice, Invoice$inboundSchema } from "./invoice.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";

export type InvoiceList = {
  data: Array<Invoice>;
  pagination: PaginationMeta;
};

/** @internal */
export const InvoiceList$inboundSchema: z.ZodMiniType<InvoiceList, unknown> = z
  .object({
    data: z.array(Invoice$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function invoiceListFromJSON(
  jsonString: string,
): SafeParseResult<InvoiceList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoiceList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoiceList' from JSON`,
  );
}
