/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type InvoiceLineItem = {
  /**
   * UUID v4
   */
  id: string;
  description: string;
  quantity: number;
  unitPrice: number;
  taxable: boolean;
  discountPercent: number | null;
  total: number;
};

/** @internal */
export const InvoiceLineItem$inboundSchema: z.ZodMiniType<
  InvoiceLineItem,
  unknown
> = z.object({
  id: types.string(),
  description: types.string(),
  quantity: types.number(),
  unitPrice: types.number(),
  taxable: types.boolean(),
  discountPercent: types.nullable(types.number()),
  total: types.number(),
});

export function invoiceLineItemFromJSON(
  jsonString: string,
): SafeParseResult<InvoiceLineItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InvoiceLineItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InvoiceLineItem' from JSON`,
  );
}
