/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const MilestoneCreateParentType = {
  Projects: "projects",
  ClientDocuments: "client-documents",
} as const;
export type MilestoneCreateParentType = ClosedEnum<
  typeof MilestoneCreateParentType
>;

export const MilestoneCreateStatus = {
  Pending: "pending",
  InProgress: "in-progress",
  Completed: "completed",
} as const;
export type MilestoneCreateStatus = ClosedEnum<typeof MilestoneCreateStatus>;

export type MilestoneCreate = {
  parentType: MilestoneCreateParentType;
  /**
   * UUID v4
   */
  parentId: string;
  title: string;
  description?: string | undefined;
  date: Date;
  time?: string | undefined;
  status?: MilestoneCreateStatus | undefined;
  /**
   * UUID v4
   */
  assigneeId?: string | undefined;
  /**
   * UUID v4
   */
  catalogItemId?: string | undefined;
  sortOrder?: number | undefined;
};

/** @internal */
export const MilestoneCreateParentType$outboundSchema: z.ZodMiniEnum<
  typeof MilestoneCreateParentType
> = z.enum(MilestoneCreateParentType);

/** @internal */
export const MilestoneCreateStatus$outboundSchema: z.ZodMiniEnum<
  typeof MilestoneCreateStatus
> = z.enum(MilestoneCreateStatus);

/** @internal */
export type MilestoneCreate$Outbound = {
  parentType: string;
  parentId: string;
  title: string;
  description?: string | undefined;
  date: string;
  time?: string | undefined;
  status: string;
  assigneeId?: string | undefined;
  catalogItemId?: string | undefined;
  sortOrder?: number | undefined;
};

/** @internal */
export const MilestoneCreate$outboundSchema: z.ZodMiniType<
  MilestoneCreate$Outbound,
  MilestoneCreate
> = z.object({
  parentType: MilestoneCreateParentType$outboundSchema,
  parentId: z.string(),
  title: z.string(),
  description: z.optional(z.string()),
  date: z.pipe(
    z.date(),
    z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
  ),
  time: z.optional(z.string()),
  status: z._default(MilestoneCreateStatus$outboundSchema, "pending"),
  assigneeId: z.optional(z.string()),
  catalogItemId: z.optional(z.string()),
  sortOrder: z.optional(z.int()),
});

export function milestoneCreateToJSON(
  milestoneCreate: MilestoneCreate,
): string {
  return JSON.stringify(MilestoneCreate$outboundSchema.parse(milestoneCreate));
}
