/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const MilestoneUpdateStatus = {
  Pending: "pending",
  InProgress: "in-progress",
  Completed: "completed",
} as const;
export type MilestoneUpdateStatus = ClosedEnum<typeof MilestoneUpdateStatus>;

export type MilestoneUpdate = {
  title?: string | undefined;
  description?: string | null | undefined;
  date?: Date | null | undefined;
  time?: string | null | undefined;
  status?: MilestoneUpdateStatus | undefined;
  /**
   * UUID v4
   */
  assigneeId?: string | null | undefined;
  /**
   * UUID v4
   */
  catalogItemId?: string | null | undefined;
  sortOrder?: number | undefined;
};

/** @internal */
export const MilestoneUpdateStatus$outboundSchema: z.ZodMiniEnum<
  typeof MilestoneUpdateStatus
> = z.enum(MilestoneUpdateStatus);

/** @internal */
export type MilestoneUpdate$Outbound = {
  title?: string | undefined;
  description?: string | null | undefined;
  date?: string | null | undefined;
  time?: string | null | undefined;
  status?: string | undefined;
  assigneeId?: string | null | undefined;
  catalogItemId?: string | null | undefined;
  sortOrder?: number | undefined;
};

/** @internal */
export const MilestoneUpdate$outboundSchema: z.ZodMiniType<
  MilestoneUpdate$Outbound,
  MilestoneUpdate
> = z.object({
  title: z.optional(z.string()),
  description: z.optional(z.nullable(z.string())),
  date: z.optional(
    z.nullable(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    )),
  ),
  time: z.optional(z.nullable(z.string())),
  status: z.optional(MilestoneUpdateStatus$outboundSchema),
  assigneeId: z.optional(z.nullable(z.string())),
  catalogItemId: z.optional(z.nullable(z.string())),
  sortOrder: z.optional(z.int()),
});

export function milestoneUpdateToJSON(
  milestoneUpdate: MilestoneUpdate,
): string {
  return JSON.stringify(MilestoneUpdate$outboundSchema.parse(milestoneUpdate));
}
