/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import { Milestone, Milestone$inboundSchema } from "./milestone.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";

export type MilestoneList = {
  data: Array<Milestone>;
  pagination: PaginationMeta;
};

/** @internal */
export const MilestoneList$inboundSchema: z.ZodMiniType<
  MilestoneList,
  unknown
> = z.object({
  data: z.array(Milestone$inboundSchema),
  pagination: PaginationMeta$inboundSchema,
});

export function milestoneListFromJSON(
  jsonString: string,
): SafeParseResult<MilestoneList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MilestoneList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MilestoneList' from JSON`,
  );
}
