/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";
import { Payment, Payment$inboundSchema } from "./payment.js";

export type PaymentList = {
  data: Array<Payment>;
  pagination: PaginationMeta;
};

/** @internal */
export const PaymentList$inboundSchema: z.ZodMiniType<PaymentList, unknown> = z
  .object({
    data: z.array(Payment$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function paymentListFromJSON(
  jsonString: string,
): SafeParseResult<PaymentList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PaymentList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PaymentList' from JSON`,
  );
}
