/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const PaymentMethod = {
  Stripe: "stripe",
  Check: "check",
  BankTransfer: "bank_transfer",
  Cash: "cash",
  Venmo: "venmo",
  Zelle: "zelle",
  Paypal: "paypal",
  Wire: "wire",
  Other: "other",
} as const;
export type PaymentMethod = OpenEnum<typeof PaymentMethod>;

export const PaymentStatus = {
  Pending: "pending",
  Processing: "processing",
  Succeeded: "succeeded",
  Failed: "failed",
} as const;
export type PaymentStatus = OpenEnum<typeof PaymentStatus>;

export const PaymentKind = {
  Payment: "payment",
  Refund: "refund",
  Chargeback: "chargeback",
  DisputeFee: "dispute_fee",
  Adjustment: "adjustment",
} as const;
export type PaymentKind = OpenEnum<typeof PaymentKind>;

export type Payment = {
  /**
   * UUID v4
   */
  id: string;
  /**
   * UUID v4
   */
  clientId: string;
  /**
   * UUID v4
   */
  invoiceId: string | null;
  amount: number;
  currency: string;
  receivedDate: Date;
  method: PaymentMethod;
  status: PaymentStatus;
  kind: PaymentKind;
  reference: string | null;
  notes: string | null;
  netAmount: number | null;
  /**
   * UUID v4
   */
  payoutId: string | null;
  /**
   * UUID v4
   */
  refundOfId: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const PaymentMethod$inboundSchema: z.ZodMiniType<
  PaymentMethod,
  unknown
> = openEnums.inboundSchema(PaymentMethod);

/** @internal */
export const PaymentStatus$inboundSchema: z.ZodMiniType<
  PaymentStatus,
  unknown
> = openEnums.inboundSchema(PaymentStatus);

/** @internal */
export const PaymentKind$inboundSchema: z.ZodMiniType<PaymentKind, unknown> =
  openEnums.inboundSchema(PaymentKind);

/** @internal */
export const Payment$inboundSchema: z.ZodMiniType<Payment, unknown> = z.object({
  id: types.string(),
  clientId: types.string(),
  invoiceId: types.nullable(types.string()),
  amount: types.number(),
  currency: types.string(),
  receivedDate: types.date(),
  method: PaymentMethod$inboundSchema,
  status: PaymentStatus$inboundSchema,
  kind: PaymentKind$inboundSchema,
  reference: types.nullable(types.string()),
  notes: types.nullable(types.string()),
  netAmount: types.nullable(types.number()),
  payoutId: types.nullable(types.string()),
  refundOfId: types.nullable(types.string()),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function paymentFromJSON(
  jsonString: string,
): SafeParseResult<Payment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Payment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Payment' from JSON`,
  );
}
