/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type PaymentUpdate = {
  reference?: string | null | undefined;
  notes?: string | null | undefined;
};

/** @internal */
export type PaymentUpdate$Outbound = {
  reference?: string | null | undefined;
  notes?: string | null | undefined;
};

/** @internal */
export const PaymentUpdate$outboundSchema: z.ZodMiniType<
  PaymentUpdate$Outbound,
  PaymentUpdate
> = z.object({
  reference: z.optional(z.nullable(z.string())),
  notes: z.optional(z.nullable(z.string())),
});

export function paymentUpdateToJSON(paymentUpdate: PaymentUpdate): string {
  return JSON.stringify(PaymentUpdate$outboundSchema.parse(paymentUpdate));
}
