/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";
import { Payout, Payout$inboundSchema } from "./payout.js";

export type PayoutList = {
  data: Array<Payout>;
  pagination: PaginationMeta;
};

/** @internal */
export const PayoutList$inboundSchema: z.ZodMiniType<PayoutList, unknown> = z
  .object({
    data: z.array(Payout$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function payoutListFromJSON(
  jsonString: string,
): SafeParseResult<PayoutList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PayoutList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PayoutList' from JSON`,
  );
}
