/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const PayoutStatus = {
  Pending: "pending",
  InTransit: "in_transit",
  Paid: "paid",
  Failed: "failed",
  Canceled: "canceled",
} as const;
export type PayoutStatus = OpenEnum<typeof PayoutStatus>;

export type Payout = {
  /**
   * UUID v4
   */
  id: string;
  stripePayoutId: string;
  amount: number;
  currency: string;
  arrivalDate: Date | null;
  status: PayoutStatus;
  type: string;
  automatic: boolean;
  description: string | null;
  bankAccountLast4: string | null;
  bankAccountName: string | null;
  grossTotal: number;
  feeTotal: number;
  refundTotal: number;
  paymentCount: number;
  failureCode: string | null;
  failureMessage: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const PayoutStatus$inboundSchema: z.ZodMiniType<PayoutStatus, unknown> =
  openEnums.inboundSchema(PayoutStatus);

/** @internal */
export const Payout$inboundSchema: z.ZodMiniType<Payout, unknown> = z.object({
  id: types.string(),
  stripePayoutId: types.string(),
  amount: types.number(),
  currency: types.string(),
  arrivalDate: types.nullable(types.date()),
  status: PayoutStatus$inboundSchema,
  type: types.string(),
  automatic: types.boolean(),
  description: types.nullable(types.string()),
  bankAccountLast4: types.nullable(types.string()),
  bankAccountName: types.nullable(types.string()),
  grossTotal: types.number(),
  feeTotal: types.number(),
  refundTotal: types.number(),
  paymentCount: types.number(),
  failureCode: types.nullable(types.string()),
  failureMessage: types.nullable(types.string()),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function payoutFromJSON(
  jsonString: string,
): SafeParseResult<Payout, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Payout$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Payout' from JSON`,
  );
}
