/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";
import { Project, Project$inboundSchema } from "./project.js";

export type ProjectList = {
  data: Array<Project>;
  pagination: PaginationMeta;
};

/** @internal */
export const ProjectList$inboundSchema: z.ZodMiniType<ProjectList, unknown> = z
  .object({
    data: z.array(Project$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function projectListFromJSON(
  jsonString: string,
): SafeParseResult<ProjectList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProjectList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProjectList' from JSON`,
  );
}
