/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const ProjectCreateStatus = {
  Active: "active",
  Paused: "paused",
  Completed: "completed",
} as const;
export type ProjectCreateStatus = ClosedEnum<typeof ProjectCreateStatus>;

export type ProjectCreate = {
  name: string;
  /**
   * UUID v4
   */
  clientId: string;
  status?: ProjectCreateStatus | undefined;
  /**
   * UUID v4
   */
  pipelineStageId?: string | undefined;
  startDate?: Date | undefined;
  endDate?: Date | undefined;
  eventDate?: Date | undefined;
  contractValue?: number | undefined;
};

/** @internal */
export const ProjectCreateStatus$outboundSchema: z.ZodMiniEnum<
  typeof ProjectCreateStatus
> = z.enum(ProjectCreateStatus);

/** @internal */
export type ProjectCreate$Outbound = {
  name: string;
  clientId: string;
  status: string;
  pipelineStageId?: string | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  eventDate?: string | undefined;
  contractValue?: number | undefined;
};

/** @internal */
export const ProjectCreate$outboundSchema: z.ZodMiniType<
  ProjectCreate$Outbound,
  ProjectCreate
> = z.object({
  name: z.string(),
  clientId: z.string(),
  status: z._default(ProjectCreateStatus$outboundSchema, "active"),
  pipelineStageId: z.optional(z.string()),
  startDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  endDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  eventDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  contractValue: z.optional(z.number()),
});

export function projectCreateToJSON(projectCreate: ProjectCreate): string {
  return JSON.stringify(ProjectCreate$outboundSchema.parse(projectCreate));
}
