/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const ProposalStatus = {
  Draft: "draft",
  Sent: "sent",
  Accepted: "accepted",
  Rejected: "rejected",
  Expired: "expired",
  Void: "void",
} as const;
export type ProposalStatus = OpenEnum<typeof ProposalStatus>;

export const ProposalSendMode = {
  Proposal: "proposal",
  Agreement: "agreement",
} as const;
export type ProposalSendMode = OpenEnum<typeof ProposalSendMode>;

export type Proposal = {
  /**
   * UUID v4
   */
  id: string;
  proposalNumber: string;
  title: string;
  /**
   * UUID v4
   */
  clientId: string;
  /**
   * UUID v4
   */
  billingContactId: string | null;
  /**
   * UUID v4
   */
  projectId: string | null;
  status: ProposalStatus;
  sendMode: ProposalSendMode;
  issueDate: Date | null;
  expirationDate: Date | null;
  eventDate: Date | null;
  currency: string;
  subtotal: number;
  discountAmount: number;
  taxAmount: number;
  total: number;
  notes: string | null;
  archived: boolean;
  /**
   * UUID v4
   */
  linkedContractId: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const ProposalStatus$inboundSchema: z.ZodMiniType<
  ProposalStatus,
  unknown
> = openEnums.inboundSchema(ProposalStatus);

/** @internal */
export const ProposalSendMode$inboundSchema: z.ZodMiniType<
  ProposalSendMode,
  unknown
> = openEnums.inboundSchema(ProposalSendMode);

/** @internal */
export const Proposal$inboundSchema: z.ZodMiniType<Proposal, unknown> = z
  .object({
    id: types.string(),
    proposalNumber: types.string(),
    title: types.string(),
    clientId: types.string(),
    billingContactId: types.nullable(types.string()),
    projectId: types.nullable(types.string()),
    status: ProposalStatus$inboundSchema,
    sendMode: ProposalSendMode$inboundSchema,
    issueDate: types.nullable(types.date()),
    expirationDate: types.nullable(types.date()),
    eventDate: types.nullable(types.date()),
    currency: types.string(),
    subtotal: types.number(),
    discountAmount: types.number(),
    taxAmount: types.number(),
    total: types.number(),
    notes: types.nullable(types.string()),
    archived: types.boolean(),
    linkedContractId: types.nullable(types.string()),
    createdAt: types.date(),
    updatedAt: types.date(),
  });

export function proposalFromJSON(
  jsonString: string,
): SafeParseResult<Proposal, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Proposal$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Proposal' from JSON`,
  );
}
