/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const ProposalCreateSendMode = {
  Proposal: "proposal",
  Agreement: "agreement",
} as const;
export type ProposalCreateSendMode = ClosedEnum<typeof ProposalCreateSendMode>;

export type ProposalCreate = {
  title: string;
  /**
   * UUID v4
   */
  clientId: string;
  /**
   * UUID v4
   */
  billingContactId?: string | undefined;
  /**
   * UUID v4
   */
  projectId?: string | undefined;
  sendMode?: ProposalCreateSendMode | undefined;
  issueDate?: Date | undefined;
  expirationDate?: Date | undefined;
  eventDate?: Date | undefined;
  notes?: string | undefined;
};

/** @internal */
export const ProposalCreateSendMode$outboundSchema: z.ZodMiniEnum<
  typeof ProposalCreateSendMode
> = z.enum(ProposalCreateSendMode);

/** @internal */
export type ProposalCreate$Outbound = {
  title: string;
  clientId: string;
  billingContactId?: string | undefined;
  projectId?: string | undefined;
  sendMode: string;
  issueDate?: string | undefined;
  expirationDate?: string | undefined;
  eventDate?: string | undefined;
  notes?: string | undefined;
};

/** @internal */
export const ProposalCreate$outboundSchema: z.ZodMiniType<
  ProposalCreate$Outbound,
  ProposalCreate
> = z.object({
  title: z.string(),
  clientId: z.string(),
  billingContactId: z.optional(z.string()),
  projectId: z.optional(z.string()),
  sendMode: z._default(ProposalCreateSendMode$outboundSchema, "proposal"),
  issueDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  expirationDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  eventDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  notes: z.optional(z.string()),
});

export function proposalCreateToJSON(proposalCreate: ProposalCreate): string {
  return JSON.stringify(ProposalCreate$outboundSchema.parse(proposalCreate));
}
