/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";
import { Proposal, Proposal$inboundSchema } from "./proposal.js";

export type ProposalList = {
  data: Array<Proposal>;
  pagination: PaginationMeta;
};

/** @internal */
export const ProposalList$inboundSchema: z.ZodMiniType<ProposalList, unknown> =
  z.object({
    data: z.array(Proposal$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function proposalListFromJSON(
  jsonString: string,
): SafeParseResult<ProposalList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ProposalList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ProposalList' from JSON`,
  );
}
