/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const ProposalUpdateStatus = {
  Draft: "draft",
  Sent: "sent",
  Void: "void",
} as const;
export type ProposalUpdateStatus = ClosedEnum<typeof ProposalUpdateStatus>;

export type ProposalUpdate = {
  title?: string | undefined;
  /**
   * UUID v4
   */
  billingContactId?: string | null | undefined;
  /**
   * UUID v4
   */
  projectId?: string | null | undefined;
  status?: ProposalUpdateStatus | undefined;
  issueDate?: Date | undefined;
  expirationDate?: Date | undefined;
  eventDate?: Date | null | undefined;
  notes?: string | null | undefined;
  archived?: boolean | undefined;
};

/** @internal */
export const ProposalUpdateStatus$outboundSchema: z.ZodMiniEnum<
  typeof ProposalUpdateStatus
> = z.enum(ProposalUpdateStatus);

/** @internal */
export type ProposalUpdate$Outbound = {
  title?: string | undefined;
  billingContactId?: string | null | undefined;
  projectId?: string | null | undefined;
  status?: string | undefined;
  issueDate?: string | undefined;
  expirationDate?: string | undefined;
  eventDate?: string | null | undefined;
  notes?: string | null | undefined;
  archived?: boolean | undefined;
};

/** @internal */
export const ProposalUpdate$outboundSchema: z.ZodMiniType<
  ProposalUpdate$Outbound,
  ProposalUpdate
> = z.object({
  title: z.optional(z.string()),
  billingContactId: z.optional(z.nullable(z.string())),
  projectId: z.optional(z.nullable(z.string())),
  status: z.optional(ProposalUpdateStatus$outboundSchema),
  issueDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  expirationDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  eventDate: z.optional(
    z.nullable(z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    )),
  ),
  notes: z.optional(z.nullable(z.string())),
  archived: z.optional(z.boolean()),
});

export function proposalUpdateToJSON(proposalUpdate: ProposalUpdate): string {
  return JSON.stringify(ProposalUpdate$outboundSchema.parse(proposalUpdate));
}
