/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";
import { Sale, Sale$inboundSchema } from "./sale.js";

export type SaleList = {
  data: Array<Sale>;
  pagination: PaginationMeta;
};

/** @internal */
export const SaleList$inboundSchema: z.ZodMiniType<SaleList, unknown> = z
  .object({
    data: z.array(Sale$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function saleListFromJSON(
  jsonString: string,
): SafeParseResult<SaleList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SaleList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SaleList' from JSON`,
  );
}
