/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const Channel = {
  Pos: "pos",
  Manual: "manual",
  Stripe: "stripe",
  Shopify: "shopify",
  Etsy: "etsy",
  SquareImport: "square-import",
  Api: "api",
} as const;
export type Channel = OpenEnum<typeof Channel>;

export const SaleStatus = {
  Completed: "completed",
  Refunded: "refunded",
  PartiallyRefunded: "partially-refunded",
  Voided: "voided",
} as const;
export type SaleStatus = OpenEnum<typeof SaleStatus>;

export type Sale = {
  /**
   * UUID v4
   */
  id: string;
  saleNumber: string;
  /**
   * UUID v4
   */
  businessId: string | null;
  /**
   * UUID v4
   */
  clientId: string | null;
  /**
   * UUID v4
   */
  contactId: string | null;
  channel: Channel;
  externalId: string | null;
  saleDate: Date;
  currency: string;
  status: SaleStatus;
  /**
   * ISO 8601 timestamp (UTC)
   */
  voidedAt: Date | null;
  voidReason: string | null;
  taxJurisdiction: string | null;
  taxInclusive: boolean;
  subtotal: number | null;
  discountPercent: number | null;
  discountAmount: number | null;
  taxRate: number | null;
  taxAmount: number | null;
  total: number | null;
  amountRefunded: number;
  notes: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const Channel$inboundSchema: z.ZodMiniType<Channel, unknown> = openEnums
  .inboundSchema(Channel);

/** @internal */
export const SaleStatus$inboundSchema: z.ZodMiniType<SaleStatus, unknown> =
  openEnums.inboundSchema(SaleStatus);

/** @internal */
export const Sale$inboundSchema: z.ZodMiniType<Sale, unknown> = z.object({
  id: types.string(),
  saleNumber: types.string(),
  businessId: types.nullable(types.string()),
  clientId: types.nullable(types.string()),
  contactId: types.nullable(types.string()),
  channel: Channel$inboundSchema,
  externalId: types.nullable(types.string()),
  saleDate: types.date(),
  currency: types.string(),
  status: SaleStatus$inboundSchema,
  voidedAt: types.nullable(types.date()),
  voidReason: types.nullable(types.string()),
  taxJurisdiction: types.nullable(types.string()),
  taxInclusive: types.boolean(),
  subtotal: types.nullable(types.number()),
  discountPercent: types.nullable(types.number()),
  discountAmount: types.nullable(types.number()),
  taxRate: types.nullable(types.number()),
  taxAmount: types.nullable(types.number()),
  total: types.nullable(types.number()),
  amountRefunded: types.number(),
  notes: types.nullable(types.string()),
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function saleFromJSON(
  jsonString: string,
): SafeParseResult<Sale, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Sale$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Sale' from JSON`,
  );
}
