/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const TimeEntryCreateRateType = {
  Standard: "standard",
  Overtime: "overtime",
  Emergency: "emergency",
  Custom: "custom",
} as const;
export type TimeEntryCreateRateType = ClosedEnum<
  typeof TimeEntryCreateRateType
>;

export type TimeEntryCreate = {
  /**
   * UUID v4
   */
  projectId: string;
  /**
   * UUID v4
   */
  memberId: string;
  /**
   * UUID v4
   */
  catalogItemId?: string | undefined;
  date: Date;
  hours: number;
  description?: string | undefined;
  billable?: boolean | undefined;
  rateType?: TimeEntryCreateRateType | undefined;
  customMultiplierName?: string | undefined;
  rateOverride?: number | undefined;
  discountPercent?: number | undefined;
  workerName?: string | undefined;
};

/** @internal */
export const TimeEntryCreateRateType$outboundSchema: z.ZodMiniEnum<
  typeof TimeEntryCreateRateType
> = z.enum(TimeEntryCreateRateType);

/** @internal */
export type TimeEntryCreate$Outbound = {
  projectId: string;
  memberId: string;
  catalogItemId?: string | undefined;
  date: string;
  hours: number;
  description?: string | undefined;
  billable: boolean;
  rateType: string;
  customMultiplierName?: string | undefined;
  rateOverride?: number | undefined;
  discountPercent?: number | undefined;
  workerName?: string | undefined;
};

/** @internal */
export const TimeEntryCreate$outboundSchema: z.ZodMiniType<
  TimeEntryCreate$Outbound,
  TimeEntryCreate
> = z.object({
  projectId: z.string(),
  memberId: z.string(),
  catalogItemId: z.optional(z.string()),
  date: z.pipe(
    z.date(),
    z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
  ),
  hours: z.number(),
  description: z.optional(z.string()),
  billable: z._default(z.boolean(), true),
  rateType: z._default(TimeEntryCreateRateType$outboundSchema, "standard"),
  customMultiplierName: z.optional(z.string()),
  rateOverride: z.optional(z.number()),
  discountPercent: z.optional(z.number()),
  workerName: z.optional(z.string()),
});

export function timeEntryCreateToJSON(
  timeEntryCreate: TimeEntryCreate,
): string {
  return JSON.stringify(TimeEntryCreate$outboundSchema.parse(timeEntryCreate));
}
