/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";
import { TimeEntry, TimeEntry$inboundSchema } from "./time-entry.js";

export type TimeEntryList = {
  data: Array<TimeEntry>;
  pagination: PaginationMeta;
};

/** @internal */
export const TimeEntryList$inboundSchema: z.ZodMiniType<
  TimeEntryList,
  unknown
> = z.object({
  data: z.array(TimeEntry$inboundSchema),
  pagination: PaginationMeta$inboundSchema,
});

export function timeEntryListFromJSON(
  jsonString: string,
): SafeParseResult<TimeEntryList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TimeEntryList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TimeEntryList' from JSON`,
  );
}
