/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const TimelineItemCreateAnchorType = {
  None: "none",
  Fixed: "fixed",
  Ceremony: "ceremony",
  EventStart: "event-start",
  Sunset: "sunset",
  Sunrise: "sunrise",
  CustomEvent: "custom-event",
} as const;
export type TimelineItemCreateAnchorType = ClosedEnum<
  typeof TimelineItemCreateAnchorType
>;

export const TimelineItemCreateVisibleTo = {
  Master: "master",
  Couple: "couple",
  VendorAll: "vendor-all",
  Venue: "venue",
  ShotList: "shot-list",
  Party: "party",
} as const;
export type TimelineItemCreateVisibleTo = ClosedEnum<
  typeof TimelineItemCreateVisibleTo
>;

export const TimelineItemCreateStatus = {
  Pending: "pending",
  InProgress: "in-progress",
  Completed: "completed",
  Skipped: "skipped",
} as const;
export type TimelineItemCreateStatus = ClosedEnum<
  typeof TimelineItemCreateStatus
>;

export type TimelineItemCreate = {
  eventDayId: string;
  title: string;
  description?: string | undefined;
  categoryId?: string | undefined;
  sortOrder?: number | undefined;
  trackId?: string | undefined;
  requestedStartTime?: string | undefined;
  durationMinutes: number;
  bufferBeforeMinutes?: number | undefined;
  bufferAfterMinutes?: number | undefined;
  travelTimeMinutes?: number | undefined;
  locked?: boolean | undefined;
  anchorType?: TimelineItemCreateAnchorType | undefined;
  anchorKey?: string | undefined;
  location?: string | undefined;
  visibleTo?: Array<TimelineItemCreateVisibleTo> | undefined;
  vendorIds?: Array<string> | undefined;
  status?: TimelineItemCreateStatus | undefined;
};

/** @internal */
export const TimelineItemCreateAnchorType$outboundSchema: z.ZodMiniEnum<
  typeof TimelineItemCreateAnchorType
> = z.enum(TimelineItemCreateAnchorType);

/** @internal */
export const TimelineItemCreateVisibleTo$outboundSchema: z.ZodMiniEnum<
  typeof TimelineItemCreateVisibleTo
> = z.enum(TimelineItemCreateVisibleTo);

/** @internal */
export const TimelineItemCreateStatus$outboundSchema: z.ZodMiniEnum<
  typeof TimelineItemCreateStatus
> = z.enum(TimelineItemCreateStatus);

/** @internal */
export type TimelineItemCreate$Outbound = {
  eventDayId: string;
  title: string;
  description?: string | undefined;
  categoryId?: string | undefined;
  sortOrder?: number | undefined;
  trackId?: string | undefined;
  requestedStartTime?: string | undefined;
  durationMinutes: number;
  bufferBeforeMinutes?: number | undefined;
  bufferAfterMinutes?: number | undefined;
  travelTimeMinutes?: number | undefined;
  locked?: boolean | undefined;
  anchorType?: string | undefined;
  anchorKey?: string | undefined;
  location?: string | undefined;
  visibleTo?: Array<string> | undefined;
  vendorIds?: Array<string> | undefined;
  status?: string | undefined;
};

/** @internal */
export const TimelineItemCreate$outboundSchema: z.ZodMiniType<
  TimelineItemCreate$Outbound,
  TimelineItemCreate
> = z.object({
  eventDayId: z.string(),
  title: z.string(),
  description: z.optional(z.string()),
  categoryId: z.optional(z.string()),
  sortOrder: z.optional(z.int()),
  trackId: z.optional(z.string()),
  requestedStartTime: z.optional(z.string()),
  durationMinutes: z.int(),
  bufferBeforeMinutes: z.optional(z.int()),
  bufferAfterMinutes: z.optional(z.int()),
  travelTimeMinutes: z.optional(z.int()),
  locked: z.optional(z.boolean()),
  anchorType: z.optional(TimelineItemCreateAnchorType$outboundSchema),
  anchorKey: z.optional(z.string()),
  location: z.optional(z.string()),
  visibleTo: z.optional(z.array(TimelineItemCreateVisibleTo$outboundSchema)),
  vendorIds: z.optional(z.array(z.string())),
  status: z.optional(TimelineItemCreateStatus$outboundSchema),
});

export function timelineItemCreateToJSON(
  timelineItemCreate: TimelineItemCreate,
): string {
  return JSON.stringify(
    TimelineItemCreate$outboundSchema.parse(timelineItemCreate),
  );
}
