/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const TimeEntryUpdateRateType = {
  Standard: "standard",
  Overtime: "overtime",
  Emergency: "emergency",
  Custom: "custom",
} as const;
export type TimeEntryUpdateRateType = ClosedEnum<
  typeof TimeEntryUpdateRateType
>;

export type TimeEntryUpdate = {
  /**
   * UUID v4
   */
  projectId?: string | undefined;
  /**
   * UUID v4
   */
  memberId?: string | undefined;
  /**
   * UUID v4
   */
  catalogItemId?: string | undefined;
  date?: Date | undefined;
  hours?: number | undefined;
  description?: string | undefined;
  billable?: boolean | undefined;
  rateType?: TimeEntryUpdateRateType | undefined;
  customMultiplierName?: string | undefined;
  rateOverride?: number | undefined;
  workerName?: string | undefined;
};

/** @internal */
export const TimeEntryUpdateRateType$outboundSchema: z.ZodMiniEnum<
  typeof TimeEntryUpdateRateType
> = z.enum(TimeEntryUpdateRateType);

/** @internal */
export type TimeEntryUpdate$Outbound = {
  projectId?: string | undefined;
  memberId?: string | undefined;
  catalogItemId?: string | undefined;
  date?: string | undefined;
  hours?: number | undefined;
  description?: string | undefined;
  billable: boolean;
  rateType: string;
  customMultiplierName?: string | undefined;
  rateOverride?: number | undefined;
  workerName?: string | undefined;
};

/** @internal */
export const TimeEntryUpdate$outboundSchema: z.ZodMiniType<
  TimeEntryUpdate$Outbound,
  TimeEntryUpdate
> = z.object({
  projectId: z.optional(z.string()),
  memberId: z.optional(z.string()),
  catalogItemId: z.optional(z.string()),
  date: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  hours: z.optional(z.number()),
  description: z.optional(z.string()),
  billable: z._default(z.boolean(), true),
  rateType: z._default(TimeEntryUpdateRateType$outboundSchema, "standard"),
  customMultiplierName: z.optional(z.string()),
  rateOverride: z.optional(z.number()),
  workerName: z.optional(z.string()),
});

export function timeEntryUpdateToJSON(
  timeEntryUpdate: TimeEntryUpdate,
): string {
  return JSON.stringify(TimeEntryUpdate$outboundSchema.parse(timeEntryUpdate));
}
