/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

/**
 * How the item is timed. 'none' floats (the cascade solves its time from order + duration). 'fixed' pins the item's START to requestedStartTime (HH:MM). 'fixed-end' pins the item's END to requestedStartTime — a hard stop / curfew / 'must be done by'; the schedule back-solves the items before it to fit (pin = end − duration). 'custom-event' pins to a named Key Moment via anchorKey. 'sunset'/'sunrise' pin to the venue's golden hour. 'ceremony'/'event-start' are legacy named anchors.
 */
export const TimelineItemUpdateAnchorType = {
  None: "none",
  Fixed: "fixed",
  FixedEnd: "fixed-end",
  Ceremony: "ceremony",
  EventStart: "event-start",
  Sunset: "sunset",
  Sunrise: "sunrise",
  CustomEvent: "custom-event",
} as const;
/**
 * How the item is timed. 'none' floats (the cascade solves its time from order + duration). 'fixed' pins the item's START to requestedStartTime (HH:MM). 'fixed-end' pins the item's END to requestedStartTime — a hard stop / curfew / 'must be done by'; the schedule back-solves the items before it to fit (pin = end − duration). 'custom-event' pins to a named Key Moment via anchorKey. 'sunset'/'sunrise' pin to the venue's golden hour. 'ceremony'/'event-start' are legacy named anchors.
 */
export type TimelineItemUpdateAnchorType = ClosedEnum<
  typeof TimelineItemUpdateAnchorType
>;

export const TimelineItemUpdateVisibleTo = {
  Master: "master",
  Couple: "couple",
  VendorAll: "vendor-all",
  Venue: "venue",
  ShotList: "shot-list",
  Party: "party",
} as const;
export type TimelineItemUpdateVisibleTo = ClosedEnum<
  typeof TimelineItemUpdateVisibleTo
>;

export const TimelineItemUpdateStatus = {
  Pending: "pending",
  InProgress: "in-progress",
  Completed: "completed",
  Skipped: "skipped",
} as const;
export type TimelineItemUpdateStatus = ClosedEnum<
  typeof TimelineItemUpdateStatus
>;

export type TimelineItemUpdate = {
  eventDayId?: string | undefined;
  title?: string | undefined;
  description?: string | null | undefined;
  categoryId?: string | null | undefined;
  sortOrder?: number | undefined;
  trackId?: string | null | undefined;
  requestedStartTime?: string | null | undefined;
  durationMinutes?: number | undefined;
  bufferBeforeMinutes?: number | undefined;
  bufferAfterMinutes?: number | undefined;
  travelTimeMinutes?: number | undefined;
  locked?: boolean | undefined;
  /**
   * How the item is timed. 'none' floats (the cascade solves its time from order + duration). 'fixed' pins the item's START to requestedStartTime (HH:MM). 'fixed-end' pins the item's END to requestedStartTime — a hard stop / curfew / 'must be done by'; the schedule back-solves the items before it to fit (pin = end − duration). 'custom-event' pins to a named Key Moment via anchorKey. 'sunset'/'sunrise' pin to the venue's golden hour. 'ceremony'/'event-start' are legacy named anchors.
   */
  anchorType?: TimelineItemUpdateAnchorType | undefined;
  anchorKey?: string | null | undefined;
  location?: string | null | undefined;
  visibleTo?: Array<TimelineItemUpdateVisibleTo> | undefined;
  vendorIds?: Array<string> | undefined;
  status?: TimelineItemUpdateStatus | undefined;
};

/** @internal */
export const TimelineItemUpdateAnchorType$outboundSchema: z.ZodMiniEnum<
  typeof TimelineItemUpdateAnchorType
> = z.enum(TimelineItemUpdateAnchorType);

/** @internal */
export const TimelineItemUpdateVisibleTo$outboundSchema: z.ZodMiniEnum<
  typeof TimelineItemUpdateVisibleTo
> = z.enum(TimelineItemUpdateVisibleTo);

/** @internal */
export const TimelineItemUpdateStatus$outboundSchema: z.ZodMiniEnum<
  typeof TimelineItemUpdateStatus
> = z.enum(TimelineItemUpdateStatus);

/** @internal */
export type TimelineItemUpdate$Outbound = {
  eventDayId?: string | undefined;
  title?: string | undefined;
  description?: string | null | undefined;
  categoryId?: string | null | undefined;
  sortOrder?: number | undefined;
  trackId?: string | null | undefined;
  requestedStartTime?: string | null | undefined;
  durationMinutes?: number | undefined;
  bufferBeforeMinutes?: number | undefined;
  bufferAfterMinutes?: number | undefined;
  travelTimeMinutes?: number | undefined;
  locked?: boolean | undefined;
  anchorType?: string | undefined;
  anchorKey?: string | null | undefined;
  location?: string | null | undefined;
  visibleTo?: Array<string> | undefined;
  vendorIds?: Array<string> | undefined;
  status?: string | undefined;
};

/** @internal */
export const TimelineItemUpdate$outboundSchema: z.ZodMiniType<
  TimelineItemUpdate$Outbound,
  TimelineItemUpdate
> = z.object({
  eventDayId: z.optional(z.string()),
  title: z.optional(z.string()),
  description: z.optional(z.nullable(z.string())),
  categoryId: z.optional(z.nullable(z.string())),
  sortOrder: z.optional(z.int()),
  trackId: z.optional(z.nullable(z.string())),
  requestedStartTime: z.optional(z.nullable(z.string())),
  durationMinutes: z.optional(z.int()),
  bufferBeforeMinutes: z.optional(z.int()),
  bufferAfterMinutes: z.optional(z.int()),
  travelTimeMinutes: z.optional(z.int()),
  locked: z.optional(z.boolean()),
  anchorType: z.optional(TimelineItemUpdateAnchorType$outboundSchema),
  anchorKey: z.optional(z.nullable(z.string())),
  location: z.optional(z.nullable(z.string())),
  visibleTo: z.optional(z.array(TimelineItemUpdateVisibleTo$outboundSchema)),
  vendorIds: z.optional(z.array(z.string())),
  status: z.optional(TimelineItemUpdateStatus$outboundSchema),
});

export function timelineItemUpdateToJSON(
  timelineItemUpdate: TimelineItemUpdate,
): string {
  return JSON.stringify(
    TimelineItemUpdate$outboundSchema.parse(timelineItemUpdate),
  );
}
