/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export const TimeEntryRateType = {
  Standard: "standard",
  Overtime: "overtime",
  Emergency: "emergency",
  Custom: "custom",
} as const;
export type TimeEntryRateType = OpenEnum<typeof TimeEntryRateType>;

export type TimeEntry = {
  /**
   * UUID v4
   */
  id: string;
  /**
   * UUID v4
   */
  projectId: string;
  /**
   * UUID v4
   */
  clientId: string;
  /**
   * UUID v4
   */
  memberId: string;
  /**
   * UUID v4
   */
  catalogItemId: string | null;
  date: Date;
  hours: number;
  description: string | null;
  billable: boolean;
  rateType: TimeEntryRateType;
  customMultiplierName: string | null;
  rateOverride: number | null;
  effectiveRate: number | null;
  workerName: string | null;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const TimeEntryRateType$inboundSchema: z.ZodMiniType<
  TimeEntryRateType,
  unknown
> = openEnums.inboundSchema(TimeEntryRateType);

/** @internal */
export const TimeEntry$inboundSchema: z.ZodMiniType<TimeEntry, unknown> = z
  .object({
    id: types.string(),
    projectId: types.string(),
    clientId: types.string(),
    memberId: types.string(),
    catalogItemId: types.nullable(types.string()),
    date: types.date(),
    hours: types.number(),
    description: types.nullable(types.string()),
    billable: types.boolean(),
    rateType: TimeEntryRateType$inboundSchema,
    customMultiplierName: types.nullable(types.string()),
    rateOverride: types.nullable(types.number()),
    effectiveRate: types.nullable(types.number()),
    workerName: types.nullable(types.string()),
    createdAt: types.date(),
    updatedAt: types.date(),
  });

export function timeEntryFromJSON(
  jsonString: string,
): SafeParseResult<TimeEntry, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TimeEntry$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TimeEntry' from JSON`,
  );
}
