/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";
import { Transaction, Transaction$inboundSchema } from "./transaction.js";

export type TransactionList = {
  data: Array<Transaction>;
  pagination: PaginationMeta;
};

/** @internal */
export const TransactionList$inboundSchema: z.ZodMiniType<
  TransactionList,
  unknown
> = z.object({
  data: z.array(Transaction$inboundSchema),
  pagination: PaginationMeta$inboundSchema,
});

export function transactionListFromJSON(
  jsonString: string,
): SafeParseResult<TransactionList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TransactionList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TransactionList' from JSON`,
  );
}
