/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const TransactionCreateFrequency = {
  OneTime: "one-time",
  Monthly: "monthly",
  Quarterly: "quarterly",
  Annual: "annual",
} as const;
export type TransactionCreateFrequency = ClosedEnum<
  typeof TransactionCreateFrequency
>;

export const TransactionCreateDirection = {
  Cost: "cost",
  Revenue: "revenue",
} as const;
export type TransactionCreateDirection = ClosedEnum<
  typeof TransactionCreateDirection
>;

export const TransactionCreateMode = {
  Each: "each",
  Split: "split",
  Global: "global",
} as const;
export type TransactionCreateMode = ClosedEnum<typeof TransactionCreateMode>;

export type TransactionCreateAssignment = {
  /**
   * UUID v4
   */
  projectId?: string | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
  amount?: number | undefined;
  percentage?: number | undefined;
  fixedAmount?: number | undefined;
  startDate?: Date | undefined;
  endDate?: Date | undefined;
};

export const TransactionCreateStatus = {
  Active: "active",
  Paused: "paused",
  Archived: "archived",
} as const;
export type TransactionCreateStatus = ClosedEnum<
  typeof TransactionCreateStatus
>;

export type TransactionCreate = {
  name: string;
  /**
   * UUID v4
   */
  catalogItemId?: string | undefined;
  /**
   * UUID v4
   */
  taxCategoryId?: string | undefined;
  amount: number;
  frequency?: TransactionCreateFrequency | undefined;
  direction: TransactionCreateDirection;
  mode?: TransactionCreateMode | undefined;
  splitEvenly?: boolean | undefined;
  assignments?: Array<TransactionCreateAssignment> | undefined;
  passThrough?: boolean | undefined;
  markupPercent?: number | undefined;
  startDate?: Date | undefined;
  endDate?: Date | undefined;
  notes?: string | undefined;
  vendorName?: string | undefined;
  vendorEmail?: string | undefined;
  vendorTaxId?: string | undefined;
  status?: TransactionCreateStatus | undefined;
};

/** @internal */
export const TransactionCreateFrequency$outboundSchema: z.ZodMiniEnum<
  typeof TransactionCreateFrequency
> = z.enum(TransactionCreateFrequency);

/** @internal */
export const TransactionCreateDirection$outboundSchema: z.ZodMiniEnum<
  typeof TransactionCreateDirection
> = z.enum(TransactionCreateDirection);

/** @internal */
export const TransactionCreateMode$outboundSchema: z.ZodMiniEnum<
  typeof TransactionCreateMode
> = z.enum(TransactionCreateMode);

/** @internal */
export type TransactionCreateAssignment$Outbound = {
  projectId?: string | undefined;
  clientId?: string | undefined;
  amount?: number | undefined;
  percentage?: number | undefined;
  fixedAmount?: number | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
};

/** @internal */
export const TransactionCreateAssignment$outboundSchema: z.ZodMiniType<
  TransactionCreateAssignment$Outbound,
  TransactionCreateAssignment
> = z.object({
  projectId: z.optional(z.string()),
  clientId: z.optional(z.string()),
  amount: z.optional(z.number()),
  percentage: z.optional(z.number()),
  fixedAmount: z.optional(z.number()),
  startDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  endDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
});

export function transactionCreateAssignmentToJSON(
  transactionCreateAssignment: TransactionCreateAssignment,
): string {
  return JSON.stringify(
    TransactionCreateAssignment$outboundSchema.parse(
      transactionCreateAssignment,
    ),
  );
}

/** @internal */
export const TransactionCreateStatus$outboundSchema: z.ZodMiniEnum<
  typeof TransactionCreateStatus
> = z.enum(TransactionCreateStatus);

/** @internal */
export type TransactionCreate$Outbound = {
  name: string;
  catalogItemId?: string | undefined;
  taxCategoryId?: string | undefined;
  amount: number;
  frequency: string;
  direction: string;
  mode: string;
  splitEvenly?: boolean | undefined;
  assignments?: Array<TransactionCreateAssignment$Outbound> | undefined;
  passThrough?: boolean | undefined;
  markupPercent?: number | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  notes?: string | undefined;
  vendorName?: string | undefined;
  vendorEmail?: string | undefined;
  vendorTaxId?: string | undefined;
  status: string;
};

/** @internal */
export const TransactionCreate$outboundSchema: z.ZodMiniType<
  TransactionCreate$Outbound,
  TransactionCreate
> = z.object({
  name: z.string(),
  catalogItemId: z.optional(z.string()),
  taxCategoryId: z.optional(z.string()),
  amount: z.number(),
  frequency: z._default(TransactionCreateFrequency$outboundSchema, "one-time"),
  direction: TransactionCreateDirection$outboundSchema,
  mode: z._default(TransactionCreateMode$outboundSchema, "each"),
  splitEvenly: z.optional(z.boolean()),
  assignments: z.optional(
    z.array(z.lazy(() => TransactionCreateAssignment$outboundSchema)),
  ),
  passThrough: z.optional(z.boolean()),
  markupPercent: z.optional(z.number()),
  startDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  endDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  notes: z.optional(z.string()),
  vendorName: z.optional(z.string()),
  vendorEmail: z.optional(z.string()),
  vendorTaxId: z.optional(z.string()),
  status: z._default(TransactionCreateStatus$outboundSchema, "active"),
});

export function transactionCreateToJSON(
  transactionCreate: TransactionCreate,
): string {
  return JSON.stringify(
    TransactionCreate$outboundSchema.parse(transactionCreate),
  );
}
