/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const TransactionUpdateFrequency = {
  OneTime: "one-time",
  Monthly: "monthly",
  Quarterly: "quarterly",
  Annual: "annual",
} as const;
export type TransactionUpdateFrequency = ClosedEnum<
  typeof TransactionUpdateFrequency
>;

export const TransactionUpdateDirection = {
  Cost: "cost",
  Revenue: "revenue",
} as const;
export type TransactionUpdateDirection = ClosedEnum<
  typeof TransactionUpdateDirection
>;

export const TransactionUpdateMode = {
  Each: "each",
  Split: "split",
  Global: "global",
} as const;
export type TransactionUpdateMode = ClosedEnum<typeof TransactionUpdateMode>;

export type TransactionUpdateAssignment = {
  /**
   * UUID v4
   */
  projectId?: string | undefined;
  /**
   * UUID v4
   */
  clientId?: string | undefined;
  amount?: number | undefined;
  percentage?: number | undefined;
  fixedAmount?: number | undefined;
  startDate?: Date | undefined;
  endDate?: Date | undefined;
};

export const TransactionUpdateStatus = {
  Active: "active",
  Paused: "paused",
  Archived: "archived",
} as const;
export type TransactionUpdateStatus = ClosedEnum<
  typeof TransactionUpdateStatus
>;

export type TransactionUpdate = {
  name?: string | undefined;
  /**
   * UUID v4
   */
  catalogItemId?: string | undefined;
  /**
   * UUID v4
   */
  taxCategoryId?: string | undefined;
  amount?: number | undefined;
  frequency?: TransactionUpdateFrequency | undefined;
  direction?: TransactionUpdateDirection | undefined;
  mode?: TransactionUpdateMode | undefined;
  splitEvenly?: boolean | undefined;
  assignments?: Array<TransactionUpdateAssignment> | undefined;
  passThrough?: boolean | undefined;
  markupPercent?: number | undefined;
  startDate?: Date | undefined;
  endDate?: Date | undefined;
  notes?: string | undefined;
  vendorName?: string | undefined;
  vendorEmail?: string | undefined;
  vendorTaxId?: string | undefined;
  status?: TransactionUpdateStatus | undefined;
};

/** @internal */
export const TransactionUpdateFrequency$outboundSchema: z.ZodMiniEnum<
  typeof TransactionUpdateFrequency
> = z.enum(TransactionUpdateFrequency);

/** @internal */
export const TransactionUpdateDirection$outboundSchema: z.ZodMiniEnum<
  typeof TransactionUpdateDirection
> = z.enum(TransactionUpdateDirection);

/** @internal */
export const TransactionUpdateMode$outboundSchema: z.ZodMiniEnum<
  typeof TransactionUpdateMode
> = z.enum(TransactionUpdateMode);

/** @internal */
export type TransactionUpdateAssignment$Outbound = {
  projectId?: string | undefined;
  clientId?: string | undefined;
  amount?: number | undefined;
  percentage?: number | undefined;
  fixedAmount?: number | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
};

/** @internal */
export const TransactionUpdateAssignment$outboundSchema: z.ZodMiniType<
  TransactionUpdateAssignment$Outbound,
  TransactionUpdateAssignment
> = z.object({
  projectId: z.optional(z.string()),
  clientId: z.optional(z.string()),
  amount: z.optional(z.number()),
  percentage: z.optional(z.number()),
  fixedAmount: z.optional(z.number()),
  startDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  endDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
});

export function transactionUpdateAssignmentToJSON(
  transactionUpdateAssignment: TransactionUpdateAssignment,
): string {
  return JSON.stringify(
    TransactionUpdateAssignment$outboundSchema.parse(
      transactionUpdateAssignment,
    ),
  );
}

/** @internal */
export const TransactionUpdateStatus$outboundSchema: z.ZodMiniEnum<
  typeof TransactionUpdateStatus
> = z.enum(TransactionUpdateStatus);

/** @internal */
export type TransactionUpdate$Outbound = {
  name?: string | undefined;
  catalogItemId?: string | undefined;
  taxCategoryId?: string | undefined;
  amount?: number | undefined;
  frequency: string;
  direction?: string | undefined;
  mode: string;
  splitEvenly?: boolean | undefined;
  assignments?: Array<TransactionUpdateAssignment$Outbound> | undefined;
  passThrough?: boolean | undefined;
  markupPercent?: number | undefined;
  startDate?: string | undefined;
  endDate?: string | undefined;
  notes?: string | undefined;
  vendorName?: string | undefined;
  vendorEmail?: string | undefined;
  vendorTaxId?: string | undefined;
  status: string;
};

/** @internal */
export const TransactionUpdate$outboundSchema: z.ZodMiniType<
  TransactionUpdate$Outbound,
  TransactionUpdate
> = z.object({
  name: z.optional(z.string()),
  catalogItemId: z.optional(z.string()),
  taxCategoryId: z.optional(z.string()),
  amount: z.optional(z.number()),
  frequency: z._default(TransactionUpdateFrequency$outboundSchema, "one-time"),
  direction: z.optional(TransactionUpdateDirection$outboundSchema),
  mode: z._default(TransactionUpdateMode$outboundSchema, "each"),
  splitEvenly: z.optional(z.boolean()),
  assignments: z.optional(
    z.array(z.lazy(() => TransactionUpdateAssignment$outboundSchema)),
  ),
  passThrough: z.optional(z.boolean()),
  markupPercent: z.optional(z.number()),
  startDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  endDate: z.optional(
    z.pipe(
      z.date(),
      z.transform(v => v.toISOString().slice(0, "YYYY-MM-DD".length)),
    ),
  ),
  notes: z.optional(z.string()),
  vendorName: z.optional(z.string()),
  vendorEmail: z.optional(z.string()),
  vendorTaxId: z.optional(z.string()),
  status: z._default(TransactionUpdateStatus$outboundSchema, "active"),
});

export function transactionUpdateToJSON(
  transactionUpdate: TransactionUpdate,
): string {
  return JSON.stringify(
    TransactionUpdate$outboundSchema.parse(transactionUpdate),
  );
}
