/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export type VendorCreateAddress = {
  street?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  zip?: string | undefined;
};

export const VendorCreateRating = {
  Preferred: "preferred",
  Approved: "approved",
  Neutral: "neutral",
  Avoid: "avoid",
} as const;
export type VendorCreateRating = ClosedEnum<typeof VendorCreateRating>;

export const VendorCreateStatus = {
  Active: "active",
  Archived: "archived",
} as const;
export type VendorCreateStatus = ClosedEnum<typeof VendorCreateStatus>;

export type VendorCreate = {
  name: string;
  companyName?: string | undefined;
  /**
   * UUID v4
   */
  categoryId?: string | undefined;
  email?: string | undefined;
  phone?: string | undefined;
  website?: string | undefined;
  address?: VendorCreateAddress | undefined;
  notes?: string | undefined;
  rating?: VendorCreateRating | undefined;
  defaultSetupMinutes?: number | undefined;
  defaultTeardownMinutes?: number | undefined;
  /**
   * UUID v4
   */
  linkedContactId?: string | undefined;
  status?: VendorCreateStatus | undefined;
};

/** @internal */
export type VendorCreateAddress$Outbound = {
  street?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  zip?: string | undefined;
};

/** @internal */
export const VendorCreateAddress$outboundSchema: z.ZodMiniType<
  VendorCreateAddress$Outbound,
  VendorCreateAddress
> = z.object({
  street: z.optional(z.string()),
  city: z.optional(z.string()),
  state: z.optional(z.string()),
  zip: z.optional(z.string()),
});

export function vendorCreateAddressToJSON(
  vendorCreateAddress: VendorCreateAddress,
): string {
  return JSON.stringify(
    VendorCreateAddress$outboundSchema.parse(vendorCreateAddress),
  );
}

/** @internal */
export const VendorCreateRating$outboundSchema: z.ZodMiniEnum<
  typeof VendorCreateRating
> = z.enum(VendorCreateRating);

/** @internal */
export const VendorCreateStatus$outboundSchema: z.ZodMiniEnum<
  typeof VendorCreateStatus
> = z.enum(VendorCreateStatus);

/** @internal */
export type VendorCreate$Outbound = {
  name: string;
  companyName?: string | undefined;
  categoryId?: string | undefined;
  email?: string | undefined;
  phone?: string | undefined;
  website?: string | undefined;
  address?: VendorCreateAddress$Outbound | undefined;
  notes?: string | undefined;
  rating?: string | undefined;
  defaultSetupMinutes?: number | undefined;
  defaultTeardownMinutes?: number | undefined;
  linkedContactId?: string | undefined;
  status: string;
};

/** @internal */
export const VendorCreate$outboundSchema: z.ZodMiniType<
  VendorCreate$Outbound,
  VendorCreate
> = z.object({
  name: z.string(),
  companyName: z.optional(z.string()),
  categoryId: z.optional(z.string()),
  email: z.optional(z.string()),
  phone: z.optional(z.string()),
  website: z.optional(z.string()),
  address: z.optional(z.lazy(() => VendorCreateAddress$outboundSchema)),
  notes: z.optional(z.string()),
  rating: z.optional(VendorCreateRating$outboundSchema),
  defaultSetupMinutes: z.optional(z.int()),
  defaultTeardownMinutes: z.optional(z.int()),
  linkedContactId: z.optional(z.string()),
  status: z._default(VendorCreateStatus$outboundSchema, "active"),
});

export function vendorCreateToJSON(vendorCreate: VendorCreate): string {
  return JSON.stringify(VendorCreate$outboundSchema.parse(vendorCreate));
}
