/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import * as openEnums from "../types/enums.js";
import { OpenEnum } from "../types/enums.js";
import { Result as SafeParseResult } from "../types/fp.js";
import * as types from "../types/primitives.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";

export type VendorAddress = {
  street: string | null;
  city: string | null;
  state: string | null;
  zip: string | null;
};

export const VendorRating = {
  Preferred: "preferred",
  Approved: "approved",
  Neutral: "neutral",
  Avoid: "avoid",
} as const;
export type VendorRating = OpenEnum<typeof VendorRating>;

export const VendorStatus = {
  Active: "active",
  Archived: "archived",
} as const;
export type VendorStatus = OpenEnum<typeof VendorStatus>;

export type Vendor = {
  /**
   * UUID v4
   */
  id: string;
  name: string;
  companyName: string | null;
  /**
   * UUID v4
   */
  categoryId: string | null;
  email: string | null;
  phone: string | null;
  website: string | null;
  address: VendorAddress | null;
  notes: string | null;
  rating: VendorRating | null;
  defaultSetupMinutes: number | null;
  defaultTeardownMinutes: number | null;
  /**
   * UUID v4
   */
  linkedContactId: string | null;
  status: VendorStatus;
  /**
   * ISO 8601 timestamp (UTC)
   */
  createdAt: Date;
  /**
   * ISO 8601 timestamp (UTC)
   */
  updatedAt: Date;
};

/** @internal */
export const VendorAddress$inboundSchema: z.ZodMiniType<
  VendorAddress,
  unknown
> = z.object({
  street: types.nullable(types.string()),
  city: types.nullable(types.string()),
  state: types.nullable(types.string()),
  zip: types.nullable(types.string()),
});

export function vendorAddressFromJSON(
  jsonString: string,
): SafeParseResult<VendorAddress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VendorAddress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VendorAddress' from JSON`,
  );
}

/** @internal */
export const VendorRating$inboundSchema: z.ZodMiniType<VendorRating, unknown> =
  openEnums.inboundSchema(VendorRating);

/** @internal */
export const VendorStatus$inboundSchema: z.ZodMiniType<VendorStatus, unknown> =
  openEnums.inboundSchema(VendorStatus);

/** @internal */
export const Vendor$inboundSchema: z.ZodMiniType<Vendor, unknown> = z.object({
  id: types.string(),
  name: types.string(),
  companyName: types.nullable(types.string()),
  categoryId: types.nullable(types.string()),
  email: types.nullable(types.string()),
  phone: types.nullable(types.string()),
  website: types.nullable(types.string()),
  address: types.nullable(z.lazy(() => VendorAddress$inboundSchema)),
  notes: types.nullable(types.string()),
  rating: types.nullable(VendorRating$inboundSchema),
  defaultSetupMinutes: types.nullable(types.number()),
  defaultTeardownMinutes: types.nullable(types.number()),
  linkedContactId: types.nullable(types.string()),
  status: VendorStatus$inboundSchema,
  createdAt: types.date(),
  updatedAt: types.date(),
});

export function vendorFromJSON(
  jsonString: string,
): SafeParseResult<Vendor, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Vendor$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Vendor' from JSON`,
  );
}
