/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";
import { Vendor, Vendor$inboundSchema } from "./vendor.js";

export type VendorList = {
  data: Array<Vendor>;
  pagination: PaginationMeta;
};

/** @internal */
export const VendorList$inboundSchema: z.ZodMiniType<VendorList, unknown> = z
  .object({
    data: z.array(Vendor$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function vendorListFromJSON(
  jsonString: string,
): SafeParseResult<VendorList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VendorList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VendorList' from JSON`,
  );
}
