/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";
import { Venue, Venue$inboundSchema } from "./venue.js";

export type VenueList = {
  data: Array<Venue>;
  pagination: PaginationMeta;
};

/** @internal */
export const VenueList$inboundSchema: z.ZodMiniType<VenueList, unknown> = z
  .object({
    data: z.array(Venue$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function venueListFromJSON(
  jsonString: string,
): SafeParseResult<VenueList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VenueList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VenueList' from JSON`,
  );
}
