/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export type VenueCreateAddress = {
  line1?: string | undefined;
  line2?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postalCode?: string | undefined;
  country?: string | undefined;
  lat?: number | undefined;
  lng?: number | undefined;
};

export type VenueCreateContact = {
  name?: string | undefined;
  role?: string | undefined;
  email?: string | undefined;
  phone?: string | undefined;
};

export type VenueCreateSpace = {
  name: string;
  notes?: string | undefined;
};

export const VenueCreateStatus = {
  Active: "active",
  Archived: "archived",
} as const;
export type VenueCreateStatus = ClosedEnum<typeof VenueCreateStatus>;

export type VenueCreate = {
  name: string;
  website?: string | undefined;
  address?: VenueCreateAddress | undefined;
  timezone?: string | undefined;
  contacts?: Array<VenueCreateContact> | undefined;
  spaces?: Array<VenueCreateSpace> | undefined;
  notes?: string | undefined;
  tagIds?: Array<string> | undefined;
  status?: VenueCreateStatus | undefined;
};

/** @internal */
export type VenueCreateAddress$Outbound = {
  line1?: string | undefined;
  line2?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postalCode?: string | undefined;
  country?: string | undefined;
  lat?: number | undefined;
  lng?: number | undefined;
};

/** @internal */
export const VenueCreateAddress$outboundSchema: z.ZodMiniType<
  VenueCreateAddress$Outbound,
  VenueCreateAddress
> = z.object({
  line1: z.optional(z.string()),
  line2: z.optional(z.string()),
  city: z.optional(z.string()),
  state: z.optional(z.string()),
  postalCode: z.optional(z.string()),
  country: z.optional(z.string()),
  lat: z.optional(z.number()),
  lng: z.optional(z.number()),
});

export function venueCreateAddressToJSON(
  venueCreateAddress: VenueCreateAddress,
): string {
  return JSON.stringify(
    VenueCreateAddress$outboundSchema.parse(venueCreateAddress),
  );
}

/** @internal */
export type VenueCreateContact$Outbound = {
  name?: string | undefined;
  role?: string | undefined;
  email?: string | undefined;
  phone?: string | undefined;
};

/** @internal */
export const VenueCreateContact$outboundSchema: z.ZodMiniType<
  VenueCreateContact$Outbound,
  VenueCreateContact
> = z.object({
  name: z.optional(z.string()),
  role: z.optional(z.string()),
  email: z.optional(z.string()),
  phone: z.optional(z.string()),
});

export function venueCreateContactToJSON(
  venueCreateContact: VenueCreateContact,
): string {
  return JSON.stringify(
    VenueCreateContact$outboundSchema.parse(venueCreateContact),
  );
}

/** @internal */
export type VenueCreateSpace$Outbound = {
  name: string;
  notes?: string | undefined;
};

/** @internal */
export const VenueCreateSpace$outboundSchema: z.ZodMiniType<
  VenueCreateSpace$Outbound,
  VenueCreateSpace
> = z.object({
  name: z.string(),
  notes: z.optional(z.string()),
});

export function venueCreateSpaceToJSON(
  venueCreateSpace: VenueCreateSpace,
): string {
  return JSON.stringify(
    VenueCreateSpace$outboundSchema.parse(venueCreateSpace),
  );
}

/** @internal */
export const VenueCreateStatus$outboundSchema: z.ZodMiniEnum<
  typeof VenueCreateStatus
> = z.enum(VenueCreateStatus);

/** @internal */
export type VenueCreate$Outbound = {
  name: string;
  website?: string | undefined;
  address?: VenueCreateAddress$Outbound | undefined;
  timezone?: string | undefined;
  contacts?: Array<VenueCreateContact$Outbound> | undefined;
  spaces?: Array<VenueCreateSpace$Outbound> | undefined;
  notes?: string | undefined;
  tagIds?: Array<string> | undefined;
  status: string;
};

/** @internal */
export const VenueCreate$outboundSchema: z.ZodMiniType<
  VenueCreate$Outbound,
  VenueCreate
> = z.object({
  name: z.string(),
  website: z.optional(z.string()),
  address: z.optional(z.lazy(() => VenueCreateAddress$outboundSchema)),
  timezone: z.optional(z.string()),
  contacts: z.optional(
    z.array(z.lazy(() => VenueCreateContact$outboundSchema)),
  ),
  spaces: z.optional(z.array(z.lazy(() => VenueCreateSpace$outboundSchema))),
  notes: z.optional(z.string()),
  tagIds: z.optional(z.array(z.string())),
  status: z._default(VenueCreateStatus$outboundSchema, "active"),
});

export function venueCreateToJSON(venueCreate: VenueCreate): string {
  return JSON.stringify(VenueCreate$outboundSchema.parse(venueCreate));
}
