/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export type VenueUpdateAddress = {
  line1?: string | undefined;
  line2?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postalCode?: string | undefined;
  country?: string | undefined;
  lat?: number | undefined;
  lng?: number | undefined;
};

export type VenueUpdateContact = {
  name?: string | undefined;
  role?: string | undefined;
  email?: string | undefined;
  phone?: string | undefined;
};

export type VenueUpdateSpace = {
  name: string;
  notes?: string | undefined;
};

export const VenueUpdateStatus = {
  Active: "active",
  Archived: "archived",
} as const;
export type VenueUpdateStatus = ClosedEnum<typeof VenueUpdateStatus>;

export type VenueUpdate = {
  name?: string | undefined;
  website?: string | null | undefined;
  address?: VenueUpdateAddress | undefined;
  timezone?: string | null | undefined;
  contacts?: Array<VenueUpdateContact> | undefined;
  spaces?: Array<VenueUpdateSpace> | undefined;
  notes?: string | null | undefined;
  tagIds?: Array<string> | undefined;
  status?: VenueUpdateStatus | undefined;
};

/** @internal */
export type VenueUpdateAddress$Outbound = {
  line1?: string | undefined;
  line2?: string | undefined;
  city?: string | undefined;
  state?: string | undefined;
  postalCode?: string | undefined;
  country?: string | undefined;
  lat?: number | undefined;
  lng?: number | undefined;
};

/** @internal */
export const VenueUpdateAddress$outboundSchema: z.ZodMiniType<
  VenueUpdateAddress$Outbound,
  VenueUpdateAddress
> = z.object({
  line1: z.optional(z.string()),
  line2: z.optional(z.string()),
  city: z.optional(z.string()),
  state: z.optional(z.string()),
  postalCode: z.optional(z.string()),
  country: z.optional(z.string()),
  lat: z.optional(z.number()),
  lng: z.optional(z.number()),
});

export function venueUpdateAddressToJSON(
  venueUpdateAddress: VenueUpdateAddress,
): string {
  return JSON.stringify(
    VenueUpdateAddress$outboundSchema.parse(venueUpdateAddress),
  );
}

/** @internal */
export type VenueUpdateContact$Outbound = {
  name?: string | undefined;
  role?: string | undefined;
  email?: string | undefined;
  phone?: string | undefined;
};

/** @internal */
export const VenueUpdateContact$outboundSchema: z.ZodMiniType<
  VenueUpdateContact$Outbound,
  VenueUpdateContact
> = z.object({
  name: z.optional(z.string()),
  role: z.optional(z.string()),
  email: z.optional(z.string()),
  phone: z.optional(z.string()),
});

export function venueUpdateContactToJSON(
  venueUpdateContact: VenueUpdateContact,
): string {
  return JSON.stringify(
    VenueUpdateContact$outboundSchema.parse(venueUpdateContact),
  );
}

/** @internal */
export type VenueUpdateSpace$Outbound = {
  name: string;
  notes?: string | undefined;
};

/** @internal */
export const VenueUpdateSpace$outboundSchema: z.ZodMiniType<
  VenueUpdateSpace$Outbound,
  VenueUpdateSpace
> = z.object({
  name: z.string(),
  notes: z.optional(z.string()),
});

export function venueUpdateSpaceToJSON(
  venueUpdateSpace: VenueUpdateSpace,
): string {
  return JSON.stringify(
    VenueUpdateSpace$outboundSchema.parse(venueUpdateSpace),
  );
}

/** @internal */
export const VenueUpdateStatus$outboundSchema: z.ZodMiniEnum<
  typeof VenueUpdateStatus
> = z.enum(VenueUpdateStatus);

/** @internal */
export type VenueUpdate$Outbound = {
  name?: string | undefined;
  website?: string | null | undefined;
  address?: VenueUpdateAddress$Outbound | undefined;
  timezone?: string | null | undefined;
  contacts?: Array<VenueUpdateContact$Outbound> | undefined;
  spaces?: Array<VenueUpdateSpace$Outbound> | undefined;
  notes?: string | null | undefined;
  tagIds?: Array<string> | undefined;
  status?: string | undefined;
};

/** @internal */
export const VenueUpdate$outboundSchema: z.ZodMiniType<
  VenueUpdate$Outbound,
  VenueUpdate
> = z.object({
  name: z.optional(z.string()),
  website: z.optional(z.nullable(z.string())),
  address: z.optional(z.lazy(() => VenueUpdateAddress$outboundSchema)),
  timezone: z.optional(z.nullable(z.string())),
  contacts: z.optional(
    z.array(z.lazy(() => VenueUpdateContact$outboundSchema)),
  ),
  spaces: z.optional(z.array(z.lazy(() => VenueUpdateSpace$outboundSchema))),
  notes: z.optional(z.nullable(z.string())),
  tagIds: z.optional(z.array(z.string())),
  status: z.optional(VenueUpdateStatus$outboundSchema),
});

export function venueUpdateToJSON(venueUpdate: VenueUpdate): string {
  return JSON.stringify(VenueUpdate$outboundSchema.parse(venueUpdate));
}
