/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdk-validation-error.js";
import {
  PaginationMeta,
  PaginationMeta$inboundSchema,
} from "./pagination-meta.js";
import { Webhook, Webhook$inboundSchema } from "./webhook.js";

export type WebhookList = {
  data: Array<Webhook>;
  pagination: PaginationMeta;
};

/** @internal */
export const WebhookList$inboundSchema: z.ZodMiniType<WebhookList, unknown> = z
  .object({
    data: z.array(Webhook$inboundSchema),
    pagination: PaginationMeta$inboundSchema,
  });

export function webhookListFromJSON(
  jsonString: string,
): SafeParseResult<WebhookList, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookList$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookList' from JSON`,
  );
}
