/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../types/enums.js";

export const WebhookUpdateEvent = {
  ProposalSent: "proposal_sent",
  ProposalExpiring: "proposal_expiring",
  ProposalAccepted: "proposal_accepted",
  ProposalRejected: "proposal_rejected",
  ProposalExpired: "proposal_expired",
  ProposalViewed: "proposal_viewed",
  InvoiceSent: "invoice_sent",
  InvoiceDueSoon: "invoice_due_soon",
  InvoiceOverdue: "invoice_overdue",
  InvoicePaid: "invoice_paid",
  InvoicePaymentFailed: "invoice_payment_failed",
  InvoiceDisputed: "invoice_disputed",
  InvoicePaymentReminder: "invoice_payment_reminder",
  InvoiceViewed: "invoice_viewed",
  PaymentReceived: "payment_received",
  PaymentRefunded: "payment_refunded",
  PaymentApplied: "payment_applied",
  PaymentUnapplied: "payment_unapplied",
  PaymentDeleted: "payment_deleted",
  PaymentChargeback: "payment_chargeback",
  ReceiptSent: "receipt_sent",
  ScheduleDepositReady: "schedule_deposit_ready",
  ScheduleInstallmentDue: "schedule_installment_due",
  ScheduleInstallmentPaid: "schedule_installment_paid",
  ScheduleCompleted: "schedule_completed",
  DocumentProcessed: "document_processed",
  DocumentActionCreated: "document_action_created",
  DocumentActionApproved: "document_action_approved",
  DocumentNeedsReview: "document_needs_review",
  DocumentFailed: "document_failed",
  ClientCreated: "client_created",
  ContactCreated: "contact_created",
  ProjectCreated: "project_created",
  TimeEntryCreated: "time_entry_created",
  InquiryCreated: "inquiry_created",
  InquiryStatusChanged: "inquiry_status_changed",
  InquiryConverted: "inquiry_converted",
  MilestoneApproaching: "milestone_approaching",
  TimerRunningReminder: "timer_running_reminder",
  ContractSent: "contract_sent",
  ContractViewed: "contract_viewed",
  ContractSigned: "contract_signed",
  ContractRecipientSigned: "contract_recipient_signed",
  ContractCountersigned: "contract_countersigned",
  ContractCompleted: "contract_completed",
  ContractExpired: "contract_expired",
  ContractVoided: "contract_voided",
  QuestionnaireSent: "questionnaire_sent",
  QuestionnaireCompleted: "questionnaire_completed",
  SubscriptionPaymentFailed: "subscription_payment_failed",
  PayoutPaid: "payout_paid",
  PayoutFailed: "payout_failed",
} as const;
export type WebhookUpdateEvent = ClosedEnum<typeof WebhookUpdateEvent>;

export type WebhookUpdate = {
  name?: string | undefined;
  url?: string | undefined;
  events?: Array<WebhookUpdateEvent> | undefined;
  enabled?: boolean | undefined;
  secret?: string | null | undefined;
};

/** @internal */
export const WebhookUpdateEvent$outboundSchema: z.ZodMiniEnum<
  typeof WebhookUpdateEvent
> = z.enum(WebhookUpdateEvent);

/** @internal */
export type WebhookUpdate$Outbound = {
  name?: string | undefined;
  url?: string | undefined;
  events?: Array<string> | undefined;
  enabled?: boolean | undefined;
  secret?: string | null | undefined;
};

/** @internal */
export const WebhookUpdate$outboundSchema: z.ZodMiniType<
  WebhookUpdate$Outbound,
  WebhookUpdate
> = z.object({
  name: z.optional(z.string()),
  url: z.optional(z.string()),
  events: z.optional(z.array(WebhookUpdateEvent$outboundSchema)),
  enabled: z.optional(z.boolean()),
  secret: z.optional(z.nullable(z.string())),
});

export function webhookUpdateToJSON(webhookUpdate: WebhookUpdate): string {
  return JSON.stringify(WebhookUpdate$outboundSchema.parse(webhookUpdate));
}
